// Code generated by mockery v2.53.5. DO NOT EDIT.

package grpc

import (
	context "context"
	io "io"
	model "secure-rag-platform/services/knowledge/internal/model"
	usecase "secure-rag-platform/services/knowledge/internal/usecase"

	mock "github.com/stretchr/testify/mock"
)

// MockDocumentUsecase is an autogenerated mock type for the DocumentUsecaseContract type
type MockDocumentUsecase struct {
	mock.Mock
}

type MockDocumentUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDocumentUsecase) EXPECT() *MockDocumentUsecase_Expecter {
	return &MockDocumentUsecase_Expecter{mock: &_m.Mock}
}

// CreateDocument provides a mock function with given fields: ctx, input, file, fileName, mimeType
func (_m *MockDocumentUsecase) CreateDocument(ctx context.Context, input usecase.CreateDocumentInput, file io.Reader, fileName string, mimeType string) (*usecase.CreateDocumentOutput, error) {
	ret := _m.Called(ctx, input, file, fileName, mimeType)

	if len(ret) == 0 {
		panic("no return value specified for CreateDocument")
	}

	var r0 *usecase.CreateDocumentOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.CreateDocumentInput, io.Reader, string, string) (*usecase.CreateDocumentOutput, error)); ok {
		return rf(ctx, input, file, fileName, mimeType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecase.CreateDocumentInput, io.Reader, string, string) *usecase.CreateDocumentOutput); ok {
		r0 = rf(ctx, input, file, fileName, mimeType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*usecase.CreateDocumentOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecase.CreateDocumentInput, io.Reader, string, string) error); ok {
		r1 = rf(ctx, input, file, fileName, mimeType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDocumentUsecase_CreateDocument_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDocument'
type MockDocumentUsecase_CreateDocument_Call struct {
	*mock.Call
}

// CreateDocument is a helper method to define mock.On call
//   - ctx context.Context
//   - input usecase.CreateDocumentInput
//   - file io.Reader
//   - fileName string
//   - mimeType string
func (_e *MockDocumentUsecase_Expecter) CreateDocument(ctx interface{}, input interface{}, file interface{}, fileName interface{}, mimeType interface{}) *MockDocumentUsecase_CreateDocument_Call {
	return &MockDocumentUsecase_CreateDocument_Call{Call: _e.mock.On("CreateDocument", ctx, input, file, fileName, mimeType)}
}

func (_c *MockDocumentUsecase_CreateDocument_Call) Run(run func(ctx context.Context, input usecase.CreateDocumentInput, file io.Reader, fileName string, mimeType string)) *MockDocumentUsecase_CreateDocument_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecase.CreateDocumentInput), args[2].(io.Reader), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MockDocumentUsecase_CreateDocument_Call) Return(_a0 *usecase.CreateDocumentOutput, _a1 error) *MockDocumentUsecase_CreateDocument_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDocumentUsecase_CreateDocument_Call) RunAndReturn(run func(context.Context, usecase.CreateDocumentInput, io.Reader, string, string) (*usecase.CreateDocumentOutput, error)) *MockDocumentUsecase_CreateDocument_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteDocument provides a mock function with given fields: ctx, docUUID
func (_m *MockDocumentUsecase) DeleteDocument(ctx context.Context, docUUID string) (*usecase.DeleteDocumentOutput, error) {
	ret := _m.Called(ctx, docUUID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDocument")
	}

	var r0 *usecase.DeleteDocumentOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*usecase.DeleteDocumentOutput, error)); ok {
		return rf(ctx, docUUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *usecase.DeleteDocumentOutput); ok {
		r0 = rf(ctx, docUUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*usecase.DeleteDocumentOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, docUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDocumentUsecase_DeleteDocument_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteDocument'
type MockDocumentUsecase_DeleteDocument_Call struct {
	*mock.Call
}

// DeleteDocument is a helper method to define mock.On call
//   - ctx context.Context
//   - docUUID string
func (_e *MockDocumentUsecase_Expecter) DeleteDocument(ctx interface{}, docUUID interface{}) *MockDocumentUsecase_DeleteDocument_Call {
	return &MockDocumentUsecase_DeleteDocument_Call{Call: _e.mock.On("DeleteDocument", ctx, docUUID)}
}

func (_c *MockDocumentUsecase_DeleteDocument_Call) Run(run func(ctx context.Context, docUUID string)) *MockDocumentUsecase_DeleteDocument_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDocumentUsecase_DeleteDocument_Call) Return(_a0 *usecase.DeleteDocumentOutput, _a1 error) *MockDocumentUsecase_DeleteDocument_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDocumentUsecase_DeleteDocument_Call) RunAndReturn(run func(context.Context, string) (*usecase.DeleteDocumentOutput, error)) *MockDocumentUsecase_DeleteDocument_Call {
	_c.Call.Return(run)
	return _c
}

// DownloadFile provides a mock function with given fields: ctx, docUUID
func (_m *MockDocumentUsecase) DownloadFile(ctx context.Context, docUUID string) (*usecase.FileDownload, error) {
	ret := _m.Called(ctx, docUUID)

	if len(ret) == 0 {
		panic("no return value specified for DownloadFile")
	}

	var r0 *usecase.FileDownload
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*usecase.FileDownload, error)); ok {
		return rf(ctx, docUUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *usecase.FileDownload); ok {
		r0 = rf(ctx, docUUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*usecase.FileDownload)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, docUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDocumentUsecase_DownloadFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownloadFile'
type MockDocumentUsecase_DownloadFile_Call struct {
	*mock.Call
}

// DownloadFile is a helper method to define mock.On call
//   - ctx context.Context
//   - docUUID string
func (_e *MockDocumentUsecase_Expecter) DownloadFile(ctx interface{}, docUUID interface{}) *MockDocumentUsecase_DownloadFile_Call {
	return &MockDocumentUsecase_DownloadFile_Call{Call: _e.mock.On("DownloadFile", ctx, docUUID)}
}

func (_c *MockDocumentUsecase_DownloadFile_Call) Run(run func(ctx context.Context, docUUID string)) *MockDocumentUsecase_DownloadFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDocumentUsecase_DownloadFile_Call) Return(_a0 *usecase.FileDownload, _a1 error) *MockDocumentUsecase_DownloadFile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDocumentUsecase_DownloadFile_Call) RunAndReturn(run func(context.Context, string) (*usecase.FileDownload, error)) *MockDocumentUsecase_DownloadFile_Call {
	_c.Call.Return(run)
	return _c
}

// GetDocument provides a mock function with given fields: ctx, docUUID
func (_m *MockDocumentUsecase) GetDocument(ctx context.Context, docUUID string) (*usecase.DocumentDetail, error) {
	ret := _m.Called(ctx, docUUID)

	if len(ret) == 0 {
		panic("no return value specified for GetDocument")
	}

	var r0 *usecase.DocumentDetail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*usecase.DocumentDetail, error)); ok {
		return rf(ctx, docUUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *usecase.DocumentDetail); ok {
		r0 = rf(ctx, docUUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*usecase.DocumentDetail)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, docUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDocumentUsecase_GetDocument_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDocument'
type MockDocumentUsecase_GetDocument_Call struct {
	*mock.Call
}

// GetDocument is a helper method to define mock.On call
//   - ctx context.Context
//   - docUUID string
func (_e *MockDocumentUsecase_Expecter) GetDocument(ctx interface{}, docUUID interface{}) *MockDocumentUsecase_GetDocument_Call {
	return &MockDocumentUsecase_GetDocument_Call{Call: _e.mock.On("GetDocument", ctx, docUUID)}
}

func (_c *MockDocumentUsecase_GetDocument_Call) Run(run func(ctx context.Context, docUUID string)) *MockDocumentUsecase_GetDocument_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDocumentUsecase_GetDocument_Call) Return(_a0 *usecase.DocumentDetail, _a1 error) *MockDocumentUsecase_GetDocument_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDocumentUsecase_GetDocument_Call) RunAndReturn(run func(context.Context, string) (*usecase.DocumentDetail, error)) *MockDocumentUsecase_GetDocument_Call {
	_c.Call.Return(run)
	return _c
}

// ListDocuments provides a mock function with given fields: ctx
func (_m *MockDocumentUsecase) ListDocuments(ctx context.Context) ([]*usecase.DocumentDetail, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListDocuments")
	}

	var r0 []*usecase.DocumentDetail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*usecase.DocumentDetail, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*usecase.DocumentDetail); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*usecase.DocumentDetail)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDocumentUsecase_ListDocuments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDocuments'
type MockDocumentUsecase_ListDocuments_Call struct {
	*mock.Call
}

// ListDocuments is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDocumentUsecase_Expecter) ListDocuments(ctx interface{}) *MockDocumentUsecase_ListDocuments_Call {
	return &MockDocumentUsecase_ListDocuments_Call{Call: _e.mock.On("ListDocuments", ctx)}
}

func (_c *MockDocumentUsecase_ListDocuments_Call) Run(run func(ctx context.Context)) *MockDocumentUsecase_ListDocuments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDocumentUsecase_ListDocuments_Call) Return(_a0 []*usecase.DocumentDetail, _a1 error) *MockDocumentUsecase_ListDocuments_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDocumentUsecase_ListDocuments_Call) RunAndReturn(run func(context.Context) ([]*usecase.DocumentDetail, error)) *MockDocumentUsecase_ListDocuments_Call {
	_c.Call.Return(run)
	return _c
}

// ReindexDocument provides a mock function with given fields: ctx, docUUID
func (_m *MockDocumentUsecase) ReindexDocument(ctx context.Context, docUUID string) (*usecase.ReindexOutput, error) {
	ret := _m.Called(ctx, docUUID)

	if len(ret) == 0 {
		panic("no return value specified for ReindexDocument")
	}

	var r0 *usecase.ReindexOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*usecase.ReindexOutput, error)); ok {
		return rf(ctx, docUUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *usecase.ReindexOutput); ok {
		r0 = rf(ctx, docUUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*usecase.ReindexOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, docUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDocumentUsecase_ReindexDocument_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReindexDocument'
type MockDocumentUsecase_ReindexDocument_Call struct {
	*mock.Call
}

// ReindexDocument is a helper method to define mock.On call
//   - ctx context.Context
//   - docUUID string
func (_e *MockDocumentUsecase_Expecter) ReindexDocument(ctx interface{}, docUUID interface{}) *MockDocumentUsecase_ReindexDocument_Call {
	return &MockDocumentUsecase_ReindexDocument_Call{Call: _e.mock.On("ReindexDocument", ctx, docUUID)}
}

func (_c *MockDocumentUsecase_ReindexDocument_Call) Run(run func(ctx context.Context, docUUID string)) *MockDocumentUsecase_ReindexDocument_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDocumentUsecase_ReindexDocument_Call) Return(_a0 *usecase.ReindexOutput, _a1 error) *MockDocumentUsecase_ReindexDocument_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDocumentUsecase_ReindexDocument_Call) RunAndReturn(run func(context.Context, string) (*usecase.ReindexOutput, error)) *MockDocumentUsecase_ReindexDocument_Call {
	_c.Call.Return(run)
	return _c
}

// RestoreDocument provides a mock function with given fields: ctx, docUUID
func (_m *MockDocumentUsecase) RestoreDocument(ctx context.Context, docUUID string) (*model.Document, error) {
	ret := _m.Called(ctx, docUUID)

	if len(ret) == 0 {
		panic("no return value specified for RestoreDocument")
	}

	var r0 *model.Document
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Document, error)); ok {
		return rf(ctx, docUUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Document); ok {
		r0 = rf(ctx, docUUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Document)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, docUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDocumentUsecase_RestoreDocument_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestoreDocument'
type MockDocumentUsecase_RestoreDocument_Call struct {
	*mock.Call
}

// RestoreDocument is a helper method to define mock.On call
//   - ctx context.Context
//   - docUUID string
func (_e *MockDocumentUsecase_Expecter) RestoreDocument(ctx interface{}, docUUID interface{}) *MockDocumentUsecase_RestoreDocument_Call {
	return &MockDocumentUsecase_RestoreDocument_Call{Call: _e.mock.On("RestoreDocument", ctx, docUUID)}
}

func (_c *MockDocumentUsecase_RestoreDocument_Call) Run(run func(ctx context.Context, docUUID string)) *MockDocumentUsecase_RestoreDocument_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDocumentUsecase_RestoreDocument_Call) Return(_a0 *model.Document, _a1 error) *MockDocumentUsecase_RestoreDocument_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDocumentUsecase_RestoreDocument_Call) RunAndReturn(run func(context.Context, string) (*model.Document, error)) *MockDocumentUsecase_RestoreDocument_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAttributes provides a mock function with given fields: ctx, docUUID, attributes
func (_m *MockDocumentUsecase) UpdateAttributes(ctx context.Context, docUUID string, attributes map[string]interface{}) (*model.Document, error) {
	ret := _m.Called(ctx, docUUID, attributes)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAttributes")
	}

	var r0 *model.Document
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}) (*model.Document, error)); ok {
		return rf(ctx, docUUID, attributes)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}) *model.Document); ok {
		r0 = rf(ctx, docUUID, attributes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Document)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, map[string]interface{}) error); ok {
		r1 = rf(ctx, docUUID, attributes)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDocumentUsecase_UpdateAttributes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAttributes'
type MockDocumentUsecase_UpdateAttributes_Call struct {
	*mock.Call
}

// UpdateAttributes is a helper method to define mock.On call
//   - ctx context.Context
//   - docUUID string
//   - attributes map[string]interface{}
func (_e *MockDocumentUsecase_Expecter) UpdateAttributes(ctx interface{}, docUUID interface{}, attributes interface{}) *MockDocumentUsecase_UpdateAttributes_Call {
	return &MockDocumentUsecase_UpdateAttributes_Call{Call: _e.mock.On("UpdateAttributes", ctx, docUUID, attributes)}
}

func (_c *MockDocumentUsecase_UpdateAttributes_Call) Run(run func(ctx context.Context, docUUID string, attributes map[string]interface{})) *MockDocumentUsecase_UpdateAttributes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(map[string]interface{}))
	})
	return _c
}

func (_c *MockDocumentUsecase_UpdateAttributes_Call) Return(_a0 *model.Document, _a1 error) *MockDocumentUsecase_UpdateAttributes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDocumentUsecase_UpdateAttributes_Call) RunAndReturn(run func(context.Context, string, map[string]interface{}) (*model.Document, error)) *MockDocumentUsecase_UpdateAttributes_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDocument provides a mock function with given fields: ctx, docUUID, title, description
func (_m *MockDocumentUsecase) UpdateDocument(ctx context.Context, docUUID string, title *string, description *string) (*model.Document, error) {
	ret := _m.Called(ctx, docUUID, title, description)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDocument")
	}

	var r0 *model.Document
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *string, *string) (*model.Document, error)); ok {
		return rf(ctx, docUUID, title, description)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *string, *string) *model.Document); ok {
		r0 = rf(ctx, docUUID, title, description)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Document)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *string, *string) error); ok {
		r1 = rf(ctx, docUUID, title, description)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDocumentUsecase_UpdateDocument_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDocument'
type MockDocumentUsecase_UpdateDocument_Call struct {
	*mock.Call
}

// UpdateDocument is a helper method to define mock.On call
//   - ctx context.Context
//   - docUUID string
//   - title *string
//   - description *string
func (_e *MockDocumentUsecase_Expecter) UpdateDocument(ctx interface{}, docUUID interface{}, title interface{}, description interface{}) *MockDocumentUsecase_UpdateDocument_Call {
	return &MockDocumentUsecase_UpdateDocument_Call{Call: _e.mock.On("UpdateDocument", ctx, docUUID, title, description)}
}

func (_c *MockDocumentUsecase_UpdateDocument_Call) Run(run func(ctx context.Context, docUUID string, title *string, description *string)) *MockDocumentUsecase_UpdateDocument_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*string), args[3].(*string))
	})
	return _c
}

func (_c *MockDocumentUsecase_UpdateDocument_Call) Return(_a0 *model.Document, _a1 error) *MockDocumentUsecase_UpdateDocument_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDocumentUsecase_UpdateDocument_Call) RunAndReturn(run func(context.Context, string, *string, *string) (*model.Document, error)) *MockDocumentUsecase_UpdateDocument_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDocumentUsecase creates a new instance of MockDocumentUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDocumentUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDocumentUsecase {
	mock := &MockDocumentUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
