// Code generated by grpcstubgen. DO NOT EDIT.

package grpc

import (
	"context"

	pb "secure-rag-platform/api/gen/go/knowledge/v1"
)

func (s *KnowledgeServiceServerImpl) Health(ctx context.Context, req *pb.HealthRequest) (*pb.HealthResponse, error) {
	return &pb.HealthResponse{Status: "ok"}, nil
}
