// Code generated by grpcstubgen. DO NOT EDIT.

package grpc

import (
	pb "example.com/project/knowledge/gen/v1"
)

type KnowledgeServiceServerImpl struct {
	pb.UnimplementedKnowledgeServiceServer
}

var _ pb.KnowledgeServiceServer = (*KnowledgeServiceServerImpl)(nil)
