// Code generated by grpcstubgen. DO NOT EDIT.

package grpc

import (
	"context"
	pb "secure-rag-platform/services/knowledge/gen/v1"

	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

func (s *KnowledgeServiceServerImpl) Search(ctx context.Context, req *pb.SearchRequest) (*pb.SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
