// Code generated by grpcstubgen. DO NOT EDIT.

package grpc

import (
	"context"
	pb "secure-rag-platform/services/rag/gen/v1"

	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

func (s *RAGServiceServerImpl) Query(ctx context.Context, req *pb.QueryRequest) (*pb.QueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Query not implemented")
}
