// Code generated by mockery v2.53.5. DO NOT EDIT.

package grpc

import (
	context "context"
	usecase "secure-rag-platform/services/rag/internal/usecase"

	mock "github.com/stretchr/testify/mock"
)

// MockRAGUsecase is an autogenerated mock type for the RAGUsecase type
type MockRAGUsecase struct {
	mock.Mock
}

type MockRAGUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRAGUsecase) EXPECT() *MockRAGUsecase_Expecter {
	return &MockRAGUsecase_Expecter{mock: &_m.Mock}
}

// DeleteDocumentIndex provides a mock function with given fields: _a0, _a1
func (_m *MockRAGUsecase) DeleteDocumentIndex(_a0 context.Context, _a1 string) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDocumentIndex")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRAGUsecase_DeleteDocumentIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteDocumentIndex'
type MockRAGUsecase_DeleteDocumentIndex_Call struct {
	*mock.Call
}

// DeleteDocumentIndex is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *MockRAGUsecase_Expecter) DeleteDocumentIndex(_a0 interface{}, _a1 interface{}) *MockRAGUsecase_DeleteDocumentIndex_Call {
	return &MockRAGUsecase_DeleteDocumentIndex_Call{Call: _e.mock.On("DeleteDocumentIndex", _a0, _a1)}
}

func (_c *MockRAGUsecase_DeleteDocumentIndex_Call) Run(run func(_a0 context.Context, _a1 string)) *MockRAGUsecase_DeleteDocumentIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRAGUsecase_DeleteDocumentIndex_Call) Return(_a0 error) *MockRAGUsecase_DeleteDocumentIndex_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRAGUsecase_DeleteDocumentIndex_Call) RunAndReturn(run func(context.Context, string) error) *MockRAGUsecase_DeleteDocumentIndex_Call {
	_c.Call.Return(run)
	return _c
}

// IndexDocument provides a mock function with given fields: _a0, _a1
func (_m *MockRAGUsecase) IndexDocument(_a0 context.Context, _a1 usecase.IndexDocumentRequest) (*usecase.IndexDocumentResult, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for IndexDocument")
	}

	var r0 *usecase.IndexDocumentResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.IndexDocumentRequest) (*usecase.IndexDocumentResult, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecase.IndexDocumentRequest) *usecase.IndexDocumentResult); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*usecase.IndexDocumentResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecase.IndexDocumentRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRAGUsecase_IndexDocument_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IndexDocument'
type MockRAGUsecase_IndexDocument_Call struct {
	*mock.Call
}

// IndexDocument is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 usecase.IndexDocumentRequest
func (_e *MockRAGUsecase_Expecter) IndexDocument(_a0 interface{}, _a1 interface{}) *MockRAGUsecase_IndexDocument_Call {
	return &MockRAGUsecase_IndexDocument_Call{Call: _e.mock.On("IndexDocument", _a0, _a1)}
}

func (_c *MockRAGUsecase_IndexDocument_Call) Run(run func(_a0 context.Context, _a1 usecase.IndexDocumentRequest)) *MockRAGUsecase_IndexDocument_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecase.IndexDocumentRequest))
	})
	return _c
}

func (_c *MockRAGUsecase_IndexDocument_Call) Return(_a0 *usecase.IndexDocumentResult, _a1 error) *MockRAGUsecase_IndexDocument_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRAGUsecase_IndexDocument_Call) RunAndReturn(run func(context.Context, usecase.IndexDocumentRequest) (*usecase.IndexDocumentResult, error)) *MockRAGUsecase_IndexDocument_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function with given fields: _a0, _a1
func (_m *MockRAGUsecase) Query(_a0 context.Context, _a1 usecase.QueryRequest) (*usecase.QueryResult, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 *usecase.QueryResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.QueryRequest) (*usecase.QueryResult, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecase.QueryRequest) *usecase.QueryResult); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*usecase.QueryResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecase.QueryRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRAGUsecase_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockRAGUsecase_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 usecase.QueryRequest
func (_e *MockRAGUsecase_Expecter) Query(_a0 interface{}, _a1 interface{}) *MockRAGUsecase_Query_Call {
	return &MockRAGUsecase_Query_Call{Call: _e.mock.On("Query", _a0, _a1)}
}

func (_c *MockRAGUsecase_Query_Call) Run(run func(_a0 context.Context, _a1 usecase.QueryRequest)) *MockRAGUsecase_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecase.QueryRequest))
	})
	return _c
}

func (_c *MockRAGUsecase_Query_Call) Return(_a0 *usecase.QueryResult, _a1 error) *MockRAGUsecase_Query_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRAGUsecase_Query_Call) RunAndReturn(run func(context.Context, usecase.QueryRequest) (*usecase.QueryResult, error)) *MockRAGUsecase_Query_Call {
	_c.Call.Return(run)
	return _c
}

// Ready provides a mock function with no fields
func (_m *MockRAGUsecase) Ready() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Ready")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockRAGUsecase_Ready_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ready'
type MockRAGUsecase_Ready_Call struct {
	*mock.Call
}

// Ready is a helper method to define mock.On call
func (_e *MockRAGUsecase_Expecter) Ready() *MockRAGUsecase_Ready_Call {
	return &MockRAGUsecase_Ready_Call{Call: _e.mock.On("Ready")}
}

func (_c *MockRAGUsecase_Ready_Call) Run(run func()) *MockRAGUsecase_Ready_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRAGUsecase_Ready_Call) Return(_a0 bool) *MockRAGUsecase_Ready_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRAGUsecase_Ready_Call) RunAndReturn(run func() bool) *MockRAGUsecase_Ready_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRAGUsecase creates a new instance of MockRAGUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRAGUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRAGUsecase {
	mock := &MockRAGUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
