// Code generated by grpcstubgen. DO NOT EDIT.

package grpc

import (
	pb "secure-rag-platform/services/rag/gen/v1"
)

type RAGServiceServerImpl struct {
	pb.UnimplementedRAGServiceServer
}

var _ pb.RAGServiceServer = (*RAGServiceServerImpl)(nil)
