// Code generated by mockery v2.53.5. DO NOT EDIT.

package usecase

import (
	context "context"
	model "secure-rag-platform/services/iam/internal/model"
	repository "secure-rag-platform/services/iam/internal/repository"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockIAMRepo is an autogenerated mock type for the IAMRepo type
type MockIAMRepo struct {
	mock.Mock
}

type MockIAMRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIAMRepo) EXPECT() *MockIAMRepo_Expecter {
	return &MockIAMRepo_Expecter{mock: &_m.Mock}
}

// AddUserRole provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *MockIAMRepo) AddUserRole(_a0 context.Context, _a1 string, _a2 string, _a3 *string) ([]*model.Role, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for AddUserRole")
	}

	var r0 []*model.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *string) ([]*model.Role, error)); ok {
		return rf(_a0, _a1, _a2, _a3)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *string) []*model.Role); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *string) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAMRepo_AddUserRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddUserRole'
type MockIAMRepo_AddUserRole_Call struct {
	*mock.Call
}

// AddUserRole is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
//   - _a2 string
//   - _a3 *string
func (_e *MockIAMRepo_Expecter) AddUserRole(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}) *MockIAMRepo_AddUserRole_Call {
	return &MockIAMRepo_AddUserRole_Call{Call: _e.mock.On("AddUserRole", _a0, _a1, _a2, _a3)}
}

func (_c *MockIAMRepo_AddUserRole_Call) Run(run func(_a0 context.Context, _a1 string, _a2 string, _a3 *string)) *MockIAMRepo_AddUserRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*string))
	})
	return _c
}

func (_c *MockIAMRepo_AddUserRole_Call) Return(_a0 []*model.Role, _a1 error) *MockIAMRepo_AddUserRole_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAMRepo_AddUserRole_Call) RunAndReturn(run func(context.Context, string, string, *string) ([]*model.Role, error)) *MockIAMRepo_AddUserRole_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSession provides a mock function with given fields: _a0, _a1
func (_m *MockIAMRepo) CreateSession(_a0 context.Context, _a1 repository.CreateSessionInput) (*model.UserSession, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 *model.UserSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.CreateSessionInput) (*model.UserSession, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.CreateSessionInput) *model.UserSession); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserSession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.CreateSessionInput) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAMRepo_CreateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSession'
type MockIAMRepo_CreateSession_Call struct {
	*mock.Call
}

// CreateSession is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 repository.CreateSessionInput
func (_e *MockIAMRepo_Expecter) CreateSession(_a0 interface{}, _a1 interface{}) *MockIAMRepo_CreateSession_Call {
	return &MockIAMRepo_CreateSession_Call{Call: _e.mock.On("CreateSession", _a0, _a1)}
}

func (_c *MockIAMRepo_CreateSession_Call) Run(run func(_a0 context.Context, _a1 repository.CreateSessionInput)) *MockIAMRepo_CreateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.CreateSessionInput))
	})
	return _c
}

func (_c *MockIAMRepo_CreateSession_Call) Return(_a0 *model.UserSession, _a1 error) *MockIAMRepo_CreateSession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAMRepo_CreateSession_Call) RunAndReturn(run func(context.Context, repository.CreateSessionInput) (*model.UserSession, error)) *MockIAMRepo_CreateSession_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function with given fields: _a0, _a1
func (_m *MockIAMRepo) CreateUser(_a0 context.Context, _a1 repository.CreateUserInput) (*model.User, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.CreateUserInput) (*model.User, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.CreateUserInput) *model.User); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.CreateUserInput) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAMRepo_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockIAMRepo_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 repository.CreateUserInput
func (_e *MockIAMRepo_Expecter) CreateUser(_a0 interface{}, _a1 interface{}) *MockIAMRepo_CreateUser_Call {
	return &MockIAMRepo_CreateUser_Call{Call: _e.mock.On("CreateUser", _a0, _a1)}
}

func (_c *MockIAMRepo_CreateUser_Call) Run(run func(_a0 context.Context, _a1 repository.CreateUserInput)) *MockIAMRepo_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.CreateUserInput))
	})
	return _c
}

func (_c *MockIAMRepo_CreateUser_Call) Return(_a0 *model.User, _a1 error) *MockIAMRepo_CreateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAMRepo_CreateUser_Call) RunAndReturn(run func(context.Context, repository.CreateUserInput) (*model.User, error)) *MockIAMRepo_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUserAttributeKey provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *MockIAMRepo) DeleteUserAttributeKey(_a0 context.Context, _a1 string, _a2 string, _a3 *string) (map[string]interface{}, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserAttributeKey")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *string) (map[string]interface{}, error)); ok {
		return rf(_a0, _a1, _a2, _a3)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *string) map[string]interface{}); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *string) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAMRepo_DeleteUserAttributeKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUserAttributeKey'
type MockIAMRepo_DeleteUserAttributeKey_Call struct {
	*mock.Call
}

// DeleteUserAttributeKey is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
//   - _a2 string
//   - _a3 *string
func (_e *MockIAMRepo_Expecter) DeleteUserAttributeKey(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}) *MockIAMRepo_DeleteUserAttributeKey_Call {
	return &MockIAMRepo_DeleteUserAttributeKey_Call{Call: _e.mock.On("DeleteUserAttributeKey", _a0, _a1, _a2, _a3)}
}

func (_c *MockIAMRepo_DeleteUserAttributeKey_Call) Run(run func(_a0 context.Context, _a1 string, _a2 string, _a3 *string)) *MockIAMRepo_DeleteUserAttributeKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*string))
	})
	return _c
}

func (_c *MockIAMRepo_DeleteUserAttributeKey_Call) Return(_a0 map[string]interface{}, _a1 error) *MockIAMRepo_DeleteUserAttributeKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAMRepo_DeleteUserAttributeKey_Call) RunAndReturn(run func(context.Context, string, string, *string) (map[string]interface{}, error)) *MockIAMRepo_DeleteUserAttributeKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetSessionByID provides a mock function with given fields: _a0, _a1
func (_m *MockIAMRepo) GetSessionByID(_a0 context.Context, _a1 string) (*model.UserSession, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetSessionByID")
	}

	var r0 *model.UserSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.UserSession, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.UserSession); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserSession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAMRepo_GetSessionByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSessionByID'
type MockIAMRepo_GetSessionByID_Call struct {
	*mock.Call
}

// GetSessionByID is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *MockIAMRepo_Expecter) GetSessionByID(_a0 interface{}, _a1 interface{}) *MockIAMRepo_GetSessionByID_Call {
	return &MockIAMRepo_GetSessionByID_Call{Call: _e.mock.On("GetSessionByID", _a0, _a1)}
}

func (_c *MockIAMRepo_GetSessionByID_Call) Run(run func(_a0 context.Context, _a1 string)) *MockIAMRepo_GetSessionByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIAMRepo_GetSessionByID_Call) Return(_a0 *model.UserSession, _a1 error) *MockIAMRepo_GetSessionByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAMRepo_GetSessionByID_Call) RunAndReturn(run func(context.Context, string) (*model.UserSession, error)) *MockIAMRepo_GetSessionByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetSessionByRefreshHash provides a mock function with given fields: _a0, _a1
func (_m *MockIAMRepo) GetSessionByRefreshHash(_a0 context.Context, _a1 string) (*model.UserSession, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetSessionByRefreshHash")
	}

	var r0 *model.UserSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.UserSession, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.UserSession); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserSession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAMRepo_GetSessionByRefreshHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSessionByRefreshHash'
type MockIAMRepo_GetSessionByRefreshHash_Call struct {
	*mock.Call
}

// GetSessionByRefreshHash is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *MockIAMRepo_Expecter) GetSessionByRefreshHash(_a0 interface{}, _a1 interface{}) *MockIAMRepo_GetSessionByRefreshHash_Call {
	return &MockIAMRepo_GetSessionByRefreshHash_Call{Call: _e.mock.On("GetSessionByRefreshHash", _a0, _a1)}
}

func (_c *MockIAMRepo_GetSessionByRefreshHash_Call) Run(run func(_a0 context.Context, _a1 string)) *MockIAMRepo_GetSessionByRefreshHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIAMRepo_GetSessionByRefreshHash_Call) Return(_a0 *model.UserSession, _a1 error) *MockIAMRepo_GetSessionByRefreshHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAMRepo_GetSessionByRefreshHash_Call) RunAndReturn(run func(context.Context, string) (*model.UserSession, error)) *MockIAMRepo_GetSessionByRefreshHash_Call {
	_c.Call.Return(run)
	return _c
}

// GetSubjectContext provides a mock function with given fields: _a0, _a1
func (_m *MockIAMRepo) GetSubjectContext(_a0 context.Context, _a1 string) (*model.SubjectContext, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetSubjectContext")
	}

	var r0 *model.SubjectContext
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.SubjectContext, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.SubjectContext); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.SubjectContext)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAMRepo_GetSubjectContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSubjectContext'
type MockIAMRepo_GetSubjectContext_Call struct {
	*mock.Call
}

// GetSubjectContext is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *MockIAMRepo_Expecter) GetSubjectContext(_a0 interface{}, _a1 interface{}) *MockIAMRepo_GetSubjectContext_Call {
	return &MockIAMRepo_GetSubjectContext_Call{Call: _e.mock.On("GetSubjectContext", _a0, _a1)}
}

func (_c *MockIAMRepo_GetSubjectContext_Call) Run(run func(_a0 context.Context, _a1 string)) *MockIAMRepo_GetSubjectContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIAMRepo_GetSubjectContext_Call) Return(_a0 *model.SubjectContext, _a1 error) *MockIAMRepo_GetSubjectContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAMRepo_GetSubjectContext_Call) RunAndReturn(run func(context.Context, string) (*model.SubjectContext, error)) *MockIAMRepo_GetSubjectContext_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserAttributes provides a mock function with given fields: _a0, _a1
func (_m *MockIAMRepo) GetUserAttributes(_a0 context.Context, _a1 string) (map[string]interface{}, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetUserAttributes")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (map[string]interface{}, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) map[string]interface{}); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAMRepo_GetUserAttributes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserAttributes'
type MockIAMRepo_GetUserAttributes_Call struct {
	*mock.Call
}

// GetUserAttributes is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *MockIAMRepo_Expecter) GetUserAttributes(_a0 interface{}, _a1 interface{}) *MockIAMRepo_GetUserAttributes_Call {
	return &MockIAMRepo_GetUserAttributes_Call{Call: _e.mock.On("GetUserAttributes", _a0, _a1)}
}

func (_c *MockIAMRepo_GetUserAttributes_Call) Run(run func(_a0 context.Context, _a1 string)) *MockIAMRepo_GetUserAttributes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIAMRepo_GetUserAttributes_Call) Return(_a0 map[string]interface{}, _a1 error) *MockIAMRepo_GetUserAttributes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAMRepo_GetUserAttributes_Call) RunAndReturn(run func(context.Context, string) (map[string]interface{}, error)) *MockIAMRepo_GetUserAttributes_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function with given fields: _a0, _a1
func (_m *MockIAMRepo) GetUserByID(_a0 context.Context, _a1 string) (*model.User, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.User, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.User); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAMRepo_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockIAMRepo_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *MockIAMRepo_Expecter) GetUserByID(_a0 interface{}, _a1 interface{}) *MockIAMRepo_GetUserByID_Call {
	return &MockIAMRepo_GetUserByID_Call{Call: _e.mock.On("GetUserByID", _a0, _a1)}
}

func (_c *MockIAMRepo_GetUserByID_Call) Run(run func(_a0 context.Context, _a1 string)) *MockIAMRepo_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIAMRepo_GetUserByID_Call) Return(_a0 *model.User, _a1 error) *MockIAMRepo_GetUserByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAMRepo_GetUserByID_Call) RunAndReturn(run func(context.Context, string) (*model.User, error)) *MockIAMRepo_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByLogin provides a mock function with given fields: _a0, _a1
func (_m *MockIAMRepo) GetUserByLogin(_a0 context.Context, _a1 string) (*model.User, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByLogin")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.User, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.User); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAMRepo_GetUserByLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByLogin'
type MockIAMRepo_GetUserByLogin_Call struct {
	*mock.Call
}

// GetUserByLogin is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *MockIAMRepo_Expecter) GetUserByLogin(_a0 interface{}, _a1 interface{}) *MockIAMRepo_GetUserByLogin_Call {
	return &MockIAMRepo_GetUserByLogin_Call{Call: _e.mock.On("GetUserByLogin", _a0, _a1)}
}

func (_c *MockIAMRepo_GetUserByLogin_Call) Run(run func(_a0 context.Context, _a1 string)) *MockIAMRepo_GetUserByLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIAMRepo_GetUserByLogin_Call) Return(_a0 *model.User, _a1 error) *MockIAMRepo_GetUserByLogin_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAMRepo_GetUserByLogin_Call) RunAndReturn(run func(context.Context, string) (*model.User, error)) *MockIAMRepo_GetUserByLogin_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserRoles provides a mock function with given fields: _a0, _a1
func (_m *MockIAMRepo) GetUserRoles(_a0 context.Context, _a1 string) ([]*model.Role, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetUserRoles")
	}

	var r0 []*model.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*model.Role, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*model.Role); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAMRepo_GetUserRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserRoles'
type MockIAMRepo_GetUserRoles_Call struct {
	*mock.Call
}

// GetUserRoles is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *MockIAMRepo_Expecter) GetUserRoles(_a0 interface{}, _a1 interface{}) *MockIAMRepo_GetUserRoles_Call {
	return &MockIAMRepo_GetUserRoles_Call{Call: _e.mock.On("GetUserRoles", _a0, _a1)}
}

func (_c *MockIAMRepo_GetUserRoles_Call) Run(run func(_a0 context.Context, _a1 string)) *MockIAMRepo_GetUserRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIAMRepo_GetUserRoles_Call) Return(_a0 []*model.Role, _a1 error) *MockIAMRepo_GetUserRoles_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAMRepo_GetUserRoles_Call) RunAndReturn(run func(context.Context, string) ([]*model.Role, error)) *MockIAMRepo_GetUserRoles_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserView provides a mock function with given fields: _a0, _a1
func (_m *MockIAMRepo) GetUserView(_a0 context.Context, _a1 string) (*model.UserView, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetUserView")
	}

	var r0 *model.UserView
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.UserView, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.UserView); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserView)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAMRepo_GetUserView_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserView'
type MockIAMRepo_GetUserView_Call struct {
	*mock.Call
}

// GetUserView is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *MockIAMRepo_Expecter) GetUserView(_a0 interface{}, _a1 interface{}) *MockIAMRepo_GetUserView_Call {
	return &MockIAMRepo_GetUserView_Call{Call: _e.mock.On("GetUserView", _a0, _a1)}
}

func (_c *MockIAMRepo_GetUserView_Call) Run(run func(_a0 context.Context, _a1 string)) *MockIAMRepo_GetUserView_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIAMRepo_GetUserView_Call) Return(_a0 *model.UserView, _a1 error) *MockIAMRepo_GetUserView_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAMRepo_GetUserView_Call) RunAndReturn(run func(context.Context, string) (*model.UserView, error)) *MockIAMRepo_GetUserView_Call {
	_c.Call.Return(run)
	return _c
}

// HasUserWithRole provides a mock function with given fields: _a0, _a1
func (_m *MockIAMRepo) HasUserWithRole(_a0 context.Context, _a1 string) (bool, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for HasUserWithRole")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAMRepo_HasUserWithRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasUserWithRole'
type MockIAMRepo_HasUserWithRole_Call struct {
	*mock.Call
}

// HasUserWithRole is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *MockIAMRepo_Expecter) HasUserWithRole(_a0 interface{}, _a1 interface{}) *MockIAMRepo_HasUserWithRole_Call {
	return &MockIAMRepo_HasUserWithRole_Call{Call: _e.mock.On("HasUserWithRole", _a0, _a1)}
}

func (_c *MockIAMRepo_HasUserWithRole_Call) Run(run func(_a0 context.Context, _a1 string)) *MockIAMRepo_HasUserWithRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIAMRepo_HasUserWithRole_Call) Return(_a0 bool, _a1 error) *MockIAMRepo_HasUserWithRole_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAMRepo_HasUserWithRole_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockIAMRepo_HasUserWithRole_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementContextVersion provides a mock function with given fields: _a0, _a1
func (_m *MockIAMRepo) IncrementContextVersion(_a0 context.Context, _a1 string) (int64, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for IncrementContextVersion")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAMRepo_IncrementContextVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementContextVersion'
type MockIAMRepo_IncrementContextVersion_Call struct {
	*mock.Call
}

// IncrementContextVersion is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *MockIAMRepo_Expecter) IncrementContextVersion(_a0 interface{}, _a1 interface{}) *MockIAMRepo_IncrementContextVersion_Call {
	return &MockIAMRepo_IncrementContextVersion_Call{Call: _e.mock.On("IncrementContextVersion", _a0, _a1)}
}

func (_c *MockIAMRepo_IncrementContextVersion_Call) Run(run func(_a0 context.Context, _a1 string)) *MockIAMRepo_IncrementContextVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIAMRepo_IncrementContextVersion_Call) Return(_a0 int64, _a1 error) *MockIAMRepo_IncrementContextVersion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAMRepo_IncrementContextVersion_Call) RunAndReturn(run func(context.Context, string) (int64, error)) *MockIAMRepo_IncrementContextVersion_Call {
	_c.Call.Return(run)
	return _c
}

// ListActiveUserSessions provides a mock function with given fields: _a0, _a1
func (_m *MockIAMRepo) ListActiveUserSessions(_a0 context.Context, _a1 string) ([]*model.UserSession, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ListActiveUserSessions")
	}

	var r0 []*model.UserSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*model.UserSession, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*model.UserSession); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.UserSession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAMRepo_ListActiveUserSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListActiveUserSessions'
type MockIAMRepo_ListActiveUserSessions_Call struct {
	*mock.Call
}

// ListActiveUserSessions is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *MockIAMRepo_Expecter) ListActiveUserSessions(_a0 interface{}, _a1 interface{}) *MockIAMRepo_ListActiveUserSessions_Call {
	return &MockIAMRepo_ListActiveUserSessions_Call{Call: _e.mock.On("ListActiveUserSessions", _a0, _a1)}
}

func (_c *MockIAMRepo_ListActiveUserSessions_Call) Run(run func(_a0 context.Context, _a1 string)) *MockIAMRepo_ListActiveUserSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIAMRepo_ListActiveUserSessions_Call) Return(_a0 []*model.UserSession, _a1 error) *MockIAMRepo_ListActiveUserSessions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAMRepo_ListActiveUserSessions_Call) RunAndReturn(run func(context.Context, string) ([]*model.UserSession, error)) *MockIAMRepo_ListActiveUserSessions_Call {
	_c.Call.Return(run)
	return _c
}

// ListRoles provides a mock function with given fields: _a0
func (_m *MockIAMRepo) ListRoles(_a0 context.Context) ([]*model.Role, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for ListRoles")
	}

	var r0 []*model.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*model.Role, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*model.Role); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAMRepo_ListRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRoles'
type MockIAMRepo_ListRoles_Call struct {
	*mock.Call
}

// ListRoles is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockIAMRepo_Expecter) ListRoles(_a0 interface{}) *MockIAMRepo_ListRoles_Call {
	return &MockIAMRepo_ListRoles_Call{Call: _e.mock.On("ListRoles", _a0)}
}

func (_c *MockIAMRepo_ListRoles_Call) Run(run func(_a0 context.Context)) *MockIAMRepo_ListRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIAMRepo_ListRoles_Call) Return(_a0 []*model.Role, _a1 error) *MockIAMRepo_ListRoles_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAMRepo_ListRoles_Call) RunAndReturn(run func(context.Context) ([]*model.Role, error)) *MockIAMRepo_ListRoles_Call {
	_c.Call.Return(run)
	return _c
}

// ListUserViews provides a mock function with given fields: _a0
func (_m *MockIAMRepo) ListUserViews(_a0 context.Context) ([]*model.UserView, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for ListUserViews")
	}

	var r0 []*model.UserView
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*model.UserView, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*model.UserView); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.UserView)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAMRepo_ListUserViews_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUserViews'
type MockIAMRepo_ListUserViews_Call struct {
	*mock.Call
}

// ListUserViews is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockIAMRepo_Expecter) ListUserViews(_a0 interface{}) *MockIAMRepo_ListUserViews_Call {
	return &MockIAMRepo_ListUserViews_Call{Call: _e.mock.On("ListUserViews", _a0)}
}

func (_c *MockIAMRepo_ListUserViews_Call) Run(run func(_a0 context.Context)) *MockIAMRepo_ListUserViews_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIAMRepo_ListUserViews_Call) Return(_a0 []*model.UserView, _a1 error) *MockIAMRepo_ListUserViews_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAMRepo_ListUserViews_Call) RunAndReturn(run func(context.Context) ([]*model.UserView, error)) *MockIAMRepo_ListUserViews_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveUserRole provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockIAMRepo) RemoveUserRole(_a0 context.Context, _a1 string, _a2 string) ([]*model.Role, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for RemoveUserRole")
	}

	var r0 []*model.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]*model.Role, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []*model.Role); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAMRepo_RemoveUserRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveUserRole'
type MockIAMRepo_RemoveUserRole_Call struct {
	*mock.Call
}

// RemoveUserRole is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
//   - _a2 string
func (_e *MockIAMRepo_Expecter) RemoveUserRole(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockIAMRepo_RemoveUserRole_Call {
	return &MockIAMRepo_RemoveUserRole_Call{Call: _e.mock.On("RemoveUserRole", _a0, _a1, _a2)}
}

func (_c *MockIAMRepo_RemoveUserRole_Call) Run(run func(_a0 context.Context, _a1 string, _a2 string)) *MockIAMRepo_RemoveUserRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockIAMRepo_RemoveUserRole_Call) Return(_a0 []*model.Role, _a1 error) *MockIAMRepo_RemoveUserRole_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAMRepo_RemoveUserRole_Call) RunAndReturn(run func(context.Context, string, string) ([]*model.Role, error)) *MockIAMRepo_RemoveUserRole_Call {
	_c.Call.Return(run)
	return _c
}

// ReplaceUserAttributes provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *MockIAMRepo) ReplaceUserAttributes(_a0 context.Context, _a1 string, _a2 map[string]interface{}, _a3 *string) (map[string]interface{}, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for ReplaceUserAttributes")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}, *string) (map[string]interface{}, error)); ok {
		return rf(_a0, _a1, _a2, _a3)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}, *string) map[string]interface{}); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, map[string]interface{}, *string) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAMRepo_ReplaceUserAttributes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplaceUserAttributes'
type MockIAMRepo_ReplaceUserAttributes_Call struct {
	*mock.Call
}

// ReplaceUserAttributes is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
//   - _a2 map[string]interface{}
//   - _a3 *string
func (_e *MockIAMRepo_Expecter) ReplaceUserAttributes(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}) *MockIAMRepo_ReplaceUserAttributes_Call {
	return &MockIAMRepo_ReplaceUserAttributes_Call{Call: _e.mock.On("ReplaceUserAttributes", _a0, _a1, _a2, _a3)}
}

func (_c *MockIAMRepo_ReplaceUserAttributes_Call) Run(run func(_a0 context.Context, _a1 string, _a2 map[string]interface{}, _a3 *string)) *MockIAMRepo_ReplaceUserAttributes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(map[string]interface{}), args[3].(*string))
	})
	return _c
}

func (_c *MockIAMRepo_ReplaceUserAttributes_Call) Return(_a0 map[string]interface{}, _a1 error) *MockIAMRepo_ReplaceUserAttributes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAMRepo_ReplaceUserAttributes_Call) RunAndReturn(run func(context.Context, string, map[string]interface{}, *string) (map[string]interface{}, error)) *MockIAMRepo_ReplaceUserAttributes_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAllUserSessions provides a mock function with given fields: _a0, _a1
func (_m *MockIAMRepo) RevokeAllUserSessions(_a0 context.Context, _a1 string) (int64, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllUserSessions")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAMRepo_RevokeAllUserSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAllUserSessions'
type MockIAMRepo_RevokeAllUserSessions_Call struct {
	*mock.Call
}

// RevokeAllUserSessions is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *MockIAMRepo_Expecter) RevokeAllUserSessions(_a0 interface{}, _a1 interface{}) *MockIAMRepo_RevokeAllUserSessions_Call {
	return &MockIAMRepo_RevokeAllUserSessions_Call{Call: _e.mock.On("RevokeAllUserSessions", _a0, _a1)}
}

func (_c *MockIAMRepo_RevokeAllUserSessions_Call) Run(run func(_a0 context.Context, _a1 string)) *MockIAMRepo_RevokeAllUserSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIAMRepo_RevokeAllUserSessions_Call) Return(_a0 int64, _a1 error) *MockIAMRepo_RevokeAllUserSessions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAMRepo_RevokeAllUserSessions_Call) RunAndReturn(run func(context.Context, string) (int64, error)) *MockIAMRepo_RevokeAllUserSessions_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeSession provides a mock function with given fields: _a0, _a1
func (_m *MockIAMRepo) RevokeSession(_a0 context.Context, _a1 string) (bool, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for RevokeSession")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAMRepo_RevokeSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeSession'
type MockIAMRepo_RevokeSession_Call struct {
	*mock.Call
}

// RevokeSession is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *MockIAMRepo_Expecter) RevokeSession(_a0 interface{}, _a1 interface{}) *MockIAMRepo_RevokeSession_Call {
	return &MockIAMRepo_RevokeSession_Call{Call: _e.mock.On("RevokeSession", _a0, _a1)}
}

func (_c *MockIAMRepo_RevokeSession_Call) Run(run func(_a0 context.Context, _a1 string)) *MockIAMRepo_RevokeSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIAMRepo_RevokeSession_Call) Return(_a0 bool, _a1 error) *MockIAMRepo_RevokeSession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAMRepo_RevokeSession_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockIAMRepo_RevokeSession_Call {
	_c.Call.Return(run)
	return _c
}

// RotateSessionRefreshHash provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *MockIAMRepo) RotateSessionRefreshHash(_a0 context.Context, _a1 string, _a2 string, _a3 time.Time) (*model.UserSession, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for RotateSessionRefreshHash")
	}

	var r0 *model.UserSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time) (*model.UserSession, error)); ok {
		return rf(_a0, _a1, _a2, _a3)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time) *model.UserSession); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserSession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, time.Time) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAMRepo_RotateSessionRefreshHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RotateSessionRefreshHash'
type MockIAMRepo_RotateSessionRefreshHash_Call struct {
	*mock.Call
}

// RotateSessionRefreshHash is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
//   - _a2 string
//   - _a3 time.Time
func (_e *MockIAMRepo_Expecter) RotateSessionRefreshHash(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}) *MockIAMRepo_RotateSessionRefreshHash_Call {
	return &MockIAMRepo_RotateSessionRefreshHash_Call{Call: _e.mock.On("RotateSessionRefreshHash", _a0, _a1, _a2, _a3)}
}

func (_c *MockIAMRepo_RotateSessionRefreshHash_Call) Run(run func(_a0 context.Context, _a1 string, _a2 string, _a3 time.Time)) *MockIAMRepo_RotateSessionRefreshHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(time.Time))
	})
	return _c
}

func (_c *MockIAMRepo_RotateSessionRefreshHash_Call) Return(_a0 *model.UserSession, _a1 error) *MockIAMRepo_RotateSessionRefreshHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAMRepo_RotateSessionRefreshHash_Call) RunAndReturn(run func(context.Context, string, string, time.Time) (*model.UserSession, error)) *MockIAMRepo_RotateSessionRefreshHash_Call {
	_c.Call.Return(run)
	return _c
}

// SetUserRoles provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *MockIAMRepo) SetUserRoles(_a0 context.Context, _a1 string, _a2 []string, _a3 *string) ([]*model.Role, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for SetUserRoles")
	}

	var r0 []*model.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string, *string) ([]*model.Role, error)); ok {
		return rf(_a0, _a1, _a2, _a3)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []string, *string) []*model.Role); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []string, *string) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAMRepo_SetUserRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetUserRoles'
type MockIAMRepo_SetUserRoles_Call struct {
	*mock.Call
}

// SetUserRoles is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
//   - _a2 []string
//   - _a3 *string
func (_e *MockIAMRepo_Expecter) SetUserRoles(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}) *MockIAMRepo_SetUserRoles_Call {
	return &MockIAMRepo_SetUserRoles_Call{Call: _e.mock.On("SetUserRoles", _a0, _a1, _a2, _a3)}
}

func (_c *MockIAMRepo_SetUserRoles_Call) Run(run func(_a0 context.Context, _a1 string, _a2 []string, _a3 *string)) *MockIAMRepo_SetUserRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]string), args[3].(*string))
	})
	return _c
}

func (_c *MockIAMRepo_SetUserRoles_Call) Return(_a0 []*model.Role, _a1 error) *MockIAMRepo_SetUserRoles_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAMRepo_SetUserRoles_Call) RunAndReturn(run func(context.Context, string, []string, *string) ([]*model.Role, error)) *MockIAMRepo_SetUserRoles_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function with given fields: _a0, _a1
func (_m *MockIAMRepo) UpdateUser(_a0 context.Context, _a1 repository.UpdateUserInput) (*model.User, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.UpdateUserInput) (*model.User, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.UpdateUserInput) *model.User); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.UpdateUserInput) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAMRepo_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type MockIAMRepo_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 repository.UpdateUserInput
func (_e *MockIAMRepo_Expecter) UpdateUser(_a0 interface{}, _a1 interface{}) *MockIAMRepo_UpdateUser_Call {
	return &MockIAMRepo_UpdateUser_Call{Call: _e.mock.On("UpdateUser", _a0, _a1)}
}

func (_c *MockIAMRepo_UpdateUser_Call) Run(run func(_a0 context.Context, _a1 repository.UpdateUserInput)) *MockIAMRepo_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.UpdateUserInput))
	})
	return _c
}

func (_c *MockIAMRepo_UpdateUser_Call) Return(_a0 *model.User, _a1 error) *MockIAMRepo_UpdateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAMRepo_UpdateUser_Call) RunAndReturn(run func(context.Context, repository.UpdateUserInput) (*model.User, error)) *MockIAMRepo_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIAMRepo creates a new instance of MockIAMRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIAMRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIAMRepo {
	mock := &MockIAMRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
