services:
  iam:
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=secure-rag-platform_traefik-net"
      - "traefik.http.routers.iam.rule=PathPrefix(`/iam`)"
      - "traefik.http.routers.iam.entrypoints=web"
      - "traefik.http.routers.iam.priority=100"
      - "traefik.http.services.iam.loadbalancer.server.port=8081"
    networks:
      - traefik-net
      - app-net
      - iam-net
      - iam-db-net
      - iam-redis-net

  knowledge:
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=secure-rag-platform_traefik-net"
      - "traefik.http.routers.knowledge.rule=PathPrefix(`/knowledge`)"
      - "traefik.http.routers.knowledge.entrypoints=web"
      - "traefik.http.routers.knowledge.priority=100"
      - "traefik.http.services.knowledge.loadbalancer.server.port=8082"
    networks:
      - traefik-net
      - app-net
      - knowledge-net
      - knowledge-db-net
      - knowledge-minio-net

  rag:
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=secure-rag-platform_traefik-net"
      - "traefik.http.routers.rag.rule=PathPrefix(`/rag`)"
      - "traefik.http.routers.rag.entrypoints=web"
      - "traefik.http.routers.rag.priority=100"
      - "traefik.http.services.rag.loadbalancer.server.port=8083"
    networks:
      - traefik-net
      - app-net
      - rag-net
      - rag-db-net
      - rag-s3-net

  ai-inference:
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=secure-rag-platform_traefik-net"
      - "traefik.http.routers.aiinference.rule=PathPrefix(`/ai-inference`)"
      - "traefik.http.routers.aiinference.entrypoints=web"
      - "traefik.http.routers.aiinference.priority=100"
      - "traefik.http.services.aiinference.loadbalancer.server.port=8084"
    networks:
      - traefik-net
      - app-net
      - egress-net
      - ai-inference-net
      - ai-inference-egress-net
