// Code generated by grpcstubgen. DO NOT EDIT.

package grpc

import (
	pb "secure-rag-platform/services/gateway/gen/v1"
)

type GatewayServiceServerImpl struct {
	pb.UnimplementedGatewayServiceServer
}

var _ pb.GatewayServiceServer = (*GatewayServiceServerImpl)(nil)
