// Code generated by grpcstubgen. DO NOT EDIT.

package grpc

import (
	pb "example.com/project/gateway/gen/v1"
)

type GatewayServiceServerImpl struct {
	pb.UnimplementedGatewayServiceServer
}

var _ pb.GatewayServiceServer = (*GatewayServiceServerImpl)(nil)
