// Code generated by grpcstubgen. DO NOT EDIT.

package grpc

import (
	"context"
	pb "example.com/project/gateway/gen/v1"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

func (s *GatewayServiceServerImpl) Health(ctx context.Context, req *pb.HealthRequest) (*pb.HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
