// Code generated by mockery v2.53.5. DO NOT EDIT.

package usecase

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// MockDocumentStorage is an autogenerated mock type for the DocumentStorage type
type MockDocumentStorage struct {
	mock.Mock
}

type MockDocumentStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDocumentStorage) EXPECT() *MockDocumentStorage_Expecter {
	return &MockDocumentStorage_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: _a0, _a1
func (_m *MockDocumentStorage) Delete(_a0 context.Context, _a1 string) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDocumentStorage_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockDocumentStorage_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *MockDocumentStorage_Expecter) Delete(_a0 interface{}, _a1 interface{}) *MockDocumentStorage_Delete_Call {
	return &MockDocumentStorage_Delete_Call{Call: _e.mock.On("Delete", _a0, _a1)}
}

func (_c *MockDocumentStorage_Delete_Call) Run(run func(_a0 context.Context, _a1 string)) *MockDocumentStorage_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDocumentStorage_Delete_Call) Return(_a0 error) *MockDocumentStorage_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDocumentStorage_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockDocumentStorage_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Download provides a mock function with given fields: _a0, _a1
func (_m *MockDocumentStorage) Download(_a0 context.Context, _a1 string) (io.ReadCloser, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Download")
	}

	var r0 io.ReadCloser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (io.ReadCloser, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) io.ReadCloser); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDocumentStorage_Download_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Download'
type MockDocumentStorage_Download_Call struct {
	*mock.Call
}

// Download is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *MockDocumentStorage_Expecter) Download(_a0 interface{}, _a1 interface{}) *MockDocumentStorage_Download_Call {
	return &MockDocumentStorage_Download_Call{Call: _e.mock.On("Download", _a0, _a1)}
}

func (_c *MockDocumentStorage_Download_Call) Run(run func(_a0 context.Context, _a1 string)) *MockDocumentStorage_Download_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDocumentStorage_Download_Call) Return(_a0 io.ReadCloser, _a1 error) *MockDocumentStorage_Download_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDocumentStorage_Download_Call) RunAndReturn(run func(context.Context, string) (io.ReadCloser, error)) *MockDocumentStorage_Download_Call {
	_c.Call.Return(run)
	return _c
}

// Upload provides a mock function with given fields: _a0, _a1, _a2, _a3, _a4
func (_m *MockDocumentStorage) Upload(_a0 context.Context, _a1 string, _a2 io.Reader, _a3 int64, _a4 string) error {
	ret := _m.Called(_a0, _a1, _a2, _a3, _a4)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader, int64, string) error); ok {
		r0 = rf(_a0, _a1, _a2, _a3, _a4)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDocumentStorage_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type MockDocumentStorage_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
//   - _a2 io.Reader
//   - _a3 int64
//   - _a4 string
func (_e *MockDocumentStorage_Expecter) Upload(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}, _a4 interface{}) *MockDocumentStorage_Upload_Call {
	return &MockDocumentStorage_Upload_Call{Call: _e.mock.On("Upload", _a0, _a1, _a2, _a3, _a4)}
}

func (_c *MockDocumentStorage_Upload_Call) Run(run func(_a0 context.Context, _a1 string, _a2 io.Reader, _a3 int64, _a4 string)) *MockDocumentStorage_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(io.Reader), args[3].(int64), args[4].(string))
	})
	return _c
}

func (_c *MockDocumentStorage_Upload_Call) Return(_a0 error) *MockDocumentStorage_Upload_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDocumentStorage_Upload_Call) RunAndReturn(run func(context.Context, string, io.Reader, int64, string) error) *MockDocumentStorage_Upload_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDocumentStorage creates a new instance of MockDocumentStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDocumentStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDocumentStorage {
	mock := &MockDocumentStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
