// Code generated by mockery v2.53.5. DO NOT EDIT.

package usecase

import (
	context "context"
	model "secure-rag-platform/services/knowledge/internal/model"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockDocumentRepo is an autogenerated mock type for the DocumentRepo type
type MockDocumentRepo struct {
	mock.Mock
}

type MockDocumentRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDocumentRepo) EXPECT() *MockDocumentRepo_Expecter {
	return &MockDocumentRepo_Expecter{mock: &_m.Mock}
}

// CreateDocument provides a mock function with given fields: _a0, _a1
func (_m *MockDocumentRepo) CreateDocument(_a0 context.Context, _a1 *model.Document) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateDocument")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Document) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDocumentRepo_CreateDocument_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDocument'
type MockDocumentRepo_CreateDocument_Call struct {
	*mock.Call
}

// CreateDocument is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *model.Document
func (_e *MockDocumentRepo_Expecter) CreateDocument(_a0 interface{}, _a1 interface{}) *MockDocumentRepo_CreateDocument_Call {
	return &MockDocumentRepo_CreateDocument_Call{Call: _e.mock.On("CreateDocument", _a0, _a1)}
}

func (_c *MockDocumentRepo_CreateDocument_Call) Run(run func(_a0 context.Context, _a1 *model.Document)) *MockDocumentRepo_CreateDocument_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Document))
	})
	return _c
}

func (_c *MockDocumentRepo_CreateDocument_Call) Return(_a0 error) *MockDocumentRepo_CreateDocument_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDocumentRepo_CreateDocument_Call) RunAndReturn(run func(context.Context, *model.Document) error) *MockDocumentRepo_CreateDocument_Call {
	_c.Call.Return(run)
	return _c
}

// GetDocumentByUUID provides a mock function with given fields: _a0, _a1
func (_m *MockDocumentRepo) GetDocumentByUUID(_a0 context.Context, _a1 string) (*model.Document, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetDocumentByUUID")
	}

	var r0 *model.Document
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Document, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Document); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Document)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDocumentRepo_GetDocumentByUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDocumentByUUID'
type MockDocumentRepo_GetDocumentByUUID_Call struct {
	*mock.Call
}

// GetDocumentByUUID is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *MockDocumentRepo_Expecter) GetDocumentByUUID(_a0 interface{}, _a1 interface{}) *MockDocumentRepo_GetDocumentByUUID_Call {
	return &MockDocumentRepo_GetDocumentByUUID_Call{Call: _e.mock.On("GetDocumentByUUID", _a0, _a1)}
}

func (_c *MockDocumentRepo_GetDocumentByUUID_Call) Run(run func(_a0 context.Context, _a1 string)) *MockDocumentRepo_GetDocumentByUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDocumentRepo_GetDocumentByUUID_Call) Return(_a0 *model.Document, _a1 error) *MockDocumentRepo_GetDocumentByUUID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDocumentRepo_GetDocumentByUUID_Call) RunAndReturn(run func(context.Context, string) (*model.Document, error)) *MockDocumentRepo_GetDocumentByUUID_Call {
	_c.Call.Return(run)
	return _c
}

// ListActiveDocuments provides a mock function with given fields: _a0
func (_m *MockDocumentRepo) ListActiveDocuments(_a0 context.Context) ([]*model.Document, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for ListActiveDocuments")
	}

	var r0 []*model.Document
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*model.Document, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*model.Document); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Document)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDocumentRepo_ListActiveDocuments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListActiveDocuments'
type MockDocumentRepo_ListActiveDocuments_Call struct {
	*mock.Call
}

// ListActiveDocuments is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockDocumentRepo_Expecter) ListActiveDocuments(_a0 interface{}) *MockDocumentRepo_ListActiveDocuments_Call {
	return &MockDocumentRepo_ListActiveDocuments_Call{Call: _e.mock.On("ListActiveDocuments", _a0)}
}

func (_c *MockDocumentRepo_ListActiveDocuments_Call) Run(run func(_a0 context.Context)) *MockDocumentRepo_ListActiveDocuments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDocumentRepo_ListActiveDocuments_Call) Return(_a0 []*model.Document, _a1 error) *MockDocumentRepo_ListActiveDocuments_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDocumentRepo_ListActiveDocuments_Call) RunAndReturn(run func(context.Context) ([]*model.Document, error)) *MockDocumentRepo_ListActiveDocuments_Call {
	_c.Call.Return(run)
	return _c
}

// RestoreDocument provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockDocumentRepo) RestoreDocument(_a0 context.Context, _a1 string, _a2 time.Time) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for RestoreDocument")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDocumentRepo_RestoreDocument_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestoreDocument'
type MockDocumentRepo_RestoreDocument_Call struct {
	*mock.Call
}

// RestoreDocument is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
//   - _a2 time.Time
func (_e *MockDocumentRepo_Expecter) RestoreDocument(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockDocumentRepo_RestoreDocument_Call {
	return &MockDocumentRepo_RestoreDocument_Call{Call: _e.mock.On("RestoreDocument", _a0, _a1, _a2)}
}

func (_c *MockDocumentRepo_RestoreDocument_Call) Run(run func(_a0 context.Context, _a1 string, _a2 time.Time)) *MockDocumentRepo_RestoreDocument_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time))
	})
	return _c
}

func (_c *MockDocumentRepo_RestoreDocument_Call) Return(_a0 error) *MockDocumentRepo_RestoreDocument_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDocumentRepo_RestoreDocument_Call) RunAndReturn(run func(context.Context, string, time.Time) error) *MockDocumentRepo_RestoreDocument_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDeleteDocument provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockDocumentRepo) SoftDeleteDocument(_a0 context.Context, _a1 string, _a2 time.Time) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for SoftDeleteDocument")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDocumentRepo_SoftDeleteDocument_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDeleteDocument'
type MockDocumentRepo_SoftDeleteDocument_Call struct {
	*mock.Call
}

// SoftDeleteDocument is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
//   - _a2 time.Time
func (_e *MockDocumentRepo_Expecter) SoftDeleteDocument(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockDocumentRepo_SoftDeleteDocument_Call {
	return &MockDocumentRepo_SoftDeleteDocument_Call{Call: _e.mock.On("SoftDeleteDocument", _a0, _a1, _a2)}
}

func (_c *MockDocumentRepo_SoftDeleteDocument_Call) Run(run func(_a0 context.Context, _a1 string, _a2 time.Time)) *MockDocumentRepo_SoftDeleteDocument_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time))
	})
	return _c
}

func (_c *MockDocumentRepo_SoftDeleteDocument_Call) Return(_a0 error) *MockDocumentRepo_SoftDeleteDocument_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDocumentRepo_SoftDeleteDocument_Call) RunAndReturn(run func(context.Context, string, time.Time) error) *MockDocumentRepo_SoftDeleteDocument_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAttributes provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *MockDocumentRepo) UpdateAttributes(_a0 context.Context, _a1 string, _a2 map[string]interface{}, _a3 time.Time) error {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAttributes")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}, time.Time) error); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDocumentRepo_UpdateAttributes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAttributes'
type MockDocumentRepo_UpdateAttributes_Call struct {
	*mock.Call
}

// UpdateAttributes is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
//   - _a2 map[string]interface{}
//   - _a3 time.Time
func (_e *MockDocumentRepo_Expecter) UpdateAttributes(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}) *MockDocumentRepo_UpdateAttributes_Call {
	return &MockDocumentRepo_UpdateAttributes_Call{Call: _e.mock.On("UpdateAttributes", _a0, _a1, _a2, _a3)}
}

func (_c *MockDocumentRepo_UpdateAttributes_Call) Run(run func(_a0 context.Context, _a1 string, _a2 map[string]interface{}, _a3 time.Time)) *MockDocumentRepo_UpdateAttributes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(map[string]interface{}), args[3].(time.Time))
	})
	return _c
}

func (_c *MockDocumentRepo_UpdateAttributes_Call) Return(_a0 error) *MockDocumentRepo_UpdateAttributes_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDocumentRepo_UpdateAttributes_Call) RunAndReturn(run func(context.Context, string, map[string]interface{}, time.Time) error) *MockDocumentRepo_UpdateAttributes_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDocument provides a mock function with given fields: _a0, _a1, _a2, _a3, _a4
func (_m *MockDocumentRepo) UpdateDocument(_a0 context.Context, _a1 string, _a2 *string, _a3 *string, _a4 time.Time) error {
	ret := _m.Called(_a0, _a1, _a2, _a3, _a4)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDocument")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *string, *string, time.Time) error); ok {
		r0 = rf(_a0, _a1, _a2, _a3, _a4)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDocumentRepo_UpdateDocument_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDocument'
type MockDocumentRepo_UpdateDocument_Call struct {
	*mock.Call
}

// UpdateDocument is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
//   - _a2 *string
//   - _a3 *string
//   - _a4 time.Time
func (_e *MockDocumentRepo_Expecter) UpdateDocument(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}, _a4 interface{}) *MockDocumentRepo_UpdateDocument_Call {
	return &MockDocumentRepo_UpdateDocument_Call{Call: _e.mock.On("UpdateDocument", _a0, _a1, _a2, _a3, _a4)}
}

func (_c *MockDocumentRepo_UpdateDocument_Call) Run(run func(_a0 context.Context, _a1 string, _a2 *string, _a3 *string, _a4 time.Time)) *MockDocumentRepo_UpdateDocument_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*string), args[3].(*string), args[4].(time.Time))
	})
	return _c
}

func (_c *MockDocumentRepo_UpdateDocument_Call) Return(_a0 error) *MockDocumentRepo_UpdateDocument_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDocumentRepo_UpdateDocument_Call) RunAndReturn(run func(context.Context, string, *string, *string, time.Time) error) *MockDocumentRepo_UpdateDocument_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateIndexStatus provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockDocumentRepo) UpdateIndexStatus(_a0 context.Context, _a1 int64, _a2 string) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for UpdateIndexStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDocumentRepo_UpdateIndexStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateIndexStatus'
type MockDocumentRepo_UpdateIndexStatus_Call struct {
	*mock.Call
}

// UpdateIndexStatus is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 int64
//   - _a2 string
func (_e *MockDocumentRepo_Expecter) UpdateIndexStatus(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockDocumentRepo_UpdateIndexStatus_Call {
	return &MockDocumentRepo_UpdateIndexStatus_Call{Call: _e.mock.On("UpdateIndexStatus", _a0, _a1, _a2)}
}

func (_c *MockDocumentRepo_UpdateIndexStatus_Call) Run(run func(_a0 context.Context, _a1 int64, _a2 string)) *MockDocumentRepo_UpdateIndexStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string))
	})
	return _c
}

func (_c *MockDocumentRepo_UpdateIndexStatus_Call) Return(_a0 error) *MockDocumentRepo_UpdateIndexStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDocumentRepo_UpdateIndexStatus_Call) RunAndReturn(run func(context.Context, int64, string) error) *MockDocumentRepo_UpdateIndexStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDocumentRepo creates a new instance of MockDocumentRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDocumentRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDocumentRepo {
	mock := &MockDocumentRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
