// Code generated by grpcstubgen. DO NOT EDIT.

package grpc

import (
	pb "secure-rag-platform/services/ai-inference/gen/v1"
	"secure-rag-platform/services/ai-inference/internal/usecase"
)

type AIInferenceServiceServerImpl struct {
	pb.UnimplementedAIInferenceServiceServer
	svc *usecase.Service
}

func NewAIInferenceServiceServer(svc *usecase.Service) *AIInferenceServiceServerImpl {
	return &AIInferenceServiceServerImpl{svc: svc}
}

var _ pb.AIInferenceServiceServer = (*AIInferenceServiceServerImpl)(nil)
