// Code generated by grpcstubgen. DO NOT EDIT.

package grpc

import (
	pb "secure-rag-platform/services/ai-inference/gen/v1"
)

type AIInferenceServiceServerImpl struct {
	pb.UnimplementedAIInferenceServiceServer
}

func NewAIInferenceServiceServer() *AIInferenceServiceServerImpl {
	return &AIInferenceServiceServerImpl{}
}

var _ pb.AIInferenceServiceServer = (*AIInferenceServiceServerImpl)(nil)
