// Code generated by grpcstubgen. DO NOT EDIT.

package grpc

import (
	"context"
	pb "secure-rag-platform/services/ai-inference/gen/v1"
	"secure-rag-platform/services/ai-inference/internal/usecase"
)

func (s *EmbeddingServiceServerImpl) BatchEmbed(ctx context.Context, req *pb.BatchEmbedRequest) (*pb.BatchEmbedResponse, error) {
	input := usecase.BatchEmbedRequest{
		RequestID:  req.GetRequestId(),
		ModelAlias: req.GetModelAlias(),
		Texts:      req.GetTexts(),
		InputType:  embeddingInputTypeFromProto(req.GetInputType()),
		Normalize:  req.GetNormalize(),
	}

	result, err := s.svc.Embed(ctx, input)
	if err != nil {
		return nil, toGRPCError(err)
	}

	vectors := make([]*pb.EmbeddingVector, 0, len(result.Vectors))
	for _, vector := range result.Vectors {
		vectors = append(vectors, &pb.EmbeddingVector{Values: vector})
	}

	return &pb.BatchEmbedResponse{
		Vectors:          vectors,
		Dimension:        result.Dimension,
		ResolvedProvider: result.ResolvedProvider,
		ResolvedModel:    result.ResolvedModel,
	}, nil
}
