// Code generated by grpcstubgen. DO NOT EDIT.

package grpc

import (
	"context"
	pb "secure-rag-platform/services/ai-inference/gen/v1"
	"secure-rag-platform/services/ai-inference/internal/usecase"
)

func (s *EmbeddingServiceServerImpl) Embed(ctx context.Context, req *pb.EmbedRequest) (*pb.EmbedResponse, error) {
	input := usecase.BatchEmbedRequest{
		RequestID:  req.GetRequestId(),
		ModelAlias: req.GetModelAlias(),
		Texts:      []string{req.GetText()},
		InputType:  embeddingInputTypeFromProto(req.GetInputType()),
		Normalize:  req.GetNormalize(),
	}

	result, err := s.svc.Embed(ctx, input)
	if err != nil {
		return nil, toGRPCError(err)
	}
	if len(result.Vectors) == 0 {
		return nil, toGRPCError(usecase.ErrProviderFailed)
	}

	return &pb.EmbedResponse{
		Vector:           result.Vectors[0],
		Dimension:        result.Dimension,
		ResolvedProvider: result.ResolvedProvider,
		ResolvedModel:    result.ResolvedModel,
	}, nil
}
