// Code generated by grpcstubgen. DO NOT EDIT.

package grpc

import (
	"context"
	pb "secure-rag-platform/api/gen/go/aiinference/v1"
	"secure-rag-platform/services/ai-inference/internal/usecase"
)

func (s *GenerationServiceServerImpl) Generate(ctx context.Context, req *pb.GenerateRequest) (*pb.GenerateResponse, error) {
	input := usecase.GenerateRequest{
		RequestID:  req.GetRequestId(),
		ModelAlias: req.GetModelAlias(),
		Messages:   make([]usecase.Message, 0, len(req.GetMessages())),
		Params:     generationParamsFromProto(req.GetParams()),
	}

	for _, message := range req.GetMessages() {
		input.Messages = append(input.Messages, usecase.Message{
			Role:    message.GetRole(),
			Content: message.GetContent(),
		})
	}

	result, err := s.svc.Generate(ctx, input)
	if err != nil {
		return nil, toGRPCError(err)
	}

	return &pb.GenerateResponse{
		Content:      result.Content,
		FinishReason: result.FinishReason,
		Usage: &pb.Usage{
			PromptTokens:     result.Usage.PromptTokens,
			CompletionTokens: result.Usage.CompletionTokens,
			TotalTokens:      result.Usage.TotalTokens,
		},
		ResolvedProvider: result.ResolvedProvider,
		ResolvedModel:    result.ResolvedModel,
	}, nil
}
