// Code generated by grpcstubgen. DO NOT EDIT.

package grpc

import (
	"context"
	pb "secure-rag-platform/api/gen/go/aiinference/v1"
)

func (s *GenerationServiceServerImpl) ListModels(ctx context.Context, req *pb.ListModelsRequest) (*pb.ListModelsResponse, error) {
	filterTask, err := taskTypeFromProto(req.GetTaskType())
	if err != nil {
		return nil, toGRPCError(err)
	}

	models := s.svc.ListModels(filterTask)
	response := &pb.ListModelsResponse{
		Models: make([]*pb.ModelAliasInfo, 0, len(models)),
	}

	for _, model := range models {
		response.Models = append(response.Models, &pb.ModelAliasInfo{
			Alias:    model.Alias,
			TaskType: taskTypeToProto(model.Task),
			Provider: model.Provider,
			Model:    model.Model,
			BaseUrl:  model.BaseURL,
		})
	}

	return response, nil
}
