// Code generated by mockery v2.53.5. DO NOT EDIT.

package usecase

import (
	context "context"
	iamv1 "secure-rag-platform/api/gen/go/iam/v1"

	mock "github.com/stretchr/testify/mock"
	grpc "google.golang.org/grpc"
)

// MockAttributeServiceClient is an autogenerated mock type for the AttributeServiceClient type
type MockAttributeServiceClient struct {
	mock.Mock
}

type MockAttributeServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAttributeServiceClient) EXPECT() *MockAttributeServiceClient_Expecter {
	return &MockAttributeServiceClient_Expecter{mock: &_m.Mock}
}

// DeleteUserAttributeKey provides a mock function with given fields: ctx, in, opts
func (_m *MockAttributeServiceClient) DeleteUserAttributeKey(ctx context.Context, in *iamv1.DeleteUserAttributeKeyRequest, opts ...grpc.CallOption) (*iamv1.DeleteUserAttributeKeyResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserAttributeKey")
	}

	var r0 *iamv1.DeleteUserAttributeKeyResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *iamv1.DeleteUserAttributeKeyRequest, ...grpc.CallOption) (*iamv1.DeleteUserAttributeKeyResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *iamv1.DeleteUserAttributeKeyRequest, ...grpc.CallOption) *iamv1.DeleteUserAttributeKeyResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*iamv1.DeleteUserAttributeKeyResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *iamv1.DeleteUserAttributeKeyRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAttributeServiceClient_DeleteUserAttributeKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUserAttributeKey'
type MockAttributeServiceClient_DeleteUserAttributeKey_Call struct {
	*mock.Call
}

// DeleteUserAttributeKey is a helper method to define mock.On call
//   - ctx context.Context
//   - in *iamv1.DeleteUserAttributeKeyRequest
//   - opts ...grpc.CallOption
func (_e *MockAttributeServiceClient_Expecter) DeleteUserAttributeKey(ctx interface{}, in interface{}, opts ...interface{}) *MockAttributeServiceClient_DeleteUserAttributeKey_Call {
	return &MockAttributeServiceClient_DeleteUserAttributeKey_Call{Call: _e.mock.On("DeleteUserAttributeKey",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockAttributeServiceClient_DeleteUserAttributeKey_Call) Run(run func(ctx context.Context, in *iamv1.DeleteUserAttributeKeyRequest, opts ...grpc.CallOption)) *MockAttributeServiceClient_DeleteUserAttributeKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*iamv1.DeleteUserAttributeKeyRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockAttributeServiceClient_DeleteUserAttributeKey_Call) Return(_a0 *iamv1.DeleteUserAttributeKeyResponse, _a1 error) *MockAttributeServiceClient_DeleteUserAttributeKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAttributeServiceClient_DeleteUserAttributeKey_Call) RunAndReturn(run func(context.Context, *iamv1.DeleteUserAttributeKeyRequest, ...grpc.CallOption) (*iamv1.DeleteUserAttributeKeyResponse, error)) *MockAttributeServiceClient_DeleteUserAttributeKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserAttributes provides a mock function with given fields: ctx, in, opts
func (_m *MockAttributeServiceClient) GetUserAttributes(ctx context.Context, in *iamv1.GetUserAttributesRequest, opts ...grpc.CallOption) (*iamv1.GetUserAttributesResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetUserAttributes")
	}

	var r0 *iamv1.GetUserAttributesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *iamv1.GetUserAttributesRequest, ...grpc.CallOption) (*iamv1.GetUserAttributesResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *iamv1.GetUserAttributesRequest, ...grpc.CallOption) *iamv1.GetUserAttributesResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*iamv1.GetUserAttributesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *iamv1.GetUserAttributesRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAttributeServiceClient_GetUserAttributes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserAttributes'
type MockAttributeServiceClient_GetUserAttributes_Call struct {
	*mock.Call
}

// GetUserAttributes is a helper method to define mock.On call
//   - ctx context.Context
//   - in *iamv1.GetUserAttributesRequest
//   - opts ...grpc.CallOption
func (_e *MockAttributeServiceClient_Expecter) GetUserAttributes(ctx interface{}, in interface{}, opts ...interface{}) *MockAttributeServiceClient_GetUserAttributes_Call {
	return &MockAttributeServiceClient_GetUserAttributes_Call{Call: _e.mock.On("GetUserAttributes",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockAttributeServiceClient_GetUserAttributes_Call) Run(run func(ctx context.Context, in *iamv1.GetUserAttributesRequest, opts ...grpc.CallOption)) *MockAttributeServiceClient_GetUserAttributes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*iamv1.GetUserAttributesRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockAttributeServiceClient_GetUserAttributes_Call) Return(_a0 *iamv1.GetUserAttributesResponse, _a1 error) *MockAttributeServiceClient_GetUserAttributes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAttributeServiceClient_GetUserAttributes_Call) RunAndReturn(run func(context.Context, *iamv1.GetUserAttributesRequest, ...grpc.CallOption) (*iamv1.GetUserAttributesResponse, error)) *MockAttributeServiceClient_GetUserAttributes_Call {
	_c.Call.Return(run)
	return _c
}

// PatchUserAttributes provides a mock function with given fields: ctx, in, opts
func (_m *MockAttributeServiceClient) PatchUserAttributes(ctx context.Context, in *iamv1.PatchUserAttributesRequest, opts ...grpc.CallOption) (*iamv1.PatchUserAttributesResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PatchUserAttributes")
	}

	var r0 *iamv1.PatchUserAttributesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *iamv1.PatchUserAttributesRequest, ...grpc.CallOption) (*iamv1.PatchUserAttributesResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *iamv1.PatchUserAttributesRequest, ...grpc.CallOption) *iamv1.PatchUserAttributesResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*iamv1.PatchUserAttributesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *iamv1.PatchUserAttributesRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAttributeServiceClient_PatchUserAttributes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PatchUserAttributes'
type MockAttributeServiceClient_PatchUserAttributes_Call struct {
	*mock.Call
}

// PatchUserAttributes is a helper method to define mock.On call
//   - ctx context.Context
//   - in *iamv1.PatchUserAttributesRequest
//   - opts ...grpc.CallOption
func (_e *MockAttributeServiceClient_Expecter) PatchUserAttributes(ctx interface{}, in interface{}, opts ...interface{}) *MockAttributeServiceClient_PatchUserAttributes_Call {
	return &MockAttributeServiceClient_PatchUserAttributes_Call{Call: _e.mock.On("PatchUserAttributes",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockAttributeServiceClient_PatchUserAttributes_Call) Run(run func(ctx context.Context, in *iamv1.PatchUserAttributesRequest, opts ...grpc.CallOption)) *MockAttributeServiceClient_PatchUserAttributes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*iamv1.PatchUserAttributesRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockAttributeServiceClient_PatchUserAttributes_Call) Return(_a0 *iamv1.PatchUserAttributesResponse, _a1 error) *MockAttributeServiceClient_PatchUserAttributes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAttributeServiceClient_PatchUserAttributes_Call) RunAndReturn(run func(context.Context, *iamv1.PatchUserAttributesRequest, ...grpc.CallOption) (*iamv1.PatchUserAttributesResponse, error)) *MockAttributeServiceClient_PatchUserAttributes_Call {
	_c.Call.Return(run)
	return _c
}

// ReplaceUserAttributes provides a mock function with given fields: ctx, in, opts
func (_m *MockAttributeServiceClient) ReplaceUserAttributes(ctx context.Context, in *iamv1.ReplaceUserAttributesRequest, opts ...grpc.CallOption) (*iamv1.ReplaceUserAttributesResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ReplaceUserAttributes")
	}

	var r0 *iamv1.ReplaceUserAttributesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *iamv1.ReplaceUserAttributesRequest, ...grpc.CallOption) (*iamv1.ReplaceUserAttributesResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *iamv1.ReplaceUserAttributesRequest, ...grpc.CallOption) *iamv1.ReplaceUserAttributesResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*iamv1.ReplaceUserAttributesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *iamv1.ReplaceUserAttributesRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAttributeServiceClient_ReplaceUserAttributes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplaceUserAttributes'
type MockAttributeServiceClient_ReplaceUserAttributes_Call struct {
	*mock.Call
}

// ReplaceUserAttributes is a helper method to define mock.On call
//   - ctx context.Context
//   - in *iamv1.ReplaceUserAttributesRequest
//   - opts ...grpc.CallOption
func (_e *MockAttributeServiceClient_Expecter) ReplaceUserAttributes(ctx interface{}, in interface{}, opts ...interface{}) *MockAttributeServiceClient_ReplaceUserAttributes_Call {
	return &MockAttributeServiceClient_ReplaceUserAttributes_Call{Call: _e.mock.On("ReplaceUserAttributes",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockAttributeServiceClient_ReplaceUserAttributes_Call) Run(run func(ctx context.Context, in *iamv1.ReplaceUserAttributesRequest, opts ...grpc.CallOption)) *MockAttributeServiceClient_ReplaceUserAttributes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*iamv1.ReplaceUserAttributesRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockAttributeServiceClient_ReplaceUserAttributes_Call) Return(_a0 *iamv1.ReplaceUserAttributesResponse, _a1 error) *MockAttributeServiceClient_ReplaceUserAttributes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAttributeServiceClient_ReplaceUserAttributes_Call) RunAndReturn(run func(context.Context, *iamv1.ReplaceUserAttributesRequest, ...grpc.CallOption) (*iamv1.ReplaceUserAttributesResponse, error)) *MockAttributeServiceClient_ReplaceUserAttributes_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAttributeServiceClient creates a new instance of MockAttributeServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAttributeServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAttributeServiceClient {
	mock := &MockAttributeServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
