// Code generated by mockery v2.53.5. DO NOT EDIT.

package usecase

import (
	context "context"
	iamv1 "secure-rag-platform/api/gen/go/iam/v1"

	mock "github.com/stretchr/testify/mock"
	grpc "google.golang.org/grpc"
)

// MockAuthServiceClient is an autogenerated mock type for the AuthServiceClient type
type MockAuthServiceClient struct {
	mock.Mock
}

type MockAuthServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthServiceClient) EXPECT() *MockAuthServiceClient_Expecter {
	return &MockAuthServiceClient_Expecter{mock: &_m.Mock}
}

// GetMe provides a mock function with given fields: ctx, in, opts
func (_m *MockAuthServiceClient) GetMe(ctx context.Context, in *iamv1.GetMeRequest, opts ...grpc.CallOption) (*iamv1.GetMeResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetMe")
	}

	var r0 *iamv1.GetMeResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *iamv1.GetMeRequest, ...grpc.CallOption) (*iamv1.GetMeResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *iamv1.GetMeRequest, ...grpc.CallOption) *iamv1.GetMeResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*iamv1.GetMeResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *iamv1.GetMeRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthServiceClient_GetMe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMe'
type MockAuthServiceClient_GetMe_Call struct {
	*mock.Call
}

// GetMe is a helper method to define mock.On call
//   - ctx context.Context
//   - in *iamv1.GetMeRequest
//   - opts ...grpc.CallOption
func (_e *MockAuthServiceClient_Expecter) GetMe(ctx interface{}, in interface{}, opts ...interface{}) *MockAuthServiceClient_GetMe_Call {
	return &MockAuthServiceClient_GetMe_Call{Call: _e.mock.On("GetMe",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockAuthServiceClient_GetMe_Call) Run(run func(ctx context.Context, in *iamv1.GetMeRequest, opts ...grpc.CallOption)) *MockAuthServiceClient_GetMe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*iamv1.GetMeRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockAuthServiceClient_GetMe_Call) Return(_a0 *iamv1.GetMeResponse, _a1 error) *MockAuthServiceClient_GetMe_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthServiceClient_GetMe_Call) RunAndReturn(run func(context.Context, *iamv1.GetMeRequest, ...grpc.CallOption) (*iamv1.GetMeResponse, error)) *MockAuthServiceClient_GetMe_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function with given fields: ctx, in, opts
func (_m *MockAuthServiceClient) Login(ctx context.Context, in *iamv1.LoginRequest, opts ...grpc.CallOption) (*iamv1.TokenPairResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *iamv1.TokenPairResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *iamv1.LoginRequest, ...grpc.CallOption) (*iamv1.TokenPairResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *iamv1.LoginRequest, ...grpc.CallOption) *iamv1.TokenPairResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*iamv1.TokenPairResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *iamv1.LoginRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthServiceClient_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthServiceClient_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - in *iamv1.LoginRequest
//   - opts ...grpc.CallOption
func (_e *MockAuthServiceClient_Expecter) Login(ctx interface{}, in interface{}, opts ...interface{}) *MockAuthServiceClient_Login_Call {
	return &MockAuthServiceClient_Login_Call{Call: _e.mock.On("Login",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockAuthServiceClient_Login_Call) Run(run func(ctx context.Context, in *iamv1.LoginRequest, opts ...grpc.CallOption)) *MockAuthServiceClient_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*iamv1.LoginRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockAuthServiceClient_Login_Call) Return(_a0 *iamv1.TokenPairResponse, _a1 error) *MockAuthServiceClient_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthServiceClient_Login_Call) RunAndReturn(run func(context.Context, *iamv1.LoginRequest, ...grpc.CallOption) (*iamv1.TokenPairResponse, error)) *MockAuthServiceClient_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function with given fields: ctx, in, opts
func (_m *MockAuthServiceClient) Logout(ctx context.Context, in *iamv1.LogoutRequest, opts ...grpc.CallOption) (*iamv1.LogoutResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 *iamv1.LogoutResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *iamv1.LogoutRequest, ...grpc.CallOption) (*iamv1.LogoutResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *iamv1.LogoutRequest, ...grpc.CallOption) *iamv1.LogoutResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*iamv1.LogoutResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *iamv1.LogoutRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthServiceClient_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MockAuthServiceClient_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - in *iamv1.LogoutRequest
//   - opts ...grpc.CallOption
func (_e *MockAuthServiceClient_Expecter) Logout(ctx interface{}, in interface{}, opts ...interface{}) *MockAuthServiceClient_Logout_Call {
	return &MockAuthServiceClient_Logout_Call{Call: _e.mock.On("Logout",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockAuthServiceClient_Logout_Call) Run(run func(ctx context.Context, in *iamv1.LogoutRequest, opts ...grpc.CallOption)) *MockAuthServiceClient_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*iamv1.LogoutRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockAuthServiceClient_Logout_Call) Return(_a0 *iamv1.LogoutResponse, _a1 error) *MockAuthServiceClient_Logout_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthServiceClient_Logout_Call) RunAndReturn(run func(context.Context, *iamv1.LogoutRequest, ...grpc.CallOption) (*iamv1.LogoutResponse, error)) *MockAuthServiceClient_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// LogoutAll provides a mock function with given fields: ctx, in, opts
func (_m *MockAuthServiceClient) LogoutAll(ctx context.Context, in *iamv1.LogoutAllRequest, opts ...grpc.CallOption) (*iamv1.LogoutAllResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for LogoutAll")
	}

	var r0 *iamv1.LogoutAllResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *iamv1.LogoutAllRequest, ...grpc.CallOption) (*iamv1.LogoutAllResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *iamv1.LogoutAllRequest, ...grpc.CallOption) *iamv1.LogoutAllResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*iamv1.LogoutAllResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *iamv1.LogoutAllRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthServiceClient_LogoutAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogoutAll'
type MockAuthServiceClient_LogoutAll_Call struct {
	*mock.Call
}

// LogoutAll is a helper method to define mock.On call
//   - ctx context.Context
//   - in *iamv1.LogoutAllRequest
//   - opts ...grpc.CallOption
func (_e *MockAuthServiceClient_Expecter) LogoutAll(ctx interface{}, in interface{}, opts ...interface{}) *MockAuthServiceClient_LogoutAll_Call {
	return &MockAuthServiceClient_LogoutAll_Call{Call: _e.mock.On("LogoutAll",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockAuthServiceClient_LogoutAll_Call) Run(run func(ctx context.Context, in *iamv1.LogoutAllRequest, opts ...grpc.CallOption)) *MockAuthServiceClient_LogoutAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*iamv1.LogoutAllRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockAuthServiceClient_LogoutAll_Call) Return(_a0 *iamv1.LogoutAllResponse, _a1 error) *MockAuthServiceClient_LogoutAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthServiceClient_LogoutAll_Call) RunAndReturn(run func(context.Context, *iamv1.LogoutAllRequest, ...grpc.CallOption) (*iamv1.LogoutAllResponse, error)) *MockAuthServiceClient_LogoutAll_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshToken provides a mock function with given fields: ctx, in, opts
func (_m *MockAuthServiceClient) RefreshToken(ctx context.Context, in *iamv1.RefreshTokenRequest, opts ...grpc.CallOption) (*iamv1.TokenPairResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}

	var r0 *iamv1.TokenPairResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *iamv1.RefreshTokenRequest, ...grpc.CallOption) (*iamv1.TokenPairResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *iamv1.RefreshTokenRequest, ...grpc.CallOption) *iamv1.TokenPairResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*iamv1.TokenPairResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *iamv1.RefreshTokenRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthServiceClient_RefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshToken'
type MockAuthServiceClient_RefreshToken_Call struct {
	*mock.Call
}

// RefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - in *iamv1.RefreshTokenRequest
//   - opts ...grpc.CallOption
func (_e *MockAuthServiceClient_Expecter) RefreshToken(ctx interface{}, in interface{}, opts ...interface{}) *MockAuthServiceClient_RefreshToken_Call {
	return &MockAuthServiceClient_RefreshToken_Call{Call: _e.mock.On("RefreshToken",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockAuthServiceClient_RefreshToken_Call) Run(run func(ctx context.Context, in *iamv1.RefreshTokenRequest, opts ...grpc.CallOption)) *MockAuthServiceClient_RefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*iamv1.RefreshTokenRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockAuthServiceClient_RefreshToken_Call) Return(_a0 *iamv1.TokenPairResponse, _a1 error) *MockAuthServiceClient_RefreshToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthServiceClient_RefreshToken_Call) RunAndReturn(run func(context.Context, *iamv1.RefreshTokenRequest, ...grpc.CallOption) (*iamv1.TokenPairResponse, error)) *MockAuthServiceClient_RefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthServiceClient creates a new instance of MockAuthServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthServiceClient {
	mock := &MockAuthServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
