// Code generated by mockery v2.53.5. DO NOT EDIT.

package usecase

import (
	context "context"
	iamv1 "secure-rag-platform/api/gen/go/iam/v1"

	mock "github.com/stretchr/testify/mock"
	grpc "google.golang.org/grpc"
)

// MockInternalIAMServiceClient is an autogenerated mock type for the InternalIAMServiceClient type
type MockInternalIAMServiceClient struct {
	mock.Mock
}

type MockInternalIAMServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInternalIAMServiceClient) EXPECT() *MockInternalIAMServiceClient_Expecter {
	return &MockInternalIAMServiceClient_Expecter{mock: &_m.Mock}
}

// GetSubjectContext provides a mock function with given fields: ctx, in, opts
func (_m *MockInternalIAMServiceClient) GetSubjectContext(ctx context.Context, in *iamv1.GetSubjectContextRequest, opts ...grpc.CallOption) (*iamv1.GetSubjectContextResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetSubjectContext")
	}

	var r0 *iamv1.GetSubjectContextResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *iamv1.GetSubjectContextRequest, ...grpc.CallOption) (*iamv1.GetSubjectContextResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *iamv1.GetSubjectContextRequest, ...grpc.CallOption) *iamv1.GetSubjectContextResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*iamv1.GetSubjectContextResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *iamv1.GetSubjectContextRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInternalIAMServiceClient_GetSubjectContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSubjectContext'
type MockInternalIAMServiceClient_GetSubjectContext_Call struct {
	*mock.Call
}

// GetSubjectContext is a helper method to define mock.On call
//   - ctx context.Context
//   - in *iamv1.GetSubjectContextRequest
//   - opts ...grpc.CallOption
func (_e *MockInternalIAMServiceClient_Expecter) GetSubjectContext(ctx interface{}, in interface{}, opts ...interface{}) *MockInternalIAMServiceClient_GetSubjectContext_Call {
	return &MockInternalIAMServiceClient_GetSubjectContext_Call{Call: _e.mock.On("GetSubjectContext",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockInternalIAMServiceClient_GetSubjectContext_Call) Run(run func(ctx context.Context, in *iamv1.GetSubjectContextRequest, opts ...grpc.CallOption)) *MockInternalIAMServiceClient_GetSubjectContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*iamv1.GetSubjectContextRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockInternalIAMServiceClient_GetSubjectContext_Call) Return(_a0 *iamv1.GetSubjectContextResponse, _a1 error) *MockInternalIAMServiceClient_GetSubjectContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInternalIAMServiceClient_GetSubjectContext_Call) RunAndReturn(run func(context.Context, *iamv1.GetSubjectContextRequest, ...grpc.CallOption) (*iamv1.GetSubjectContextResponse, error)) *MockInternalIAMServiceClient_GetSubjectContext_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateAccessToken provides a mock function with given fields: ctx, in, opts
func (_m *MockInternalIAMServiceClient) ValidateAccessToken(ctx context.Context, in *iamv1.ValidateAccessTokenRequest, opts ...grpc.CallOption) (*iamv1.ValidateAccessTokenResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ValidateAccessToken")
	}

	var r0 *iamv1.ValidateAccessTokenResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *iamv1.ValidateAccessTokenRequest, ...grpc.CallOption) (*iamv1.ValidateAccessTokenResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *iamv1.ValidateAccessTokenRequest, ...grpc.CallOption) *iamv1.ValidateAccessTokenResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*iamv1.ValidateAccessTokenResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *iamv1.ValidateAccessTokenRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInternalIAMServiceClient_ValidateAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateAccessToken'
type MockInternalIAMServiceClient_ValidateAccessToken_Call struct {
	*mock.Call
}

// ValidateAccessToken is a helper method to define mock.On call
//   - ctx context.Context
//   - in *iamv1.ValidateAccessTokenRequest
//   - opts ...grpc.CallOption
func (_e *MockInternalIAMServiceClient_Expecter) ValidateAccessToken(ctx interface{}, in interface{}, opts ...interface{}) *MockInternalIAMServiceClient_ValidateAccessToken_Call {
	return &MockInternalIAMServiceClient_ValidateAccessToken_Call{Call: _e.mock.On("ValidateAccessToken",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockInternalIAMServiceClient_ValidateAccessToken_Call) Run(run func(ctx context.Context, in *iamv1.ValidateAccessTokenRequest, opts ...grpc.CallOption)) *MockInternalIAMServiceClient_ValidateAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*iamv1.ValidateAccessTokenRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockInternalIAMServiceClient_ValidateAccessToken_Call) Return(_a0 *iamv1.ValidateAccessTokenResponse, _a1 error) *MockInternalIAMServiceClient_ValidateAccessToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInternalIAMServiceClient_ValidateAccessToken_Call) RunAndReturn(run func(context.Context, *iamv1.ValidateAccessTokenRequest, ...grpc.CallOption) (*iamv1.ValidateAccessTokenResponse, error)) *MockInternalIAMServiceClient_ValidateAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInternalIAMServiceClient creates a new instance of MockInternalIAMServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInternalIAMServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInternalIAMServiceClient {
	mock := &MockInternalIAMServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
