// Code generated by mockery v2.53.5. DO NOT EDIT.

package usecase

import (
	context "context"
	knowledgev1 "secure-rag-platform/api/gen/go/knowledge/v1"

	mock "github.com/stretchr/testify/mock"
	httpbody "google.golang.org/genproto/googleapis/api/httpbody"
	grpc "google.golang.org/grpc"
)

// MockKnowledgeServiceClient is an autogenerated mock type for the KnowledgeServiceClient type
type MockKnowledgeServiceClient struct {
	mock.Mock
}

type MockKnowledgeServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKnowledgeServiceClient) EXPECT() *MockKnowledgeServiceClient_Expecter {
	return &MockKnowledgeServiceClient_Expecter{mock: &_m.Mock}
}

// CreateDocumentStream provides a mock function with given fields: ctx, opts
func (_m *MockKnowledgeServiceClient) CreateDocumentStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[knowledgev1.CreateDocumentStreamRequest, knowledgev1.CreateDocumentResponse], error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateDocumentStream")
	}

	var r0 grpc.ClientStreamingClient[knowledgev1.CreateDocumentStreamRequest, knowledgev1.CreateDocumentResponse]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...grpc.CallOption) (grpc.ClientStreamingClient[knowledgev1.CreateDocumentStreamRequest, knowledgev1.CreateDocumentResponse], error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...grpc.CallOption) grpc.ClientStreamingClient[knowledgev1.CreateDocumentStreamRequest, knowledgev1.CreateDocumentResponse]); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(grpc.ClientStreamingClient[knowledgev1.CreateDocumentStreamRequest, knowledgev1.CreateDocumentResponse])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKnowledgeServiceClient_CreateDocumentStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDocumentStream'
type MockKnowledgeServiceClient_CreateDocumentStream_Call struct {
	*mock.Call
}

// CreateDocumentStream is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...grpc.CallOption
func (_e *MockKnowledgeServiceClient_Expecter) CreateDocumentStream(ctx interface{}, opts ...interface{}) *MockKnowledgeServiceClient_CreateDocumentStream_Call {
	return &MockKnowledgeServiceClient_CreateDocumentStream_Call{Call: _e.mock.On("CreateDocumentStream",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *MockKnowledgeServiceClient_CreateDocumentStream_Call) Run(run func(ctx context.Context, opts ...grpc.CallOption)) *MockKnowledgeServiceClient_CreateDocumentStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *MockKnowledgeServiceClient_CreateDocumentStream_Call) Return(_a0 grpc.ClientStreamingClient[knowledgev1.CreateDocumentStreamRequest, knowledgev1.CreateDocumentResponse], _a1 error) *MockKnowledgeServiceClient_CreateDocumentStream_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKnowledgeServiceClient_CreateDocumentStream_Call) RunAndReturn(run func(context.Context, ...grpc.CallOption) (grpc.ClientStreamingClient[knowledgev1.CreateDocumentStreamRequest, knowledgev1.CreateDocumentResponse], error)) *MockKnowledgeServiceClient_CreateDocumentStream_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteDocument provides a mock function with given fields: ctx, in, opts
func (_m *MockKnowledgeServiceClient) DeleteDocument(ctx context.Context, in *knowledgev1.DeleteDocumentRequest, opts ...grpc.CallOption) (*knowledgev1.DeleteDocumentResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDocument")
	}

	var r0 *knowledgev1.DeleteDocumentResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *knowledgev1.DeleteDocumentRequest, ...grpc.CallOption) (*knowledgev1.DeleteDocumentResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *knowledgev1.DeleteDocumentRequest, ...grpc.CallOption) *knowledgev1.DeleteDocumentResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*knowledgev1.DeleteDocumentResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *knowledgev1.DeleteDocumentRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKnowledgeServiceClient_DeleteDocument_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteDocument'
type MockKnowledgeServiceClient_DeleteDocument_Call struct {
	*mock.Call
}

// DeleteDocument is a helper method to define mock.On call
//   - ctx context.Context
//   - in *knowledgev1.DeleteDocumentRequest
//   - opts ...grpc.CallOption
func (_e *MockKnowledgeServiceClient_Expecter) DeleteDocument(ctx interface{}, in interface{}, opts ...interface{}) *MockKnowledgeServiceClient_DeleteDocument_Call {
	return &MockKnowledgeServiceClient_DeleteDocument_Call{Call: _e.mock.On("DeleteDocument",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockKnowledgeServiceClient_DeleteDocument_Call) Run(run func(ctx context.Context, in *knowledgev1.DeleteDocumentRequest, opts ...grpc.CallOption)) *MockKnowledgeServiceClient_DeleteDocument_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*knowledgev1.DeleteDocumentRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockKnowledgeServiceClient_DeleteDocument_Call) Return(_a0 *knowledgev1.DeleteDocumentResponse, _a1 error) *MockKnowledgeServiceClient_DeleteDocument_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKnowledgeServiceClient_DeleteDocument_Call) RunAndReturn(run func(context.Context, *knowledgev1.DeleteDocumentRequest, ...grpc.CallOption) (*knowledgev1.DeleteDocumentResponse, error)) *MockKnowledgeServiceClient_DeleteDocument_Call {
	_c.Call.Return(run)
	return _c
}

// DownloadFile provides a mock function with given fields: ctx, in, opts
func (_m *MockKnowledgeServiceClient) DownloadFile(ctx context.Context, in *knowledgev1.DownloadFileRequest, opts ...grpc.CallOption) (*httpbody.HttpBody, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DownloadFile")
	}

	var r0 *httpbody.HttpBody
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *knowledgev1.DownloadFileRequest, ...grpc.CallOption) (*httpbody.HttpBody, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *knowledgev1.DownloadFileRequest, ...grpc.CallOption) *httpbody.HttpBody); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*httpbody.HttpBody)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *knowledgev1.DownloadFileRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKnowledgeServiceClient_DownloadFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownloadFile'
type MockKnowledgeServiceClient_DownloadFile_Call struct {
	*mock.Call
}

// DownloadFile is a helper method to define mock.On call
//   - ctx context.Context
//   - in *knowledgev1.DownloadFileRequest
//   - opts ...grpc.CallOption
func (_e *MockKnowledgeServiceClient_Expecter) DownloadFile(ctx interface{}, in interface{}, opts ...interface{}) *MockKnowledgeServiceClient_DownloadFile_Call {
	return &MockKnowledgeServiceClient_DownloadFile_Call{Call: _e.mock.On("DownloadFile",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockKnowledgeServiceClient_DownloadFile_Call) Run(run func(ctx context.Context, in *knowledgev1.DownloadFileRequest, opts ...grpc.CallOption)) *MockKnowledgeServiceClient_DownloadFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*knowledgev1.DownloadFileRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockKnowledgeServiceClient_DownloadFile_Call) Return(_a0 *httpbody.HttpBody, _a1 error) *MockKnowledgeServiceClient_DownloadFile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKnowledgeServiceClient_DownloadFile_Call) RunAndReturn(run func(context.Context, *knowledgev1.DownloadFileRequest, ...grpc.CallOption) (*httpbody.HttpBody, error)) *MockKnowledgeServiceClient_DownloadFile_Call {
	_c.Call.Return(run)
	return _c
}

// GetDocument provides a mock function with given fields: ctx, in, opts
func (_m *MockKnowledgeServiceClient) GetDocument(ctx context.Context, in *knowledgev1.GetDocumentRequest, opts ...grpc.CallOption) (*knowledgev1.GetDocumentResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetDocument")
	}

	var r0 *knowledgev1.GetDocumentResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *knowledgev1.GetDocumentRequest, ...grpc.CallOption) (*knowledgev1.GetDocumentResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *knowledgev1.GetDocumentRequest, ...grpc.CallOption) *knowledgev1.GetDocumentResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*knowledgev1.GetDocumentResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *knowledgev1.GetDocumentRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKnowledgeServiceClient_GetDocument_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDocument'
type MockKnowledgeServiceClient_GetDocument_Call struct {
	*mock.Call
}

// GetDocument is a helper method to define mock.On call
//   - ctx context.Context
//   - in *knowledgev1.GetDocumentRequest
//   - opts ...grpc.CallOption
func (_e *MockKnowledgeServiceClient_Expecter) GetDocument(ctx interface{}, in interface{}, opts ...interface{}) *MockKnowledgeServiceClient_GetDocument_Call {
	return &MockKnowledgeServiceClient_GetDocument_Call{Call: _e.mock.On("GetDocument",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockKnowledgeServiceClient_GetDocument_Call) Run(run func(ctx context.Context, in *knowledgev1.GetDocumentRequest, opts ...grpc.CallOption)) *MockKnowledgeServiceClient_GetDocument_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*knowledgev1.GetDocumentRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockKnowledgeServiceClient_GetDocument_Call) Return(_a0 *knowledgev1.GetDocumentResponse, _a1 error) *MockKnowledgeServiceClient_GetDocument_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKnowledgeServiceClient_GetDocument_Call) RunAndReturn(run func(context.Context, *knowledgev1.GetDocumentRequest, ...grpc.CallOption) (*knowledgev1.GetDocumentResponse, error)) *MockKnowledgeServiceClient_GetDocument_Call {
	_c.Call.Return(run)
	return _c
}

// Health provides a mock function with given fields: ctx, in, opts
func (_m *MockKnowledgeServiceClient) Health(ctx context.Context, in *knowledgev1.HealthRequest, opts ...grpc.CallOption) (*knowledgev1.HealthResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Health")
	}

	var r0 *knowledgev1.HealthResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *knowledgev1.HealthRequest, ...grpc.CallOption) (*knowledgev1.HealthResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *knowledgev1.HealthRequest, ...grpc.CallOption) *knowledgev1.HealthResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*knowledgev1.HealthResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *knowledgev1.HealthRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKnowledgeServiceClient_Health_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Health'
type MockKnowledgeServiceClient_Health_Call struct {
	*mock.Call
}

// Health is a helper method to define mock.On call
//   - ctx context.Context
//   - in *knowledgev1.HealthRequest
//   - opts ...grpc.CallOption
func (_e *MockKnowledgeServiceClient_Expecter) Health(ctx interface{}, in interface{}, opts ...interface{}) *MockKnowledgeServiceClient_Health_Call {
	return &MockKnowledgeServiceClient_Health_Call{Call: _e.mock.On("Health",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockKnowledgeServiceClient_Health_Call) Run(run func(ctx context.Context, in *knowledgev1.HealthRequest, opts ...grpc.CallOption)) *MockKnowledgeServiceClient_Health_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*knowledgev1.HealthRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockKnowledgeServiceClient_Health_Call) Return(_a0 *knowledgev1.HealthResponse, _a1 error) *MockKnowledgeServiceClient_Health_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKnowledgeServiceClient_Health_Call) RunAndReturn(run func(context.Context, *knowledgev1.HealthRequest, ...grpc.CallOption) (*knowledgev1.HealthResponse, error)) *MockKnowledgeServiceClient_Health_Call {
	_c.Call.Return(run)
	return _c
}

// ListDocuments provides a mock function with given fields: ctx, in, opts
func (_m *MockKnowledgeServiceClient) ListDocuments(ctx context.Context, in *knowledgev1.ListDocumentsRequest, opts ...grpc.CallOption) (*knowledgev1.ListDocumentsResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListDocuments")
	}

	var r0 *knowledgev1.ListDocumentsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *knowledgev1.ListDocumentsRequest, ...grpc.CallOption) (*knowledgev1.ListDocumentsResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *knowledgev1.ListDocumentsRequest, ...grpc.CallOption) *knowledgev1.ListDocumentsResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*knowledgev1.ListDocumentsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *knowledgev1.ListDocumentsRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKnowledgeServiceClient_ListDocuments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDocuments'
type MockKnowledgeServiceClient_ListDocuments_Call struct {
	*mock.Call
}

// ListDocuments is a helper method to define mock.On call
//   - ctx context.Context
//   - in *knowledgev1.ListDocumentsRequest
//   - opts ...grpc.CallOption
func (_e *MockKnowledgeServiceClient_Expecter) ListDocuments(ctx interface{}, in interface{}, opts ...interface{}) *MockKnowledgeServiceClient_ListDocuments_Call {
	return &MockKnowledgeServiceClient_ListDocuments_Call{Call: _e.mock.On("ListDocuments",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockKnowledgeServiceClient_ListDocuments_Call) Run(run func(ctx context.Context, in *knowledgev1.ListDocumentsRequest, opts ...grpc.CallOption)) *MockKnowledgeServiceClient_ListDocuments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*knowledgev1.ListDocumentsRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockKnowledgeServiceClient_ListDocuments_Call) Return(_a0 *knowledgev1.ListDocumentsResponse, _a1 error) *MockKnowledgeServiceClient_ListDocuments_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKnowledgeServiceClient_ListDocuments_Call) RunAndReturn(run func(context.Context, *knowledgev1.ListDocumentsRequest, ...grpc.CallOption) (*knowledgev1.ListDocumentsResponse, error)) *MockKnowledgeServiceClient_ListDocuments_Call {
	_c.Call.Return(run)
	return _c
}

// ReindexDocument provides a mock function with given fields: ctx, in, opts
func (_m *MockKnowledgeServiceClient) ReindexDocument(ctx context.Context, in *knowledgev1.ReindexDocumentRequest, opts ...grpc.CallOption) (*knowledgev1.ReindexDocumentResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ReindexDocument")
	}

	var r0 *knowledgev1.ReindexDocumentResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *knowledgev1.ReindexDocumentRequest, ...grpc.CallOption) (*knowledgev1.ReindexDocumentResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *knowledgev1.ReindexDocumentRequest, ...grpc.CallOption) *knowledgev1.ReindexDocumentResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*knowledgev1.ReindexDocumentResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *knowledgev1.ReindexDocumentRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKnowledgeServiceClient_ReindexDocument_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReindexDocument'
type MockKnowledgeServiceClient_ReindexDocument_Call struct {
	*mock.Call
}

// ReindexDocument is a helper method to define mock.On call
//   - ctx context.Context
//   - in *knowledgev1.ReindexDocumentRequest
//   - opts ...grpc.CallOption
func (_e *MockKnowledgeServiceClient_Expecter) ReindexDocument(ctx interface{}, in interface{}, opts ...interface{}) *MockKnowledgeServiceClient_ReindexDocument_Call {
	return &MockKnowledgeServiceClient_ReindexDocument_Call{Call: _e.mock.On("ReindexDocument",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockKnowledgeServiceClient_ReindexDocument_Call) Run(run func(ctx context.Context, in *knowledgev1.ReindexDocumentRequest, opts ...grpc.CallOption)) *MockKnowledgeServiceClient_ReindexDocument_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*knowledgev1.ReindexDocumentRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockKnowledgeServiceClient_ReindexDocument_Call) Return(_a0 *knowledgev1.ReindexDocumentResponse, _a1 error) *MockKnowledgeServiceClient_ReindexDocument_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKnowledgeServiceClient_ReindexDocument_Call) RunAndReturn(run func(context.Context, *knowledgev1.ReindexDocumentRequest, ...grpc.CallOption) (*knowledgev1.ReindexDocumentResponse, error)) *MockKnowledgeServiceClient_ReindexDocument_Call {
	_c.Call.Return(run)
	return _c
}

// RestoreDocument provides a mock function with given fields: ctx, in, opts
func (_m *MockKnowledgeServiceClient) RestoreDocument(ctx context.Context, in *knowledgev1.RestoreDocumentRequest, opts ...grpc.CallOption) (*knowledgev1.RestoreDocumentResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for RestoreDocument")
	}

	var r0 *knowledgev1.RestoreDocumentResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *knowledgev1.RestoreDocumentRequest, ...grpc.CallOption) (*knowledgev1.RestoreDocumentResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *knowledgev1.RestoreDocumentRequest, ...grpc.CallOption) *knowledgev1.RestoreDocumentResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*knowledgev1.RestoreDocumentResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *knowledgev1.RestoreDocumentRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKnowledgeServiceClient_RestoreDocument_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestoreDocument'
type MockKnowledgeServiceClient_RestoreDocument_Call struct {
	*mock.Call
}

// RestoreDocument is a helper method to define mock.On call
//   - ctx context.Context
//   - in *knowledgev1.RestoreDocumentRequest
//   - opts ...grpc.CallOption
func (_e *MockKnowledgeServiceClient_Expecter) RestoreDocument(ctx interface{}, in interface{}, opts ...interface{}) *MockKnowledgeServiceClient_RestoreDocument_Call {
	return &MockKnowledgeServiceClient_RestoreDocument_Call{Call: _e.mock.On("RestoreDocument",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockKnowledgeServiceClient_RestoreDocument_Call) Run(run func(ctx context.Context, in *knowledgev1.RestoreDocumentRequest, opts ...grpc.CallOption)) *MockKnowledgeServiceClient_RestoreDocument_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*knowledgev1.RestoreDocumentRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockKnowledgeServiceClient_RestoreDocument_Call) Return(_a0 *knowledgev1.RestoreDocumentResponse, _a1 error) *MockKnowledgeServiceClient_RestoreDocument_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKnowledgeServiceClient_RestoreDocument_Call) RunAndReturn(run func(context.Context, *knowledgev1.RestoreDocumentRequest, ...grpc.CallOption) (*knowledgev1.RestoreDocumentResponse, error)) *MockKnowledgeServiceClient_RestoreDocument_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDocument provides a mock function with given fields: ctx, in, opts
func (_m *MockKnowledgeServiceClient) UpdateDocument(ctx context.Context, in *knowledgev1.UpdateDocumentRequest, opts ...grpc.CallOption) (*knowledgev1.UpdateDocumentResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDocument")
	}

	var r0 *knowledgev1.UpdateDocumentResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *knowledgev1.UpdateDocumentRequest, ...grpc.CallOption) (*knowledgev1.UpdateDocumentResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *knowledgev1.UpdateDocumentRequest, ...grpc.CallOption) *knowledgev1.UpdateDocumentResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*knowledgev1.UpdateDocumentResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *knowledgev1.UpdateDocumentRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKnowledgeServiceClient_UpdateDocument_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDocument'
type MockKnowledgeServiceClient_UpdateDocument_Call struct {
	*mock.Call
}

// UpdateDocument is a helper method to define mock.On call
//   - ctx context.Context
//   - in *knowledgev1.UpdateDocumentRequest
//   - opts ...grpc.CallOption
func (_e *MockKnowledgeServiceClient_Expecter) UpdateDocument(ctx interface{}, in interface{}, opts ...interface{}) *MockKnowledgeServiceClient_UpdateDocument_Call {
	return &MockKnowledgeServiceClient_UpdateDocument_Call{Call: _e.mock.On("UpdateDocument",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockKnowledgeServiceClient_UpdateDocument_Call) Run(run func(ctx context.Context, in *knowledgev1.UpdateDocumentRequest, opts ...grpc.CallOption)) *MockKnowledgeServiceClient_UpdateDocument_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*knowledgev1.UpdateDocumentRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockKnowledgeServiceClient_UpdateDocument_Call) Return(_a0 *knowledgev1.UpdateDocumentResponse, _a1 error) *MockKnowledgeServiceClient_UpdateDocument_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKnowledgeServiceClient_UpdateDocument_Call) RunAndReturn(run func(context.Context, *knowledgev1.UpdateDocumentRequest, ...grpc.CallOption) (*knowledgev1.UpdateDocumentResponse, error)) *MockKnowledgeServiceClient_UpdateDocument_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDocumentAttributes provides a mock function with given fields: ctx, in, opts
func (_m *MockKnowledgeServiceClient) UpdateDocumentAttributes(ctx context.Context, in *knowledgev1.UpdateDocumentAttributesRequest, opts ...grpc.CallOption) (*knowledgev1.UpdateDocumentAttributesResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDocumentAttributes")
	}

	var r0 *knowledgev1.UpdateDocumentAttributesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *knowledgev1.UpdateDocumentAttributesRequest, ...grpc.CallOption) (*knowledgev1.UpdateDocumentAttributesResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *knowledgev1.UpdateDocumentAttributesRequest, ...grpc.CallOption) *knowledgev1.UpdateDocumentAttributesResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*knowledgev1.UpdateDocumentAttributesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *knowledgev1.UpdateDocumentAttributesRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKnowledgeServiceClient_UpdateDocumentAttributes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDocumentAttributes'
type MockKnowledgeServiceClient_UpdateDocumentAttributes_Call struct {
	*mock.Call
}

// UpdateDocumentAttributes is a helper method to define mock.On call
//   - ctx context.Context
//   - in *knowledgev1.UpdateDocumentAttributesRequest
//   - opts ...grpc.CallOption
func (_e *MockKnowledgeServiceClient_Expecter) UpdateDocumentAttributes(ctx interface{}, in interface{}, opts ...interface{}) *MockKnowledgeServiceClient_UpdateDocumentAttributes_Call {
	return &MockKnowledgeServiceClient_UpdateDocumentAttributes_Call{Call: _e.mock.On("UpdateDocumentAttributes",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockKnowledgeServiceClient_UpdateDocumentAttributes_Call) Run(run func(ctx context.Context, in *knowledgev1.UpdateDocumentAttributesRequest, opts ...grpc.CallOption)) *MockKnowledgeServiceClient_UpdateDocumentAttributes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*knowledgev1.UpdateDocumentAttributesRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockKnowledgeServiceClient_UpdateDocumentAttributes_Call) Return(_a0 *knowledgev1.UpdateDocumentAttributesResponse, _a1 error) *MockKnowledgeServiceClient_UpdateDocumentAttributes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKnowledgeServiceClient_UpdateDocumentAttributes_Call) RunAndReturn(run func(context.Context, *knowledgev1.UpdateDocumentAttributesRequest, ...grpc.CallOption) (*knowledgev1.UpdateDocumentAttributesResponse, error)) *MockKnowledgeServiceClient_UpdateDocumentAttributes_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockKnowledgeServiceClient creates a new instance of MockKnowledgeServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKnowledgeServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKnowledgeServiceClient {
	mock := &MockKnowledgeServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
