// Code generated by mockery v2.53.5. DO NOT EDIT.

package usecase

import (
	context "context"
	iamv1 "secure-rag-platform/api/gen/go/iam/v1"

	mock "github.com/stretchr/testify/mock"
)

// MockPolicyAuthorizer is an autogenerated mock type for the PolicyAuthorizer type
type MockPolicyAuthorizer struct {
	mock.Mock
}

type MockPolicyAuthorizer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPolicyAuthorizer) EXPECT() *MockPolicyAuthorizer_Expecter {
	return &MockPolicyAuthorizer_Expecter{mock: &_m.Mock}
}

// AllowDocument provides a mock function with given fields: ctx, subject, documentAttributes
func (_m *MockPolicyAuthorizer) AllowDocument(ctx context.Context, subject *iamv1.SubjectContext, documentAttributes map[string]interface{}) (bool, error) {
	ret := _m.Called(ctx, subject, documentAttributes)

	if len(ret) == 0 {
		panic("no return value specified for AllowDocument")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *iamv1.SubjectContext, map[string]interface{}) (bool, error)); ok {
		return rf(ctx, subject, documentAttributes)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *iamv1.SubjectContext, map[string]interface{}) bool); ok {
		r0 = rf(ctx, subject, documentAttributes)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *iamv1.SubjectContext, map[string]interface{}) error); ok {
		r1 = rf(ctx, subject, documentAttributes)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPolicyAuthorizer_AllowDocument_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AllowDocument'
type MockPolicyAuthorizer_AllowDocument_Call struct {
	*mock.Call
}

// AllowDocument is a helper method to define mock.On call
//   - ctx context.Context
//   - subject *iamv1.SubjectContext
//   - documentAttributes map[string]interface{}
func (_e *MockPolicyAuthorizer_Expecter) AllowDocument(ctx interface{}, subject interface{}, documentAttributes interface{}) *MockPolicyAuthorizer_AllowDocument_Call {
	return &MockPolicyAuthorizer_AllowDocument_Call{Call: _e.mock.On("AllowDocument", ctx, subject, documentAttributes)}
}

func (_c *MockPolicyAuthorizer_AllowDocument_Call) Run(run func(ctx context.Context, subject *iamv1.SubjectContext, documentAttributes map[string]interface{})) *MockPolicyAuthorizer_AllowDocument_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*iamv1.SubjectContext), args[2].(map[string]interface{}))
	})
	return _c
}

func (_c *MockPolicyAuthorizer_AllowDocument_Call) Return(_a0 bool, _a1 error) *MockPolicyAuthorizer_AllowDocument_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPolicyAuthorizer_AllowDocument_Call) RunAndReturn(run func(context.Context, *iamv1.SubjectContext, map[string]interface{}) (bool, error)) *MockPolicyAuthorizer_AllowDocument_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPolicyAuthorizer creates a new instance of MockPolicyAuthorizer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPolicyAuthorizer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPolicyAuthorizer {
	mock := &MockPolicyAuthorizer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
