// Code generated by mockery v2.53.5. DO NOT EDIT.

package usecase

import (
	context "context"
	ragv1 "secure-rag-platform/api/gen/go/rag/v1"

	mock "github.com/stretchr/testify/mock"
	grpc "google.golang.org/grpc"
)

// MockRAGServiceClient is an autogenerated mock type for the RAGServiceClient type
type MockRAGServiceClient struct {
	mock.Mock
}

type MockRAGServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRAGServiceClient) EXPECT() *MockRAGServiceClient_Expecter {
	return &MockRAGServiceClient_Expecter{mock: &_m.Mock}
}

// DeleteDocumentIndex provides a mock function with given fields: ctx, in, opts
func (_m *MockRAGServiceClient) DeleteDocumentIndex(ctx context.Context, in *ragv1.DeleteDocumentIndexRequest, opts ...grpc.CallOption) (*ragv1.DeleteDocumentIndexResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDocumentIndex")
	}

	var r0 *ragv1.DeleteDocumentIndexResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ragv1.DeleteDocumentIndexRequest, ...grpc.CallOption) (*ragv1.DeleteDocumentIndexResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ragv1.DeleteDocumentIndexRequest, ...grpc.CallOption) *ragv1.DeleteDocumentIndexResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ragv1.DeleteDocumentIndexResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ragv1.DeleteDocumentIndexRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRAGServiceClient_DeleteDocumentIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteDocumentIndex'
type MockRAGServiceClient_DeleteDocumentIndex_Call struct {
	*mock.Call
}

// DeleteDocumentIndex is a helper method to define mock.On call
//   - ctx context.Context
//   - in *ragv1.DeleteDocumentIndexRequest
//   - opts ...grpc.CallOption
func (_e *MockRAGServiceClient_Expecter) DeleteDocumentIndex(ctx interface{}, in interface{}, opts ...interface{}) *MockRAGServiceClient_DeleteDocumentIndex_Call {
	return &MockRAGServiceClient_DeleteDocumentIndex_Call{Call: _e.mock.On("DeleteDocumentIndex",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockRAGServiceClient_DeleteDocumentIndex_Call) Run(run func(ctx context.Context, in *ragv1.DeleteDocumentIndexRequest, opts ...grpc.CallOption)) *MockRAGServiceClient_DeleteDocumentIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*ragv1.DeleteDocumentIndexRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockRAGServiceClient_DeleteDocumentIndex_Call) Return(_a0 *ragv1.DeleteDocumentIndexResponse, _a1 error) *MockRAGServiceClient_DeleteDocumentIndex_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRAGServiceClient_DeleteDocumentIndex_Call) RunAndReturn(run func(context.Context, *ragv1.DeleteDocumentIndexRequest, ...grpc.CallOption) (*ragv1.DeleteDocumentIndexResponse, error)) *MockRAGServiceClient_DeleteDocumentIndex_Call {
	_c.Call.Return(run)
	return _c
}

// Health provides a mock function with given fields: ctx, in, opts
func (_m *MockRAGServiceClient) Health(ctx context.Context, in *ragv1.HealthRequest, opts ...grpc.CallOption) (*ragv1.HealthResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Health")
	}

	var r0 *ragv1.HealthResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ragv1.HealthRequest, ...grpc.CallOption) (*ragv1.HealthResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ragv1.HealthRequest, ...grpc.CallOption) *ragv1.HealthResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ragv1.HealthResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ragv1.HealthRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRAGServiceClient_Health_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Health'
type MockRAGServiceClient_Health_Call struct {
	*mock.Call
}

// Health is a helper method to define mock.On call
//   - ctx context.Context
//   - in *ragv1.HealthRequest
//   - opts ...grpc.CallOption
func (_e *MockRAGServiceClient_Expecter) Health(ctx interface{}, in interface{}, opts ...interface{}) *MockRAGServiceClient_Health_Call {
	return &MockRAGServiceClient_Health_Call{Call: _e.mock.On("Health",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockRAGServiceClient_Health_Call) Run(run func(ctx context.Context, in *ragv1.HealthRequest, opts ...grpc.CallOption)) *MockRAGServiceClient_Health_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*ragv1.HealthRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockRAGServiceClient_Health_Call) Return(_a0 *ragv1.HealthResponse, _a1 error) *MockRAGServiceClient_Health_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRAGServiceClient_Health_Call) RunAndReturn(run func(context.Context, *ragv1.HealthRequest, ...grpc.CallOption) (*ragv1.HealthResponse, error)) *MockRAGServiceClient_Health_Call {
	_c.Call.Return(run)
	return _c
}

// IndexDocument provides a mock function with given fields: ctx, in, opts
func (_m *MockRAGServiceClient) IndexDocument(ctx context.Context, in *ragv1.IndexDocumentRequest, opts ...grpc.CallOption) (*ragv1.IndexDocumentResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for IndexDocument")
	}

	var r0 *ragv1.IndexDocumentResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ragv1.IndexDocumentRequest, ...grpc.CallOption) (*ragv1.IndexDocumentResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ragv1.IndexDocumentRequest, ...grpc.CallOption) *ragv1.IndexDocumentResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ragv1.IndexDocumentResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ragv1.IndexDocumentRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRAGServiceClient_IndexDocument_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IndexDocument'
type MockRAGServiceClient_IndexDocument_Call struct {
	*mock.Call
}

// IndexDocument is a helper method to define mock.On call
//   - ctx context.Context
//   - in *ragv1.IndexDocumentRequest
//   - opts ...grpc.CallOption
func (_e *MockRAGServiceClient_Expecter) IndexDocument(ctx interface{}, in interface{}, opts ...interface{}) *MockRAGServiceClient_IndexDocument_Call {
	return &MockRAGServiceClient_IndexDocument_Call{Call: _e.mock.On("IndexDocument",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockRAGServiceClient_IndexDocument_Call) Run(run func(ctx context.Context, in *ragv1.IndexDocumentRequest, opts ...grpc.CallOption)) *MockRAGServiceClient_IndexDocument_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*ragv1.IndexDocumentRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockRAGServiceClient_IndexDocument_Call) Return(_a0 *ragv1.IndexDocumentResponse, _a1 error) *MockRAGServiceClient_IndexDocument_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRAGServiceClient_IndexDocument_Call) RunAndReturn(run func(context.Context, *ragv1.IndexDocumentRequest, ...grpc.CallOption) (*ragv1.IndexDocumentResponse, error)) *MockRAGServiceClient_IndexDocument_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function with given fields: ctx, in, opts
func (_m *MockRAGServiceClient) Query(ctx context.Context, in *ragv1.QueryRequest, opts ...grpc.CallOption) (*ragv1.QueryResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 *ragv1.QueryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ragv1.QueryRequest, ...grpc.CallOption) (*ragv1.QueryResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ragv1.QueryRequest, ...grpc.CallOption) *ragv1.QueryResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ragv1.QueryResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ragv1.QueryRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRAGServiceClient_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockRAGServiceClient_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - in *ragv1.QueryRequest
//   - opts ...grpc.CallOption
func (_e *MockRAGServiceClient_Expecter) Query(ctx interface{}, in interface{}, opts ...interface{}) *MockRAGServiceClient_Query_Call {
	return &MockRAGServiceClient_Query_Call{Call: _e.mock.On("Query",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockRAGServiceClient_Query_Call) Run(run func(ctx context.Context, in *ragv1.QueryRequest, opts ...grpc.CallOption)) *MockRAGServiceClient_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*ragv1.QueryRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockRAGServiceClient_Query_Call) Return(_a0 *ragv1.QueryResponse, _a1 error) *MockRAGServiceClient_Query_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRAGServiceClient_Query_Call) RunAndReturn(run func(context.Context, *ragv1.QueryRequest, ...grpc.CallOption) (*ragv1.QueryResponse, error)) *MockRAGServiceClient_Query_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRAGServiceClient creates a new instance of MockRAGServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRAGServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRAGServiceClient {
	mock := &MockRAGServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
