// Code generated by mockery v2.53.5. DO NOT EDIT.

package usecase

import (
	context "context"
	iamv1 "secure-rag-platform/api/gen/go/iam/v1"

	mock "github.com/stretchr/testify/mock"
	grpc "google.golang.org/grpc"
)

// MockRoleServiceClient is an autogenerated mock type for the RoleServiceClient type
type MockRoleServiceClient struct {
	mock.Mock
}

type MockRoleServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoleServiceClient) EXPECT() *MockRoleServiceClient_Expecter {
	return &MockRoleServiceClient_Expecter{mock: &_m.Mock}
}

// AddUserRole provides a mock function with given fields: ctx, in, opts
func (_m *MockRoleServiceClient) AddUserRole(ctx context.Context, in *iamv1.AddUserRoleRequest, opts ...grpc.CallOption) (*iamv1.AddUserRoleResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for AddUserRole")
	}

	var r0 *iamv1.AddUserRoleResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *iamv1.AddUserRoleRequest, ...grpc.CallOption) (*iamv1.AddUserRoleResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *iamv1.AddUserRoleRequest, ...grpc.CallOption) *iamv1.AddUserRoleResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*iamv1.AddUserRoleResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *iamv1.AddUserRoleRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleServiceClient_AddUserRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddUserRole'
type MockRoleServiceClient_AddUserRole_Call struct {
	*mock.Call
}

// AddUserRole is a helper method to define mock.On call
//   - ctx context.Context
//   - in *iamv1.AddUserRoleRequest
//   - opts ...grpc.CallOption
func (_e *MockRoleServiceClient_Expecter) AddUserRole(ctx interface{}, in interface{}, opts ...interface{}) *MockRoleServiceClient_AddUserRole_Call {
	return &MockRoleServiceClient_AddUserRole_Call{Call: _e.mock.On("AddUserRole",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockRoleServiceClient_AddUserRole_Call) Run(run func(ctx context.Context, in *iamv1.AddUserRoleRequest, opts ...grpc.CallOption)) *MockRoleServiceClient_AddUserRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*iamv1.AddUserRoleRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockRoleServiceClient_AddUserRole_Call) Return(_a0 *iamv1.AddUserRoleResponse, _a1 error) *MockRoleServiceClient_AddUserRole_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleServiceClient_AddUserRole_Call) RunAndReturn(run func(context.Context, *iamv1.AddUserRoleRequest, ...grpc.CallOption) (*iamv1.AddUserRoleResponse, error)) *MockRoleServiceClient_AddUserRole_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserRoles provides a mock function with given fields: ctx, in, opts
func (_m *MockRoleServiceClient) GetUserRoles(ctx context.Context, in *iamv1.GetUserRolesRequest, opts ...grpc.CallOption) (*iamv1.GetUserRolesResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetUserRoles")
	}

	var r0 *iamv1.GetUserRolesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *iamv1.GetUserRolesRequest, ...grpc.CallOption) (*iamv1.GetUserRolesResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *iamv1.GetUserRolesRequest, ...grpc.CallOption) *iamv1.GetUserRolesResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*iamv1.GetUserRolesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *iamv1.GetUserRolesRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleServiceClient_GetUserRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserRoles'
type MockRoleServiceClient_GetUserRoles_Call struct {
	*mock.Call
}

// GetUserRoles is a helper method to define mock.On call
//   - ctx context.Context
//   - in *iamv1.GetUserRolesRequest
//   - opts ...grpc.CallOption
func (_e *MockRoleServiceClient_Expecter) GetUserRoles(ctx interface{}, in interface{}, opts ...interface{}) *MockRoleServiceClient_GetUserRoles_Call {
	return &MockRoleServiceClient_GetUserRoles_Call{Call: _e.mock.On("GetUserRoles",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockRoleServiceClient_GetUserRoles_Call) Run(run func(ctx context.Context, in *iamv1.GetUserRolesRequest, opts ...grpc.CallOption)) *MockRoleServiceClient_GetUserRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*iamv1.GetUserRolesRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockRoleServiceClient_GetUserRoles_Call) Return(_a0 *iamv1.GetUserRolesResponse, _a1 error) *MockRoleServiceClient_GetUserRoles_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleServiceClient_GetUserRoles_Call) RunAndReturn(run func(context.Context, *iamv1.GetUserRolesRequest, ...grpc.CallOption) (*iamv1.GetUserRolesResponse, error)) *MockRoleServiceClient_GetUserRoles_Call {
	_c.Call.Return(run)
	return _c
}

// ListRoles provides a mock function with given fields: ctx, in, opts
func (_m *MockRoleServiceClient) ListRoles(ctx context.Context, in *iamv1.ListRolesRequest, opts ...grpc.CallOption) (*iamv1.ListRolesResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListRoles")
	}

	var r0 *iamv1.ListRolesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *iamv1.ListRolesRequest, ...grpc.CallOption) (*iamv1.ListRolesResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *iamv1.ListRolesRequest, ...grpc.CallOption) *iamv1.ListRolesResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*iamv1.ListRolesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *iamv1.ListRolesRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleServiceClient_ListRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRoles'
type MockRoleServiceClient_ListRoles_Call struct {
	*mock.Call
}

// ListRoles is a helper method to define mock.On call
//   - ctx context.Context
//   - in *iamv1.ListRolesRequest
//   - opts ...grpc.CallOption
func (_e *MockRoleServiceClient_Expecter) ListRoles(ctx interface{}, in interface{}, opts ...interface{}) *MockRoleServiceClient_ListRoles_Call {
	return &MockRoleServiceClient_ListRoles_Call{Call: _e.mock.On("ListRoles",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockRoleServiceClient_ListRoles_Call) Run(run func(ctx context.Context, in *iamv1.ListRolesRequest, opts ...grpc.CallOption)) *MockRoleServiceClient_ListRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*iamv1.ListRolesRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockRoleServiceClient_ListRoles_Call) Return(_a0 *iamv1.ListRolesResponse, _a1 error) *MockRoleServiceClient_ListRoles_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleServiceClient_ListRoles_Call) RunAndReturn(run func(context.Context, *iamv1.ListRolesRequest, ...grpc.CallOption) (*iamv1.ListRolesResponse, error)) *MockRoleServiceClient_ListRoles_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveUserRole provides a mock function with given fields: ctx, in, opts
func (_m *MockRoleServiceClient) RemoveUserRole(ctx context.Context, in *iamv1.RemoveUserRoleRequest, opts ...grpc.CallOption) (*iamv1.RemoveUserRoleResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for RemoveUserRole")
	}

	var r0 *iamv1.RemoveUserRoleResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *iamv1.RemoveUserRoleRequest, ...grpc.CallOption) (*iamv1.RemoveUserRoleResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *iamv1.RemoveUserRoleRequest, ...grpc.CallOption) *iamv1.RemoveUserRoleResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*iamv1.RemoveUserRoleResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *iamv1.RemoveUserRoleRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleServiceClient_RemoveUserRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveUserRole'
type MockRoleServiceClient_RemoveUserRole_Call struct {
	*mock.Call
}

// RemoveUserRole is a helper method to define mock.On call
//   - ctx context.Context
//   - in *iamv1.RemoveUserRoleRequest
//   - opts ...grpc.CallOption
func (_e *MockRoleServiceClient_Expecter) RemoveUserRole(ctx interface{}, in interface{}, opts ...interface{}) *MockRoleServiceClient_RemoveUserRole_Call {
	return &MockRoleServiceClient_RemoveUserRole_Call{Call: _e.mock.On("RemoveUserRole",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockRoleServiceClient_RemoveUserRole_Call) Run(run func(ctx context.Context, in *iamv1.RemoveUserRoleRequest, opts ...grpc.CallOption)) *MockRoleServiceClient_RemoveUserRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*iamv1.RemoveUserRoleRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockRoleServiceClient_RemoveUserRole_Call) Return(_a0 *iamv1.RemoveUserRoleResponse, _a1 error) *MockRoleServiceClient_RemoveUserRole_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleServiceClient_RemoveUserRole_Call) RunAndReturn(run func(context.Context, *iamv1.RemoveUserRoleRequest, ...grpc.CallOption) (*iamv1.RemoveUserRoleResponse, error)) *MockRoleServiceClient_RemoveUserRole_Call {
	_c.Call.Return(run)
	return _c
}

// SetUserRoles provides a mock function with given fields: ctx, in, opts
func (_m *MockRoleServiceClient) SetUserRoles(ctx context.Context, in *iamv1.SetUserRolesRequest, opts ...grpc.CallOption) (*iamv1.SetUserRolesResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for SetUserRoles")
	}

	var r0 *iamv1.SetUserRolesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *iamv1.SetUserRolesRequest, ...grpc.CallOption) (*iamv1.SetUserRolesResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *iamv1.SetUserRolesRequest, ...grpc.CallOption) *iamv1.SetUserRolesResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*iamv1.SetUserRolesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *iamv1.SetUserRolesRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleServiceClient_SetUserRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetUserRoles'
type MockRoleServiceClient_SetUserRoles_Call struct {
	*mock.Call
}

// SetUserRoles is a helper method to define mock.On call
//   - ctx context.Context
//   - in *iamv1.SetUserRolesRequest
//   - opts ...grpc.CallOption
func (_e *MockRoleServiceClient_Expecter) SetUserRoles(ctx interface{}, in interface{}, opts ...interface{}) *MockRoleServiceClient_SetUserRoles_Call {
	return &MockRoleServiceClient_SetUserRoles_Call{Call: _e.mock.On("SetUserRoles",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockRoleServiceClient_SetUserRoles_Call) Run(run func(ctx context.Context, in *iamv1.SetUserRolesRequest, opts ...grpc.CallOption)) *MockRoleServiceClient_SetUserRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*iamv1.SetUserRolesRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockRoleServiceClient_SetUserRoles_Call) Return(_a0 *iamv1.SetUserRolesResponse, _a1 error) *MockRoleServiceClient_SetUserRoles_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleServiceClient_SetUserRoles_Call) RunAndReturn(run func(context.Context, *iamv1.SetUserRolesRequest, ...grpc.CallOption) (*iamv1.SetUserRolesResponse, error)) *MockRoleServiceClient_SetUserRoles_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRoleServiceClient creates a new instance of MockRoleServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoleServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoleServiceClient {
	mock := &MockRoleServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
