// Code generated by mockery v2.53.5. DO NOT EDIT.

package usecase

import (
	context "context"
	iamv1 "secure-rag-platform/api/gen/go/iam/v1"

	mock "github.com/stretchr/testify/mock"
	grpc "google.golang.org/grpc"
)

// MockUserServiceClient is an autogenerated mock type for the UserServiceClient type
type MockUserServiceClient struct {
	mock.Mock
}

type MockUserServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserServiceClient) EXPECT() *MockUserServiceClient_Expecter {
	return &MockUserServiceClient_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function with given fields: ctx, in, opts
func (_m *MockUserServiceClient) CreateUser(ctx context.Context, in *iamv1.CreateUserRequest, opts ...grpc.CallOption) (*iamv1.CreateUserResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *iamv1.CreateUserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *iamv1.CreateUserRequest, ...grpc.CallOption) (*iamv1.CreateUserResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *iamv1.CreateUserRequest, ...grpc.CallOption) *iamv1.CreateUserResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*iamv1.CreateUserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *iamv1.CreateUserRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserServiceClient_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockUserServiceClient_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - in *iamv1.CreateUserRequest
//   - opts ...grpc.CallOption
func (_e *MockUserServiceClient_Expecter) CreateUser(ctx interface{}, in interface{}, opts ...interface{}) *MockUserServiceClient_CreateUser_Call {
	return &MockUserServiceClient_CreateUser_Call{Call: _e.mock.On("CreateUser",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockUserServiceClient_CreateUser_Call) Run(run func(ctx context.Context, in *iamv1.CreateUserRequest, opts ...grpc.CallOption)) *MockUserServiceClient_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*iamv1.CreateUserRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockUserServiceClient_CreateUser_Call) Return(_a0 *iamv1.CreateUserResponse, _a1 error) *MockUserServiceClient_CreateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserServiceClient_CreateUser_Call) RunAndReturn(run func(context.Context, *iamv1.CreateUserRequest, ...grpc.CallOption) (*iamv1.CreateUserResponse, error)) *MockUserServiceClient_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function with given fields: ctx, in, opts
func (_m *MockUserServiceClient) GetUser(ctx context.Context, in *iamv1.GetUserRequest, opts ...grpc.CallOption) (*iamv1.GetUserResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *iamv1.GetUserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *iamv1.GetUserRequest, ...grpc.CallOption) (*iamv1.GetUserResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *iamv1.GetUserRequest, ...grpc.CallOption) *iamv1.GetUserResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*iamv1.GetUserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *iamv1.GetUserRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserServiceClient_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type MockUserServiceClient_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - in *iamv1.GetUserRequest
//   - opts ...grpc.CallOption
func (_e *MockUserServiceClient_Expecter) GetUser(ctx interface{}, in interface{}, opts ...interface{}) *MockUserServiceClient_GetUser_Call {
	return &MockUserServiceClient_GetUser_Call{Call: _e.mock.On("GetUser",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockUserServiceClient_GetUser_Call) Run(run func(ctx context.Context, in *iamv1.GetUserRequest, opts ...grpc.CallOption)) *MockUserServiceClient_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*iamv1.GetUserRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockUserServiceClient_GetUser_Call) Return(_a0 *iamv1.GetUserResponse, _a1 error) *MockUserServiceClient_GetUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserServiceClient_GetUser_Call) RunAndReturn(run func(context.Context, *iamv1.GetUserRequest, ...grpc.CallOption) (*iamv1.GetUserResponse, error)) *MockUserServiceClient_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// ListUsers provides a mock function with given fields: ctx, in, opts
func (_m *MockUserServiceClient) ListUsers(ctx context.Context, in *iamv1.ListUsersRequest, opts ...grpc.CallOption) (*iamv1.ListUsersResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListUsers")
	}

	var r0 *iamv1.ListUsersResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *iamv1.ListUsersRequest, ...grpc.CallOption) (*iamv1.ListUsersResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *iamv1.ListUsersRequest, ...grpc.CallOption) *iamv1.ListUsersResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*iamv1.ListUsersResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *iamv1.ListUsersRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserServiceClient_ListUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUsers'
type MockUserServiceClient_ListUsers_Call struct {
	*mock.Call
}

// ListUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - in *iamv1.ListUsersRequest
//   - opts ...grpc.CallOption
func (_e *MockUserServiceClient_Expecter) ListUsers(ctx interface{}, in interface{}, opts ...interface{}) *MockUserServiceClient_ListUsers_Call {
	return &MockUserServiceClient_ListUsers_Call{Call: _e.mock.On("ListUsers",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockUserServiceClient_ListUsers_Call) Run(run func(ctx context.Context, in *iamv1.ListUsersRequest, opts ...grpc.CallOption)) *MockUserServiceClient_ListUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*iamv1.ListUsersRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockUserServiceClient_ListUsers_Call) Return(_a0 *iamv1.ListUsersResponse, _a1 error) *MockUserServiceClient_ListUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserServiceClient_ListUsers_Call) RunAndReturn(run func(context.Context, *iamv1.ListUsersRequest, ...grpc.CallOption) (*iamv1.ListUsersResponse, error)) *MockUserServiceClient_ListUsers_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function with given fields: ctx, in, opts
func (_m *MockUserServiceClient) UpdateUser(ctx context.Context, in *iamv1.UpdateUserRequest, opts ...grpc.CallOption) (*iamv1.UpdateUserResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 *iamv1.UpdateUserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *iamv1.UpdateUserRequest, ...grpc.CallOption) (*iamv1.UpdateUserResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *iamv1.UpdateUserRequest, ...grpc.CallOption) *iamv1.UpdateUserResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*iamv1.UpdateUserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *iamv1.UpdateUserRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserServiceClient_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type MockUserServiceClient_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - in *iamv1.UpdateUserRequest
//   - opts ...grpc.CallOption
func (_e *MockUserServiceClient_Expecter) UpdateUser(ctx interface{}, in interface{}, opts ...interface{}) *MockUserServiceClient_UpdateUser_Call {
	return &MockUserServiceClient_UpdateUser_Call{Call: _e.mock.On("UpdateUser",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockUserServiceClient_UpdateUser_Call) Run(run func(ctx context.Context, in *iamv1.UpdateUserRequest, opts ...grpc.CallOption)) *MockUserServiceClient_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*iamv1.UpdateUserRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockUserServiceClient_UpdateUser_Call) Return(_a0 *iamv1.UpdateUserResponse, _a1 error) *MockUserServiceClient_UpdateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserServiceClient_UpdateUser_Call) RunAndReturn(run func(context.Context, *iamv1.UpdateUserRequest, ...grpc.CallOption) (*iamv1.UpdateUserResponse, error)) *MockUserServiceClient_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserServiceClient creates a new instance of MockUserServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserServiceClient {
	mock := &MockUserServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
