// Code generated by mockery v2.53.5. DO NOT EDIT.

package usecase

import (
	context "context"
	aiinferencev1 "secure-rag-platform/api/gen/go/aiinference/v1"

	mock "github.com/stretchr/testify/mock"
	grpc "google.golang.org/grpc"
)

// MockEmbeddingServiceClient is an autogenerated mock type for the EmbeddingServiceClient type
type MockEmbeddingServiceClient struct {
	mock.Mock
}

type MockEmbeddingServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmbeddingServiceClient) EXPECT() *MockEmbeddingServiceClient_Expecter {
	return &MockEmbeddingServiceClient_Expecter{mock: &_m.Mock}
}

// BatchEmbed provides a mock function with given fields: ctx, in, opts
func (_m *MockEmbeddingServiceClient) BatchEmbed(ctx context.Context, in *aiinferencev1.BatchEmbedRequest, opts ...grpc.CallOption) (*aiinferencev1.BatchEmbedResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for BatchEmbed")
	}

	var r0 *aiinferencev1.BatchEmbedResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *aiinferencev1.BatchEmbedRequest, ...grpc.CallOption) (*aiinferencev1.BatchEmbedResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *aiinferencev1.BatchEmbedRequest, ...grpc.CallOption) *aiinferencev1.BatchEmbedResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*aiinferencev1.BatchEmbedResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *aiinferencev1.BatchEmbedRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEmbeddingServiceClient_BatchEmbed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchEmbed'
type MockEmbeddingServiceClient_BatchEmbed_Call struct {
	*mock.Call
}

// BatchEmbed is a helper method to define mock.On call
//   - ctx context.Context
//   - in *aiinferencev1.BatchEmbedRequest
//   - opts ...grpc.CallOption
func (_e *MockEmbeddingServiceClient_Expecter) BatchEmbed(ctx interface{}, in interface{}, opts ...interface{}) *MockEmbeddingServiceClient_BatchEmbed_Call {
	return &MockEmbeddingServiceClient_BatchEmbed_Call{Call: _e.mock.On("BatchEmbed",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockEmbeddingServiceClient_BatchEmbed_Call) Run(run func(ctx context.Context, in *aiinferencev1.BatchEmbedRequest, opts ...grpc.CallOption)) *MockEmbeddingServiceClient_BatchEmbed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*aiinferencev1.BatchEmbedRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockEmbeddingServiceClient_BatchEmbed_Call) Return(_a0 *aiinferencev1.BatchEmbedResponse, _a1 error) *MockEmbeddingServiceClient_BatchEmbed_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEmbeddingServiceClient_BatchEmbed_Call) RunAndReturn(run func(context.Context, *aiinferencev1.BatchEmbedRequest, ...grpc.CallOption) (*aiinferencev1.BatchEmbedResponse, error)) *MockEmbeddingServiceClient_BatchEmbed_Call {
	_c.Call.Return(run)
	return _c
}

// Embed provides a mock function with given fields: ctx, in, opts
func (_m *MockEmbeddingServiceClient) Embed(ctx context.Context, in *aiinferencev1.EmbedRequest, opts ...grpc.CallOption) (*aiinferencev1.EmbedResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Embed")
	}

	var r0 *aiinferencev1.EmbedResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *aiinferencev1.EmbedRequest, ...grpc.CallOption) (*aiinferencev1.EmbedResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *aiinferencev1.EmbedRequest, ...grpc.CallOption) *aiinferencev1.EmbedResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*aiinferencev1.EmbedResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *aiinferencev1.EmbedRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEmbeddingServiceClient_Embed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Embed'
type MockEmbeddingServiceClient_Embed_Call struct {
	*mock.Call
}

// Embed is a helper method to define mock.On call
//   - ctx context.Context
//   - in *aiinferencev1.EmbedRequest
//   - opts ...grpc.CallOption
func (_e *MockEmbeddingServiceClient_Expecter) Embed(ctx interface{}, in interface{}, opts ...interface{}) *MockEmbeddingServiceClient_Embed_Call {
	return &MockEmbeddingServiceClient_Embed_Call{Call: _e.mock.On("Embed",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockEmbeddingServiceClient_Embed_Call) Run(run func(ctx context.Context, in *aiinferencev1.EmbedRequest, opts ...grpc.CallOption)) *MockEmbeddingServiceClient_Embed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*aiinferencev1.EmbedRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockEmbeddingServiceClient_Embed_Call) Return(_a0 *aiinferencev1.EmbedResponse, _a1 error) *MockEmbeddingServiceClient_Embed_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEmbeddingServiceClient_Embed_Call) RunAndReturn(run func(context.Context, *aiinferencev1.EmbedRequest, ...grpc.CallOption) (*aiinferencev1.EmbedResponse, error)) *MockEmbeddingServiceClient_Embed_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEmbeddingServiceClient creates a new instance of MockEmbeddingServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmbeddingServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmbeddingServiceClient {
	mock := &MockEmbeddingServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
