// Code generated by mockery v2.53.5. DO NOT EDIT.

package usecase

import (
	context "context"
	aiinferencev1 "secure-rag-platform/api/gen/go/aiinference/v1"

	mock "github.com/stretchr/testify/mock"
	grpc "google.golang.org/grpc"
)

// MockGenerationServiceClient is an autogenerated mock type for the GenerationServiceClient type
type MockGenerationServiceClient struct {
	mock.Mock
}

type MockGenerationServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGenerationServiceClient) EXPECT() *MockGenerationServiceClient_Expecter {
	return &MockGenerationServiceClient_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function with given fields: ctx, in, opts
func (_m *MockGenerationServiceClient) Generate(ctx context.Context, in *aiinferencev1.GenerateRequest, opts ...grpc.CallOption) (*aiinferencev1.GenerateResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 *aiinferencev1.GenerateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *aiinferencev1.GenerateRequest, ...grpc.CallOption) (*aiinferencev1.GenerateResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *aiinferencev1.GenerateRequest, ...grpc.CallOption) *aiinferencev1.GenerateResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*aiinferencev1.GenerateResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *aiinferencev1.GenerateRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGenerationServiceClient_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type MockGenerationServiceClient_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
//   - ctx context.Context
//   - in *aiinferencev1.GenerateRequest
//   - opts ...grpc.CallOption
func (_e *MockGenerationServiceClient_Expecter) Generate(ctx interface{}, in interface{}, opts ...interface{}) *MockGenerationServiceClient_Generate_Call {
	return &MockGenerationServiceClient_Generate_Call{Call: _e.mock.On("Generate",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockGenerationServiceClient_Generate_Call) Run(run func(ctx context.Context, in *aiinferencev1.GenerateRequest, opts ...grpc.CallOption)) *MockGenerationServiceClient_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*aiinferencev1.GenerateRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockGenerationServiceClient_Generate_Call) Return(_a0 *aiinferencev1.GenerateResponse, _a1 error) *MockGenerationServiceClient_Generate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGenerationServiceClient_Generate_Call) RunAndReturn(run func(context.Context, *aiinferencev1.GenerateRequest, ...grpc.CallOption) (*aiinferencev1.GenerateResponse, error)) *MockGenerationServiceClient_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// ListModels provides a mock function with given fields: ctx, in, opts
func (_m *MockGenerationServiceClient) ListModels(ctx context.Context, in *aiinferencev1.ListModelsRequest, opts ...grpc.CallOption) (*aiinferencev1.ListModelsResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListModels")
	}

	var r0 *aiinferencev1.ListModelsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *aiinferencev1.ListModelsRequest, ...grpc.CallOption) (*aiinferencev1.ListModelsResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *aiinferencev1.ListModelsRequest, ...grpc.CallOption) *aiinferencev1.ListModelsResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*aiinferencev1.ListModelsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *aiinferencev1.ListModelsRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGenerationServiceClient_ListModels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListModels'
type MockGenerationServiceClient_ListModels_Call struct {
	*mock.Call
}

// ListModels is a helper method to define mock.On call
//   - ctx context.Context
//   - in *aiinferencev1.ListModelsRequest
//   - opts ...grpc.CallOption
func (_e *MockGenerationServiceClient_Expecter) ListModels(ctx interface{}, in interface{}, opts ...interface{}) *MockGenerationServiceClient_ListModels_Call {
	return &MockGenerationServiceClient_ListModels_Call{Call: _e.mock.On("ListModels",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockGenerationServiceClient_ListModels_Call) Run(run func(ctx context.Context, in *aiinferencev1.ListModelsRequest, opts ...grpc.CallOption)) *MockGenerationServiceClient_ListModels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*aiinferencev1.ListModelsRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockGenerationServiceClient_ListModels_Call) Return(_a0 *aiinferencev1.ListModelsResponse, _a1 error) *MockGenerationServiceClient_ListModels_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGenerationServiceClient_ListModels_Call) RunAndReturn(run func(context.Context, *aiinferencev1.ListModelsRequest, ...grpc.CallOption) (*aiinferencev1.ListModelsResponse, error)) *MockGenerationServiceClient_ListModels_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGenerationServiceClient creates a new instance of MockGenerationServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGenerationServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGenerationServiceClient {
	mock := &MockGenerationServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
