// Code generated by mockery v2.53.5. DO NOT EDIT.

package usecase

import (
	context "context"
	repository "secure-rag-platform/services/rag/internal/repository"

	pgvector "github.com/pgvector/pgvector-go"
	mock "github.com/stretchr/testify/mock"
)

// MockRAGRepo is an autogenerated mock type for the RAGRepo type
type MockRAGRepo struct {
	mock.Mock
}

type MockRAGRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRAGRepo) EXPECT() *MockRAGRepo_Expecter {
	return &MockRAGRepo_Expecter{mock: &_m.Mock}
}

// DeleteChunks provides a mock function with given fields: _a0, _a1
func (_m *MockRAGRepo) DeleteChunks(_a0 context.Context, _a1 string) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for DeleteChunks")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRAGRepo_DeleteChunks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteChunks'
type MockRAGRepo_DeleteChunks_Call struct {
	*mock.Call
}

// DeleteChunks is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *MockRAGRepo_Expecter) DeleteChunks(_a0 interface{}, _a1 interface{}) *MockRAGRepo_DeleteChunks_Call {
	return &MockRAGRepo_DeleteChunks_Call{Call: _e.mock.On("DeleteChunks", _a0, _a1)}
}

func (_c *MockRAGRepo_DeleteChunks_Call) Run(run func(_a0 context.Context, _a1 string)) *MockRAGRepo_DeleteChunks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRAGRepo_DeleteChunks_Call) Return(_a0 error) *MockRAGRepo_DeleteChunks_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRAGRepo_DeleteChunks_Call) RunAndReturn(run func(context.Context, string) error) *MockRAGRepo_DeleteChunks_Call {
	_c.Call.Return(run)
	return _c
}

// InsertChunks provides a mock function with given fields: _a0, _a1
func (_m *MockRAGRepo) InsertChunks(_a0 context.Context, _a1 []repository.Chunk) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for InsertChunks")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []repository.Chunk) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRAGRepo_InsertChunks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertChunks'
type MockRAGRepo_InsertChunks_Call struct {
	*mock.Call
}

// InsertChunks is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 []repository.Chunk
func (_e *MockRAGRepo_Expecter) InsertChunks(_a0 interface{}, _a1 interface{}) *MockRAGRepo_InsertChunks_Call {
	return &MockRAGRepo_InsertChunks_Call{Call: _e.mock.On("InsertChunks", _a0, _a1)}
}

func (_c *MockRAGRepo_InsertChunks_Call) Run(run func(_a0 context.Context, _a1 []repository.Chunk)) *MockRAGRepo_InsertChunks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]repository.Chunk))
	})
	return _c
}

func (_c *MockRAGRepo_InsertChunks_Call) Return(_a0 error) *MockRAGRepo_InsertChunks_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRAGRepo_InsertChunks_Call) RunAndReturn(run func(context.Context, []repository.Chunk) error) *MockRAGRepo_InsertChunks_Call {
	_c.Call.Return(run)
	return _c
}

// SearchSimilar provides a mock function with given fields: _a0, _a1, _a2, _a3, _a4, _a5, _a6
func (_m *MockRAGRepo) SearchSimilar(_a0 context.Context, _a1 pgvector.Vector, _a2 string, _a3 int32, _a4 int32, _a5 int32, _a6 []string) ([]repository.ChunkMatch, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3, _a4, _a5, _a6)

	if len(ret) == 0 {
		panic("no return value specified for SearchSimilar")
	}

	var r0 []repository.ChunkMatch
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgvector.Vector, string, int32, int32, int32, []string) ([]repository.ChunkMatch, error)); ok {
		return rf(_a0, _a1, _a2, _a3, _a4, _a5, _a6)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgvector.Vector, string, int32, int32, int32, []string) []repository.ChunkMatch); ok {
		r0 = rf(_a0, _a1, _a2, _a3, _a4, _a5, _a6)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.ChunkMatch)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgvector.Vector, string, int32, int32, int32, []string) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3, _a4, _a5, _a6)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRAGRepo_SearchSimilar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchSimilar'
type MockRAGRepo_SearchSimilar_Call struct {
	*mock.Call
}

// SearchSimilar is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 pgvector.Vector
//   - _a2 string
//   - _a3 int32
//   - _a4 int32
//   - _a5 int32
//   - _a6 []string
func (_e *MockRAGRepo_Expecter) SearchSimilar(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}, _a4 interface{}, _a5 interface{}, _a6 interface{}) *MockRAGRepo_SearchSimilar_Call {
	return &MockRAGRepo_SearchSimilar_Call{Call: _e.mock.On("SearchSimilar", _a0, _a1, _a2, _a3, _a4, _a5, _a6)}
}

func (_c *MockRAGRepo_SearchSimilar_Call) Run(run func(_a0 context.Context, _a1 pgvector.Vector, _a2 string, _a3 int32, _a4 int32, _a5 int32, _a6 []string)) *MockRAGRepo_SearchSimilar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pgvector.Vector), args[2].(string), args[3].(int32), args[4].(int32), args[5].(int32), args[6].([]string))
	})
	return _c
}

func (_c *MockRAGRepo_SearchSimilar_Call) Return(_a0 []repository.ChunkMatch, _a1 error) *MockRAGRepo_SearchSimilar_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRAGRepo_SearchSimilar_Call) RunAndReturn(run func(context.Context, pgvector.Vector, string, int32, int32, int32, []string) ([]repository.ChunkMatch, error)) *MockRAGRepo_SearchSimilar_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRAGRepo creates a new instance of MockRAGRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRAGRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRAGRepo {
	mock := &MockRAGRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
