// Code generated by grpcstubgen. DO NOT EDIT.

package grpc

import (
	"context"
	pb "secure-rag-platform/services/iam/gen/v1"
	"secure-rag-platform/services/iam/internal/usecase"
)

func (s *RoleServiceServerImpl) AddUserRole(ctx context.Context, req *pb.AddUserRoleRequest) (*pb.AddUserRoleResponse, error) {
	principal, _, err := authenticate(s.svc, ctx)
	if err != nil {
		return nil, toGRPCError(err)
	}
	if !isAdmin(principal) {
		return nil, toGRPCError(usecase.ErrForbidden)
	}

	assignedBy := principal.UserID
	roles, ctxVer, err := s.svc.AddUserRole(ctx, req.GetUserId(), req.GetRoleCode(), &assignedBy)
	if err != nil {
		return nil, toGRPCError(err)
	}

	return &pb.AddUserRoleResponse{
		UserId: req.GetUserId(),
		Roles:  rolesToProto(roles),
		CtxVer: ctxVer,
	}, nil
}
