// Code generated by grpcstubgen. DO NOT EDIT.

package grpc

import (
	pb "secure-rag-platform/api/gen/go/iam/v1"
	"secure-rag-platform/services/iam/internal/usecase"
)

type AttributeServiceServerImpl struct {
	pb.UnimplementedAttributeServiceServer
	svc IAMUsecaseContract
}

func NewAttributeServiceServer(uc *usecase.IAMUsecase) *AttributeServiceServerImpl {
	return &AttributeServiceServerImpl{svc: usecaseOrNil(uc)}
}

var _ pb.AttributeServiceServer = (*AttributeServiceServerImpl)(nil)
