// Code generated by grpcstubgen. DO NOT EDIT.

package grpc

import (
	pb "secure-rag-platform/services/iam/gen/v1"
	"secure-rag-platform/services/iam/internal/usecase"
)

type AttributeServiceServerImpl struct {
	pb.UnimplementedAttributeServiceServer
	deps *serverDeps
}

func NewAttributeServiceServer(uc *usecase.IAMUsecase) *AttributeServiceServerImpl {
	return &AttributeServiceServerImpl{deps: newServerDeps(uc)}
}

var _ pb.AttributeServiceServer = (*AttributeServiceServerImpl)(nil)
