// Code generated by grpcstubgen. DO NOT EDIT.

package grpc

import (
	"context"
	pb "secure-rag-platform/services/iam/gen/v1"

	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

func (s *IAMServiceServerImpl) Authenticate(ctx context.Context, req *pb.AuthenticateRequest) (*pb.AuthenticateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Authenticate not implemented")
}
