// Code generated by grpcstubgen. DO NOT EDIT.

package grpc

import (
	pb "secure-rag-platform/api/gen/go/iam/v1"
	"secure-rag-platform/services/iam/internal/usecase"
)

type AuthServiceServerImpl struct {
	pb.UnimplementedAuthServiceServer
	svc IAMUsecaseContract
}

func NewAuthServiceServer(uc *usecase.IAMUsecase) *AuthServiceServerImpl {
	return &AuthServiceServerImpl{svc: usecaseOrNil(uc)}
}

var _ pb.AuthServiceServer = (*AuthServiceServerImpl)(nil)
