// Code generated by grpcstubgen. DO NOT EDIT.

package grpc

import (
	"context"
	pb "secure-rag-platform/api/gen/go/iam/v1"
	"secure-rag-platform/services/iam/internal/usecase"
)

func (s *UserServiceServerImpl) CreateUser(ctx context.Context, req *pb.CreateUserRequest) (*pb.CreateUserResponse, error) {
	principal, _, err := authenticate(s.svc, ctx)
	if err != nil {
		return nil, toGRPCError(err)
	}
	if !isAdmin(principal) {
		return nil, toGRPCError(usecase.ErrForbidden)
	}

	var isActive *bool
	if req.IsActive != nil {
		v := req.GetIsActive()
		isActive = &v
	}

	createdBy := principal.UserID
	user, err := s.svc.CreateUser(ctx, usecase.CreateUserInput{
		Login:      req.GetLogin(),
		Password:   req.GetPassword(),
		IsActive:   isActive,
		RoleCodes:  req.GetRoleCodes(),
		Attributes: structToMap(req.GetAttributes()),
		CreatedBy:  &createdBy,
	})
	if err != nil {
		return nil, toGRPCError(err)
	}

	return &pb.CreateUserResponse{User: userToProto(user)}, nil
}
