// Code generated by grpcstubgen. DO NOT EDIT.

package grpc

import (
	"context"
	pb "secure-rag-platform/services/iam/gen/v1"
	"secure-rag-platform/services/iam/internal/usecase"
)

func (s *AttributeServiceServerImpl) DeleteUserAttributeKey(ctx context.Context, req *pb.DeleteUserAttributeKeyRequest) (*pb.DeleteUserAttributeKeyResponse, error) {
	principal, _, err := authenticate(s.svc, ctx)
	if err != nil {
		return nil, toGRPCError(err)
	}

	targetUserID := req.GetUserId()
	if targetUserID == "" {
		targetUserID = principal.UserID
	}

	if !canAccessUser(principal, targetUserID) {
		return nil, toGRPCError(usecase.ErrForbidden)
	}

	updatedBy := principal.UserID
	attributes, ctxVer, err := s.svc.DeleteUserAttributeKey(ctx, targetUserID, req.GetKey(), &updatedBy)
	if err != nil {
		return nil, toGRPCError(err)
	}

	return &pb.DeleteUserAttributeKeyResponse{
		UserId:     targetUserID,
		Attributes: mapToStruct(attributes),
		CtxVer:     ctxVer,
	}, nil
}
