// Code generated by grpcstubgen. DO NOT EDIT.

package grpc

import (
	"context"
	"strings"

	pb "secure-rag-platform/services/iam/gen/v1"
)

func (s *InternalIAMServiceServerImpl) GetSubjectContext(ctx context.Context, req *pb.GetSubjectContextRequest) (*pb.GetSubjectContextResponse, error) {
	if err := s.deps.requireUC(); err != nil {
		return nil, err
	}

	targetUserID := strings.TrimSpace(req.GetUserId())
	if targetUserID == "" {
		principal, _, err := s.deps.authenticate(ctx)
		if err != nil {
			return nil, toGRPCError(err)
		}
		targetUserID = principal.UserID
	}

	subject, err := s.deps.uc.GetSubjectContextByUserID(ctx, targetUserID)
	if err != nil {
		return nil, toGRPCError(err)
	}

	return &pb.GetSubjectContextResponse{Subject: subjectToProto(subject)}, nil
}
