// Code generated by grpcstubgen. DO NOT EDIT.

package grpc

import (
	"context"
	pb "secure-rag-platform/services/iam/gen/v1"
	"secure-rag-platform/services/iam/internal/usecase"
)

func (s *UserServiceServerImpl) GetUser(ctx context.Context, req *pb.GetUserRequest) (*pb.GetUserResponse, error) {
	principal, _, err := s.deps.authenticate(ctx)
	if err != nil {
		return nil, toGRPCError(err)
	}

	targetUserID := req.GetUserId()
	if targetUserID == "" {
		targetUserID = principal.UserID
	}

	if !canAccessUser(principal, targetUserID) {
		return nil, toGRPCError(usecase.ErrForbidden)
	}

	user, err := s.deps.uc.GetUser(ctx, targetUserID)
	if err != nil {
		return nil, toGRPCError(err)
	}

	return &pb.GetUserResponse{User: userToProto(user)}, nil
}
