// Code generated by grpcstubgen. DO NOT EDIT.

package grpc

import (
	"context"
	pb "secure-rag-platform/services/iam/gen/v1"
	"secure-rag-platform/services/iam/internal/usecase"
)

func (s *RoleServiceServerImpl) GetUserRoles(ctx context.Context, req *pb.GetUserRolesRequest) (*pb.GetUserRolesResponse, error) {
	principal, _, err := authenticate(s.svc, ctx)
	if err != nil {
		return nil, toGRPCError(err)
	}

	targetUserID := req.GetUserId()
	if targetUserID == "" {
		targetUserID = principal.UserID
	}

	if !canAccessUser(principal, targetUserID) {
		return nil, toGRPCError(usecase.ErrForbidden)
	}

	roles, ctxVer, err := s.svc.GetUserRoles(ctx, targetUserID)
	if err != nil {
		return nil, toGRPCError(err)
	}

	return &pb.GetUserRolesResponse{
		UserId: targetUserID,
		Roles:  rolesToProto(roles),
		CtxVer: ctxVer,
	}, nil
}
