// Code generated by grpcstubgen. DO NOT EDIT.

package grpc

import (
	"context"
	pb "secure-rag-platform/api/gen/go/iam/v1"
)

func (s *AuthServiceServerImpl) GetMe(ctx context.Context, req *pb.GetMeRequest) (*pb.GetMeResponse, error) {
	if err := requireUC(s.svc); err != nil {
		return nil, err
	}

	accessToken, err := extractBearerToken(ctx)
	if err != nil {
		return nil, toGRPCError(err)
	}

	principal, _, err := s.svc.AuthenticateAccessToken(ctx, accessToken)
	if err != nil {
		return nil, toGRPCError(err)
	}

	me, err := s.svc.GetMe(ctx, principal)
	if err != nil {
		return nil, toGRPCError(err)
	}

	return &pb.GetMeResponse{Me: subjectToProto(me)}, nil
}
