// Code generated by grpcstubgen. DO NOT EDIT.

package grpc

import (
	"context"
	pb "secure-rag-platform/api/gen/go/iam/v1"
	"secure-rag-platform/services/iam/internal/usecase"
)

func (s *AttributeServiceServerImpl) GetUserAttributes(ctx context.Context, req *pb.GetUserAttributesRequest) (*pb.GetUserAttributesResponse, error) {
	principal, _, err := authenticate(s.svc, ctx)
	if err != nil {
		return nil, toGRPCError(err)
	}

	targetUserID := req.GetUserId()
	if targetUserID == "" {
		targetUserID = principal.UserID
	}

	if !canAccessUser(principal, targetUserID) {
		return nil, toGRPCError(usecase.ErrForbidden)
	}

	attributes, ctxVer, err := s.svc.GetUserAttributes(ctx, targetUserID)
	if err != nil {
		return nil, toGRPCError(err)
	}

	return &pb.GetUserAttributesResponse{
		UserId:     targetUserID,
		Attributes: mapToStruct(attributes),
		CtxVer:     ctxVer,
	}, nil
}
