// Code generated by grpcstubgen. DO NOT EDIT.

package grpc

import (
	"context"
	pb "secure-rag-platform/services/iam/gen/v1"
)

func (s *AuthServiceServerImpl) GetMe(ctx context.Context, req *pb.GetMeRequest) (*pb.GetMeResponse, error) {
	if err := s.deps.requireUC(); err != nil {
		return nil, err
	}

	accessToken, err := extractBearerToken(ctx)
	if err != nil {
		return nil, toGRPCError(err)
	}

	principal, _, err := s.deps.uc.AuthenticateAccessToken(ctx, accessToken)
	if err != nil {
		return nil, toGRPCError(err)
	}

	me, err := s.deps.uc.GetMe(ctx, principal)
	if err != nil {
		return nil, toGRPCError(err)
	}

	return &pb.GetMeResponse{Me: subjectToProto(me)}, nil
}
