// Code generated by grpcstubgen. DO NOT EDIT.

package grpc

import (
	"context"

	pb "secure-rag-platform/api/gen/go/iam/v1"
)

func (s *IAMServiceServerImpl) Health(ctx context.Context, req *pb.HealthRequest) (*pb.HealthResponse, error) {
	return &pb.HealthResponse{Status: "ok"}, nil
}
