// Code generated by mockery v2.53.5. DO NOT EDIT.

package grpc

import (
	context "context"
	model "secure-rag-platform/services/iam/internal/model"
	usecase "secure-rag-platform/services/iam/internal/usecase"

	mock "github.com/stretchr/testify/mock"
)

// MockIAMUsecase is an autogenerated mock type for the IAMUsecaseContract type
type MockIAMUsecase struct {
	mock.Mock
}

type MockIAMUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIAMUsecase) EXPECT() *MockIAMUsecase_Expecter {
	return &MockIAMUsecase_Expecter{mock: &_m.Mock}
}

// AddUserRole provides a mock function with given fields: ctx, userID, roleCode, assignedBy
func (_m *MockIAMUsecase) AddUserRole(ctx context.Context, userID string, roleCode string, assignedBy *string) ([]*model.Role, int64, error) {
	ret := _m.Called(ctx, userID, roleCode, assignedBy)

	if len(ret) == 0 {
		panic("no return value specified for AddUserRole")
	}

	var r0 []*model.Role
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *string) ([]*model.Role, int64, error)); ok {
		return rf(ctx, userID, roleCode, assignedBy)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *string) []*model.Role); ok {
		r0 = rf(ctx, userID, roleCode, assignedBy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *string) int64); ok {
		r1 = rf(ctx, userID, roleCode, assignedBy)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, *string) error); ok {
		r2 = rf(ctx, userID, roleCode, assignedBy)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockIAMUsecase_AddUserRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddUserRole'
type MockIAMUsecase_AddUserRole_Call struct {
	*mock.Call
}

// AddUserRole is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - roleCode string
//   - assignedBy *string
func (_e *MockIAMUsecase_Expecter) AddUserRole(ctx interface{}, userID interface{}, roleCode interface{}, assignedBy interface{}) *MockIAMUsecase_AddUserRole_Call {
	return &MockIAMUsecase_AddUserRole_Call{Call: _e.mock.On("AddUserRole", ctx, userID, roleCode, assignedBy)}
}

func (_c *MockIAMUsecase_AddUserRole_Call) Run(run func(ctx context.Context, userID string, roleCode string, assignedBy *string)) *MockIAMUsecase_AddUserRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*string))
	})
	return _c
}

func (_c *MockIAMUsecase_AddUserRole_Call) Return(_a0 []*model.Role, _a1 int64, _a2 error) *MockIAMUsecase_AddUserRole_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockIAMUsecase_AddUserRole_Call) RunAndReturn(run func(context.Context, string, string, *string) ([]*model.Role, int64, error)) *MockIAMUsecase_AddUserRole_Call {
	_c.Call.Return(run)
	return _c
}

// AuthenticateAccessToken provides a mock function with given fields: ctx, accessToken
func (_m *MockIAMUsecase) AuthenticateAccessToken(ctx context.Context, accessToken string) (*usecase.Principal, *model.SubjectContext, error) {
	ret := _m.Called(ctx, accessToken)

	if len(ret) == 0 {
		panic("no return value specified for AuthenticateAccessToken")
	}

	var r0 *usecase.Principal
	var r1 *model.SubjectContext
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*usecase.Principal, *model.SubjectContext, error)); ok {
		return rf(ctx, accessToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *usecase.Principal); ok {
		r0 = rf(ctx, accessToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*usecase.Principal)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) *model.SubjectContext); ok {
		r1 = rf(ctx, accessToken)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*model.SubjectContext)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, accessToken)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockIAMUsecase_AuthenticateAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthenticateAccessToken'
type MockIAMUsecase_AuthenticateAccessToken_Call struct {
	*mock.Call
}

// AuthenticateAccessToken is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
func (_e *MockIAMUsecase_Expecter) AuthenticateAccessToken(ctx interface{}, accessToken interface{}) *MockIAMUsecase_AuthenticateAccessToken_Call {
	return &MockIAMUsecase_AuthenticateAccessToken_Call{Call: _e.mock.On("AuthenticateAccessToken", ctx, accessToken)}
}

func (_c *MockIAMUsecase_AuthenticateAccessToken_Call) Run(run func(ctx context.Context, accessToken string)) *MockIAMUsecase_AuthenticateAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIAMUsecase_AuthenticateAccessToken_Call) Return(_a0 *usecase.Principal, _a1 *model.SubjectContext, _a2 error) *MockIAMUsecase_AuthenticateAccessToken_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockIAMUsecase_AuthenticateAccessToken_Call) RunAndReturn(run func(context.Context, string) (*usecase.Principal, *model.SubjectContext, error)) *MockIAMUsecase_AuthenticateAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function with given fields: ctx, input
func (_m *MockIAMUsecase) CreateUser(ctx context.Context, input usecase.CreateUserInput) (*model.UserView, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *model.UserView
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.CreateUserInput) (*model.UserView, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecase.CreateUserInput) *model.UserView); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserView)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecase.CreateUserInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAMUsecase_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockIAMUsecase_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - input usecase.CreateUserInput
func (_e *MockIAMUsecase_Expecter) CreateUser(ctx interface{}, input interface{}) *MockIAMUsecase_CreateUser_Call {
	return &MockIAMUsecase_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, input)}
}

func (_c *MockIAMUsecase_CreateUser_Call) Run(run func(ctx context.Context, input usecase.CreateUserInput)) *MockIAMUsecase_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecase.CreateUserInput))
	})
	return _c
}

func (_c *MockIAMUsecase_CreateUser_Call) Return(_a0 *model.UserView, _a1 error) *MockIAMUsecase_CreateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAMUsecase_CreateUser_Call) RunAndReturn(run func(context.Context, usecase.CreateUserInput) (*model.UserView, error)) *MockIAMUsecase_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUserAttributeKey provides a mock function with given fields: ctx, userID, key, updatedBy
func (_m *MockIAMUsecase) DeleteUserAttributeKey(ctx context.Context, userID string, key string, updatedBy *string) (map[string]interface{}, int64, error) {
	ret := _m.Called(ctx, userID, key, updatedBy)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserAttributeKey")
	}

	var r0 map[string]interface{}
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *string) (map[string]interface{}, int64, error)); ok {
		return rf(ctx, userID, key, updatedBy)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *string) map[string]interface{}); ok {
		r0 = rf(ctx, userID, key, updatedBy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *string) int64); ok {
		r1 = rf(ctx, userID, key, updatedBy)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, *string) error); ok {
		r2 = rf(ctx, userID, key, updatedBy)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockIAMUsecase_DeleteUserAttributeKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUserAttributeKey'
type MockIAMUsecase_DeleteUserAttributeKey_Call struct {
	*mock.Call
}

// DeleteUserAttributeKey is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - key string
//   - updatedBy *string
func (_e *MockIAMUsecase_Expecter) DeleteUserAttributeKey(ctx interface{}, userID interface{}, key interface{}, updatedBy interface{}) *MockIAMUsecase_DeleteUserAttributeKey_Call {
	return &MockIAMUsecase_DeleteUserAttributeKey_Call{Call: _e.mock.On("DeleteUserAttributeKey", ctx, userID, key, updatedBy)}
}

func (_c *MockIAMUsecase_DeleteUserAttributeKey_Call) Run(run func(ctx context.Context, userID string, key string, updatedBy *string)) *MockIAMUsecase_DeleteUserAttributeKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*string))
	})
	return _c
}

func (_c *MockIAMUsecase_DeleteUserAttributeKey_Call) Return(_a0 map[string]interface{}, _a1 int64, _a2 error) *MockIAMUsecase_DeleteUserAttributeKey_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockIAMUsecase_DeleteUserAttributeKey_Call) RunAndReturn(run func(context.Context, string, string, *string) (map[string]interface{}, int64, error)) *MockIAMUsecase_DeleteUserAttributeKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetMe provides a mock function with given fields: ctx, principal
func (_m *MockIAMUsecase) GetMe(ctx context.Context, principal *usecase.Principal) (*model.SubjectContext, error) {
	ret := _m.Called(ctx, principal)

	if len(ret) == 0 {
		panic("no return value specified for GetMe")
	}

	var r0 *model.SubjectContext
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *usecase.Principal) (*model.SubjectContext, error)); ok {
		return rf(ctx, principal)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *usecase.Principal) *model.SubjectContext); ok {
		r0 = rf(ctx, principal)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.SubjectContext)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *usecase.Principal) error); ok {
		r1 = rf(ctx, principal)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAMUsecase_GetMe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMe'
type MockIAMUsecase_GetMe_Call struct {
	*mock.Call
}

// GetMe is a helper method to define mock.On call
//   - ctx context.Context
//   - principal *usecase.Principal
func (_e *MockIAMUsecase_Expecter) GetMe(ctx interface{}, principal interface{}) *MockIAMUsecase_GetMe_Call {
	return &MockIAMUsecase_GetMe_Call{Call: _e.mock.On("GetMe", ctx, principal)}
}

func (_c *MockIAMUsecase_GetMe_Call) Run(run func(ctx context.Context, principal *usecase.Principal)) *MockIAMUsecase_GetMe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*usecase.Principal))
	})
	return _c
}

func (_c *MockIAMUsecase_GetMe_Call) Return(_a0 *model.SubjectContext, _a1 error) *MockIAMUsecase_GetMe_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAMUsecase_GetMe_Call) RunAndReturn(run func(context.Context, *usecase.Principal) (*model.SubjectContext, error)) *MockIAMUsecase_GetMe_Call {
	_c.Call.Return(run)
	return _c
}

// GetSubjectContextByUserID provides a mock function with given fields: ctx, userID
func (_m *MockIAMUsecase) GetSubjectContextByUserID(ctx context.Context, userID string) (*model.SubjectContext, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetSubjectContextByUserID")
	}

	var r0 *model.SubjectContext
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.SubjectContext, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.SubjectContext); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.SubjectContext)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAMUsecase_GetSubjectContextByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSubjectContextByUserID'
type MockIAMUsecase_GetSubjectContextByUserID_Call struct {
	*mock.Call
}

// GetSubjectContextByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockIAMUsecase_Expecter) GetSubjectContextByUserID(ctx interface{}, userID interface{}) *MockIAMUsecase_GetSubjectContextByUserID_Call {
	return &MockIAMUsecase_GetSubjectContextByUserID_Call{Call: _e.mock.On("GetSubjectContextByUserID", ctx, userID)}
}

func (_c *MockIAMUsecase_GetSubjectContextByUserID_Call) Run(run func(ctx context.Context, userID string)) *MockIAMUsecase_GetSubjectContextByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIAMUsecase_GetSubjectContextByUserID_Call) Return(_a0 *model.SubjectContext, _a1 error) *MockIAMUsecase_GetSubjectContextByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAMUsecase_GetSubjectContextByUserID_Call) RunAndReturn(run func(context.Context, string) (*model.SubjectContext, error)) *MockIAMUsecase_GetSubjectContextByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function with given fields: ctx, userID
func (_m *MockIAMUsecase) GetUser(ctx context.Context, userID string) (*model.UserView, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *model.UserView
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.UserView, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.UserView); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserView)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAMUsecase_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type MockIAMUsecase_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockIAMUsecase_Expecter) GetUser(ctx interface{}, userID interface{}) *MockIAMUsecase_GetUser_Call {
	return &MockIAMUsecase_GetUser_Call{Call: _e.mock.On("GetUser", ctx, userID)}
}

func (_c *MockIAMUsecase_GetUser_Call) Run(run func(ctx context.Context, userID string)) *MockIAMUsecase_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIAMUsecase_GetUser_Call) Return(_a0 *model.UserView, _a1 error) *MockIAMUsecase_GetUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAMUsecase_GetUser_Call) RunAndReturn(run func(context.Context, string) (*model.UserView, error)) *MockIAMUsecase_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserAttributes provides a mock function with given fields: ctx, userID
func (_m *MockIAMUsecase) GetUserAttributes(ctx context.Context, userID string) (map[string]interface{}, int64, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserAttributes")
	}

	var r0 map[string]interface{}
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (map[string]interface{}, int64, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) map[string]interface{}); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) int64); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, userID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockIAMUsecase_GetUserAttributes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserAttributes'
type MockIAMUsecase_GetUserAttributes_Call struct {
	*mock.Call
}

// GetUserAttributes is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockIAMUsecase_Expecter) GetUserAttributes(ctx interface{}, userID interface{}) *MockIAMUsecase_GetUserAttributes_Call {
	return &MockIAMUsecase_GetUserAttributes_Call{Call: _e.mock.On("GetUserAttributes", ctx, userID)}
}

func (_c *MockIAMUsecase_GetUserAttributes_Call) Run(run func(ctx context.Context, userID string)) *MockIAMUsecase_GetUserAttributes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIAMUsecase_GetUserAttributes_Call) Return(_a0 map[string]interface{}, _a1 int64, _a2 error) *MockIAMUsecase_GetUserAttributes_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockIAMUsecase_GetUserAttributes_Call) RunAndReturn(run func(context.Context, string) (map[string]interface{}, int64, error)) *MockIAMUsecase_GetUserAttributes_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserRoles provides a mock function with given fields: ctx, userID
func (_m *MockIAMUsecase) GetUserRoles(ctx context.Context, userID string) ([]*model.Role, int64, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserRoles")
	}

	var r0 []*model.Role
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*model.Role, int64, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*model.Role); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) int64); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, userID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockIAMUsecase_GetUserRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserRoles'
type MockIAMUsecase_GetUserRoles_Call struct {
	*mock.Call
}

// GetUserRoles is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockIAMUsecase_Expecter) GetUserRoles(ctx interface{}, userID interface{}) *MockIAMUsecase_GetUserRoles_Call {
	return &MockIAMUsecase_GetUserRoles_Call{Call: _e.mock.On("GetUserRoles", ctx, userID)}
}

func (_c *MockIAMUsecase_GetUserRoles_Call) Run(run func(ctx context.Context, userID string)) *MockIAMUsecase_GetUserRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIAMUsecase_GetUserRoles_Call) Return(_a0 []*model.Role, _a1 int64, _a2 error) *MockIAMUsecase_GetUserRoles_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockIAMUsecase_GetUserRoles_Call) RunAndReturn(run func(context.Context, string) ([]*model.Role, int64, error)) *MockIAMUsecase_GetUserRoles_Call {
	_c.Call.Return(run)
	return _c
}

// ListRoles provides a mock function with given fields: ctx
func (_m *MockIAMUsecase) ListRoles(ctx context.Context) ([]*model.Role, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListRoles")
	}

	var r0 []*model.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*model.Role, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*model.Role); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAMUsecase_ListRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRoles'
type MockIAMUsecase_ListRoles_Call struct {
	*mock.Call
}

// ListRoles is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIAMUsecase_Expecter) ListRoles(ctx interface{}) *MockIAMUsecase_ListRoles_Call {
	return &MockIAMUsecase_ListRoles_Call{Call: _e.mock.On("ListRoles", ctx)}
}

func (_c *MockIAMUsecase_ListRoles_Call) Run(run func(ctx context.Context)) *MockIAMUsecase_ListRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIAMUsecase_ListRoles_Call) Return(_a0 []*model.Role, _a1 error) *MockIAMUsecase_ListRoles_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAMUsecase_ListRoles_Call) RunAndReturn(run func(context.Context) ([]*model.Role, error)) *MockIAMUsecase_ListRoles_Call {
	_c.Call.Return(run)
	return _c
}

// ListUserSessions provides a mock function with given fields: ctx, principal, userID
func (_m *MockIAMUsecase) ListUserSessions(ctx context.Context, principal *usecase.Principal, userID string) ([]*model.UserSession, string, error) {
	ret := _m.Called(ctx, principal, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListUserSessions")
	}

	var r0 []*model.UserSession
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *usecase.Principal, string) ([]*model.UserSession, string, error)); ok {
		return rf(ctx, principal, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *usecase.Principal, string) []*model.UserSession); ok {
		r0 = rf(ctx, principal, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.UserSession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *usecase.Principal, string) string); ok {
		r1 = rf(ctx, principal, userID)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *usecase.Principal, string) error); ok {
		r2 = rf(ctx, principal, userID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockIAMUsecase_ListUserSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUserSessions'
type MockIAMUsecase_ListUserSessions_Call struct {
	*mock.Call
}

// ListUserSessions is a helper method to define mock.On call
//   - ctx context.Context
//   - principal *usecase.Principal
//   - userID string
func (_e *MockIAMUsecase_Expecter) ListUserSessions(ctx interface{}, principal interface{}, userID interface{}) *MockIAMUsecase_ListUserSessions_Call {
	return &MockIAMUsecase_ListUserSessions_Call{Call: _e.mock.On("ListUserSessions", ctx, principal, userID)}
}

func (_c *MockIAMUsecase_ListUserSessions_Call) Run(run func(ctx context.Context, principal *usecase.Principal, userID string)) *MockIAMUsecase_ListUserSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*usecase.Principal), args[2].(string))
	})
	return _c
}

func (_c *MockIAMUsecase_ListUserSessions_Call) Return(_a0 []*model.UserSession, _a1 string, _a2 error) *MockIAMUsecase_ListUserSessions_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockIAMUsecase_ListUserSessions_Call) RunAndReturn(run func(context.Context, *usecase.Principal, string) ([]*model.UserSession, string, error)) *MockIAMUsecase_ListUserSessions_Call {
	_c.Call.Return(run)
	return _c
}

// ListUsers provides a mock function with given fields: ctx
func (_m *MockIAMUsecase) ListUsers(ctx context.Context) ([]*model.UserView, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListUsers")
	}

	var r0 []*model.UserView
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*model.UserView, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*model.UserView); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.UserView)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAMUsecase_ListUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUsers'
type MockIAMUsecase_ListUsers_Call struct {
	*mock.Call
}

// ListUsers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIAMUsecase_Expecter) ListUsers(ctx interface{}) *MockIAMUsecase_ListUsers_Call {
	return &MockIAMUsecase_ListUsers_Call{Call: _e.mock.On("ListUsers", ctx)}
}

func (_c *MockIAMUsecase_ListUsers_Call) Run(run func(ctx context.Context)) *MockIAMUsecase_ListUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIAMUsecase_ListUsers_Call) Return(_a0 []*model.UserView, _a1 error) *MockIAMUsecase_ListUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAMUsecase_ListUsers_Call) RunAndReturn(run func(context.Context) ([]*model.UserView, error)) *MockIAMUsecase_ListUsers_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function with given fields: ctx, input
func (_m *MockIAMUsecase) Login(ctx context.Context, input usecase.LoginInput) (*usecase.TokenPair, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *usecase.TokenPair
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.LoginInput) (*usecase.TokenPair, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecase.LoginInput) *usecase.TokenPair); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*usecase.TokenPair)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecase.LoginInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAMUsecase_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockIAMUsecase_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - input usecase.LoginInput
func (_e *MockIAMUsecase_Expecter) Login(ctx interface{}, input interface{}) *MockIAMUsecase_Login_Call {
	return &MockIAMUsecase_Login_Call{Call: _e.mock.On("Login", ctx, input)}
}

func (_c *MockIAMUsecase_Login_Call) Run(run func(ctx context.Context, input usecase.LoginInput)) *MockIAMUsecase_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecase.LoginInput))
	})
	return _c
}

func (_c *MockIAMUsecase_Login_Call) Return(_a0 *usecase.TokenPair, _a1 error) *MockIAMUsecase_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAMUsecase_Login_Call) RunAndReturn(run func(context.Context, usecase.LoginInput) (*usecase.TokenPair, error)) *MockIAMUsecase_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function with given fields: ctx, principal, sessionID
func (_m *MockIAMUsecase) Logout(ctx context.Context, principal *usecase.Principal, sessionID string) (bool, error) {
	ret := _m.Called(ctx, principal, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *usecase.Principal, string) (bool, error)); ok {
		return rf(ctx, principal, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *usecase.Principal, string) bool); ok {
		r0 = rf(ctx, principal, sessionID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *usecase.Principal, string) error); ok {
		r1 = rf(ctx, principal, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAMUsecase_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MockIAMUsecase_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - principal *usecase.Principal
//   - sessionID string
func (_e *MockIAMUsecase_Expecter) Logout(ctx interface{}, principal interface{}, sessionID interface{}) *MockIAMUsecase_Logout_Call {
	return &MockIAMUsecase_Logout_Call{Call: _e.mock.On("Logout", ctx, principal, sessionID)}
}

func (_c *MockIAMUsecase_Logout_Call) Run(run func(ctx context.Context, principal *usecase.Principal, sessionID string)) *MockIAMUsecase_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*usecase.Principal), args[2].(string))
	})
	return _c
}

func (_c *MockIAMUsecase_Logout_Call) Return(_a0 bool, _a1 error) *MockIAMUsecase_Logout_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAMUsecase_Logout_Call) RunAndReturn(run func(context.Context, *usecase.Principal, string) (bool, error)) *MockIAMUsecase_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// LogoutAll provides a mock function with given fields: ctx, principal, userID
func (_m *MockIAMUsecase) LogoutAll(ctx context.Context, principal *usecase.Principal, userID string) (*usecase.LogoutAllResult, error) {
	ret := _m.Called(ctx, principal, userID)

	if len(ret) == 0 {
		panic("no return value specified for LogoutAll")
	}

	var r0 *usecase.LogoutAllResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *usecase.Principal, string) (*usecase.LogoutAllResult, error)); ok {
		return rf(ctx, principal, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *usecase.Principal, string) *usecase.LogoutAllResult); ok {
		r0 = rf(ctx, principal, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*usecase.LogoutAllResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *usecase.Principal, string) error); ok {
		r1 = rf(ctx, principal, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAMUsecase_LogoutAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogoutAll'
type MockIAMUsecase_LogoutAll_Call struct {
	*mock.Call
}

// LogoutAll is a helper method to define mock.On call
//   - ctx context.Context
//   - principal *usecase.Principal
//   - userID string
func (_e *MockIAMUsecase_Expecter) LogoutAll(ctx interface{}, principal interface{}, userID interface{}) *MockIAMUsecase_LogoutAll_Call {
	return &MockIAMUsecase_LogoutAll_Call{Call: _e.mock.On("LogoutAll", ctx, principal, userID)}
}

func (_c *MockIAMUsecase_LogoutAll_Call) Run(run func(ctx context.Context, principal *usecase.Principal, userID string)) *MockIAMUsecase_LogoutAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*usecase.Principal), args[2].(string))
	})
	return _c
}

func (_c *MockIAMUsecase_LogoutAll_Call) Return(_a0 *usecase.LogoutAllResult, _a1 error) *MockIAMUsecase_LogoutAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAMUsecase_LogoutAll_Call) RunAndReturn(run func(context.Context, *usecase.Principal, string) (*usecase.LogoutAllResult, error)) *MockIAMUsecase_LogoutAll_Call {
	_c.Call.Return(run)
	return _c
}

// PatchUserAttributes provides a mock function with given fields: ctx, userID, patch, updatedBy
func (_m *MockIAMUsecase) PatchUserAttributes(ctx context.Context, userID string, patch map[string]interface{}, updatedBy *string) (map[string]interface{}, int64, error) {
	ret := _m.Called(ctx, userID, patch, updatedBy)

	if len(ret) == 0 {
		panic("no return value specified for PatchUserAttributes")
	}

	var r0 map[string]interface{}
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}, *string) (map[string]interface{}, int64, error)); ok {
		return rf(ctx, userID, patch, updatedBy)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}, *string) map[string]interface{}); ok {
		r0 = rf(ctx, userID, patch, updatedBy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, map[string]interface{}, *string) int64); ok {
		r1 = rf(ctx, userID, patch, updatedBy)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, map[string]interface{}, *string) error); ok {
		r2 = rf(ctx, userID, patch, updatedBy)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockIAMUsecase_PatchUserAttributes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PatchUserAttributes'
type MockIAMUsecase_PatchUserAttributes_Call struct {
	*mock.Call
}

// PatchUserAttributes is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - patch map[string]interface{}
//   - updatedBy *string
func (_e *MockIAMUsecase_Expecter) PatchUserAttributes(ctx interface{}, userID interface{}, patch interface{}, updatedBy interface{}) *MockIAMUsecase_PatchUserAttributes_Call {
	return &MockIAMUsecase_PatchUserAttributes_Call{Call: _e.mock.On("PatchUserAttributes", ctx, userID, patch, updatedBy)}
}

func (_c *MockIAMUsecase_PatchUserAttributes_Call) Run(run func(ctx context.Context, userID string, patch map[string]interface{}, updatedBy *string)) *MockIAMUsecase_PatchUserAttributes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(map[string]interface{}), args[3].(*string))
	})
	return _c
}

func (_c *MockIAMUsecase_PatchUserAttributes_Call) Return(_a0 map[string]interface{}, _a1 int64, _a2 error) *MockIAMUsecase_PatchUserAttributes_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockIAMUsecase_PatchUserAttributes_Call) RunAndReturn(run func(context.Context, string, map[string]interface{}, *string) (map[string]interface{}, int64, error)) *MockIAMUsecase_PatchUserAttributes_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshToken provides a mock function with given fields: ctx, input
func (_m *MockIAMUsecase) RefreshToken(ctx context.Context, input usecase.RefreshTokenInput) (*usecase.TokenPair, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}

	var r0 *usecase.TokenPair
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.RefreshTokenInput) (*usecase.TokenPair, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecase.RefreshTokenInput) *usecase.TokenPair); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*usecase.TokenPair)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecase.RefreshTokenInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAMUsecase_RefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshToken'
type MockIAMUsecase_RefreshToken_Call struct {
	*mock.Call
}

// RefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - input usecase.RefreshTokenInput
func (_e *MockIAMUsecase_Expecter) RefreshToken(ctx interface{}, input interface{}) *MockIAMUsecase_RefreshToken_Call {
	return &MockIAMUsecase_RefreshToken_Call{Call: _e.mock.On("RefreshToken", ctx, input)}
}

func (_c *MockIAMUsecase_RefreshToken_Call) Run(run func(ctx context.Context, input usecase.RefreshTokenInput)) *MockIAMUsecase_RefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecase.RefreshTokenInput))
	})
	return _c
}

func (_c *MockIAMUsecase_RefreshToken_Call) Return(_a0 *usecase.TokenPair, _a1 error) *MockIAMUsecase_RefreshToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAMUsecase_RefreshToken_Call) RunAndReturn(run func(context.Context, usecase.RefreshTokenInput) (*usecase.TokenPair, error)) *MockIAMUsecase_RefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveUserRole provides a mock function with given fields: ctx, userID, roleCode
func (_m *MockIAMUsecase) RemoveUserRole(ctx context.Context, userID string, roleCode string) ([]*model.Role, int64, error) {
	ret := _m.Called(ctx, userID, roleCode)

	if len(ret) == 0 {
		panic("no return value specified for RemoveUserRole")
	}

	var r0 []*model.Role
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]*model.Role, int64, error)); ok {
		return rf(ctx, userID, roleCode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []*model.Role); ok {
		r0 = rf(ctx, userID, roleCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) int64); ok {
		r1 = rf(ctx, userID, roleCode)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = rf(ctx, userID, roleCode)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockIAMUsecase_RemoveUserRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveUserRole'
type MockIAMUsecase_RemoveUserRole_Call struct {
	*mock.Call
}

// RemoveUserRole is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - roleCode string
func (_e *MockIAMUsecase_Expecter) RemoveUserRole(ctx interface{}, userID interface{}, roleCode interface{}) *MockIAMUsecase_RemoveUserRole_Call {
	return &MockIAMUsecase_RemoveUserRole_Call{Call: _e.mock.On("RemoveUserRole", ctx, userID, roleCode)}
}

func (_c *MockIAMUsecase_RemoveUserRole_Call) Run(run func(ctx context.Context, userID string, roleCode string)) *MockIAMUsecase_RemoveUserRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockIAMUsecase_RemoveUserRole_Call) Return(_a0 []*model.Role, _a1 int64, _a2 error) *MockIAMUsecase_RemoveUserRole_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockIAMUsecase_RemoveUserRole_Call) RunAndReturn(run func(context.Context, string, string) ([]*model.Role, int64, error)) *MockIAMUsecase_RemoveUserRole_Call {
	_c.Call.Return(run)
	return _c
}

// ReplaceUserAttributes provides a mock function with given fields: ctx, userID, attrs, updatedBy
func (_m *MockIAMUsecase) ReplaceUserAttributes(ctx context.Context, userID string, attrs map[string]interface{}, updatedBy *string) (map[string]interface{}, int64, error) {
	ret := _m.Called(ctx, userID, attrs, updatedBy)

	if len(ret) == 0 {
		panic("no return value specified for ReplaceUserAttributes")
	}

	var r0 map[string]interface{}
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}, *string) (map[string]interface{}, int64, error)); ok {
		return rf(ctx, userID, attrs, updatedBy)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}, *string) map[string]interface{}); ok {
		r0 = rf(ctx, userID, attrs, updatedBy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, map[string]interface{}, *string) int64); ok {
		r1 = rf(ctx, userID, attrs, updatedBy)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, map[string]interface{}, *string) error); ok {
		r2 = rf(ctx, userID, attrs, updatedBy)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockIAMUsecase_ReplaceUserAttributes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplaceUserAttributes'
type MockIAMUsecase_ReplaceUserAttributes_Call struct {
	*mock.Call
}

// ReplaceUserAttributes is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - attrs map[string]interface{}
//   - updatedBy *string
func (_e *MockIAMUsecase_Expecter) ReplaceUserAttributes(ctx interface{}, userID interface{}, attrs interface{}, updatedBy interface{}) *MockIAMUsecase_ReplaceUserAttributes_Call {
	return &MockIAMUsecase_ReplaceUserAttributes_Call{Call: _e.mock.On("ReplaceUserAttributes", ctx, userID, attrs, updatedBy)}
}

func (_c *MockIAMUsecase_ReplaceUserAttributes_Call) Run(run func(ctx context.Context, userID string, attrs map[string]interface{}, updatedBy *string)) *MockIAMUsecase_ReplaceUserAttributes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(map[string]interface{}), args[3].(*string))
	})
	return _c
}

func (_c *MockIAMUsecase_ReplaceUserAttributes_Call) Return(_a0 map[string]interface{}, _a1 int64, _a2 error) *MockIAMUsecase_ReplaceUserAttributes_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockIAMUsecase_ReplaceUserAttributes_Call) RunAndReturn(run func(context.Context, string, map[string]interface{}, *string) (map[string]interface{}, int64, error)) *MockIAMUsecase_ReplaceUserAttributes_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAllUserSessions provides a mock function with given fields: ctx, principal, userID
func (_m *MockIAMUsecase) RevokeAllUserSessions(ctx context.Context, principal *usecase.Principal, userID string) (*usecase.LogoutAllResult, error) {
	ret := _m.Called(ctx, principal, userID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllUserSessions")
	}

	var r0 *usecase.LogoutAllResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *usecase.Principal, string) (*usecase.LogoutAllResult, error)); ok {
		return rf(ctx, principal, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *usecase.Principal, string) *usecase.LogoutAllResult); ok {
		r0 = rf(ctx, principal, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*usecase.LogoutAllResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *usecase.Principal, string) error); ok {
		r1 = rf(ctx, principal, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAMUsecase_RevokeAllUserSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAllUserSessions'
type MockIAMUsecase_RevokeAllUserSessions_Call struct {
	*mock.Call
}

// RevokeAllUserSessions is a helper method to define mock.On call
//   - ctx context.Context
//   - principal *usecase.Principal
//   - userID string
func (_e *MockIAMUsecase_Expecter) RevokeAllUserSessions(ctx interface{}, principal interface{}, userID interface{}) *MockIAMUsecase_RevokeAllUserSessions_Call {
	return &MockIAMUsecase_RevokeAllUserSessions_Call{Call: _e.mock.On("RevokeAllUserSessions", ctx, principal, userID)}
}

func (_c *MockIAMUsecase_RevokeAllUserSessions_Call) Run(run func(ctx context.Context, principal *usecase.Principal, userID string)) *MockIAMUsecase_RevokeAllUserSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*usecase.Principal), args[2].(string))
	})
	return _c
}

func (_c *MockIAMUsecase_RevokeAllUserSessions_Call) Return(_a0 *usecase.LogoutAllResult, _a1 error) *MockIAMUsecase_RevokeAllUserSessions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAMUsecase_RevokeAllUserSessions_Call) RunAndReturn(run func(context.Context, *usecase.Principal, string) (*usecase.LogoutAllResult, error)) *MockIAMUsecase_RevokeAllUserSessions_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeSession provides a mock function with given fields: ctx, principal, sessionID
func (_m *MockIAMUsecase) RevokeSession(ctx context.Context, principal *usecase.Principal, sessionID string) (bool, error) {
	ret := _m.Called(ctx, principal, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeSession")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *usecase.Principal, string) (bool, error)); ok {
		return rf(ctx, principal, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *usecase.Principal, string) bool); ok {
		r0 = rf(ctx, principal, sessionID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *usecase.Principal, string) error); ok {
		r1 = rf(ctx, principal, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAMUsecase_RevokeSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeSession'
type MockIAMUsecase_RevokeSession_Call struct {
	*mock.Call
}

// RevokeSession is a helper method to define mock.On call
//   - ctx context.Context
//   - principal *usecase.Principal
//   - sessionID string
func (_e *MockIAMUsecase_Expecter) RevokeSession(ctx interface{}, principal interface{}, sessionID interface{}) *MockIAMUsecase_RevokeSession_Call {
	return &MockIAMUsecase_RevokeSession_Call{Call: _e.mock.On("RevokeSession", ctx, principal, sessionID)}
}

func (_c *MockIAMUsecase_RevokeSession_Call) Run(run func(ctx context.Context, principal *usecase.Principal, sessionID string)) *MockIAMUsecase_RevokeSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*usecase.Principal), args[2].(string))
	})
	return _c
}

func (_c *MockIAMUsecase_RevokeSession_Call) Return(_a0 bool, _a1 error) *MockIAMUsecase_RevokeSession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAMUsecase_RevokeSession_Call) RunAndReturn(run func(context.Context, *usecase.Principal, string) (bool, error)) *MockIAMUsecase_RevokeSession_Call {
	_c.Call.Return(run)
	return _c
}

// SetUserRoles provides a mock function with given fields: ctx, userID, roleCodes, assignedBy
func (_m *MockIAMUsecase) SetUserRoles(ctx context.Context, userID string, roleCodes []string, assignedBy *string) ([]*model.Role, int64, error) {
	ret := _m.Called(ctx, userID, roleCodes, assignedBy)

	if len(ret) == 0 {
		panic("no return value specified for SetUserRoles")
	}

	var r0 []*model.Role
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string, *string) ([]*model.Role, int64, error)); ok {
		return rf(ctx, userID, roleCodes, assignedBy)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []string, *string) []*model.Role); ok {
		r0 = rf(ctx, userID, roleCodes, assignedBy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []string, *string) int64); ok {
		r1 = rf(ctx, userID, roleCodes, assignedBy)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, []string, *string) error); ok {
		r2 = rf(ctx, userID, roleCodes, assignedBy)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockIAMUsecase_SetUserRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetUserRoles'
type MockIAMUsecase_SetUserRoles_Call struct {
	*mock.Call
}

// SetUserRoles is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - roleCodes []string
//   - assignedBy *string
func (_e *MockIAMUsecase_Expecter) SetUserRoles(ctx interface{}, userID interface{}, roleCodes interface{}, assignedBy interface{}) *MockIAMUsecase_SetUserRoles_Call {
	return &MockIAMUsecase_SetUserRoles_Call{Call: _e.mock.On("SetUserRoles", ctx, userID, roleCodes, assignedBy)}
}

func (_c *MockIAMUsecase_SetUserRoles_Call) Run(run func(ctx context.Context, userID string, roleCodes []string, assignedBy *string)) *MockIAMUsecase_SetUserRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]string), args[3].(*string))
	})
	return _c
}

func (_c *MockIAMUsecase_SetUserRoles_Call) Return(_a0 []*model.Role, _a1 int64, _a2 error) *MockIAMUsecase_SetUserRoles_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockIAMUsecase_SetUserRoles_Call) RunAndReturn(run func(context.Context, string, []string, *string) ([]*model.Role, int64, error)) *MockIAMUsecase_SetUserRoles_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function with given fields: ctx, input
func (_m *MockIAMUsecase) UpdateUser(ctx context.Context, input usecase.UpdateUserInput) (*model.UserView, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 *model.UserView
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.UpdateUserInput) (*model.UserView, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecase.UpdateUserInput) *model.UserView); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserView)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecase.UpdateUserInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAMUsecase_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type MockIAMUsecase_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - input usecase.UpdateUserInput
func (_e *MockIAMUsecase_Expecter) UpdateUser(ctx interface{}, input interface{}) *MockIAMUsecase_UpdateUser_Call {
	return &MockIAMUsecase_UpdateUser_Call{Call: _e.mock.On("UpdateUser", ctx, input)}
}

func (_c *MockIAMUsecase_UpdateUser_Call) Run(run func(ctx context.Context, input usecase.UpdateUserInput)) *MockIAMUsecase_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecase.UpdateUserInput))
	})
	return _c
}

func (_c *MockIAMUsecase_UpdateUser_Call) Return(_a0 *model.UserView, _a1 error) *MockIAMUsecase_UpdateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAMUsecase_UpdateUser_Call) RunAndReturn(run func(context.Context, usecase.UpdateUserInput) (*model.UserView, error)) *MockIAMUsecase_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateAccessToken provides a mock function with given fields: ctx, accessToken
func (_m *MockIAMUsecase) ValidateAccessToken(ctx context.Context, accessToken string) (*usecase.ValidateTokenResult, error) {
	ret := _m.Called(ctx, accessToken)

	if len(ret) == 0 {
		panic("no return value specified for ValidateAccessToken")
	}

	var r0 *usecase.ValidateTokenResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*usecase.ValidateTokenResult, error)); ok {
		return rf(ctx, accessToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *usecase.ValidateTokenResult); ok {
		r0 = rf(ctx, accessToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*usecase.ValidateTokenResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, accessToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAMUsecase_ValidateAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateAccessToken'
type MockIAMUsecase_ValidateAccessToken_Call struct {
	*mock.Call
}

// ValidateAccessToken is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
func (_e *MockIAMUsecase_Expecter) ValidateAccessToken(ctx interface{}, accessToken interface{}) *MockIAMUsecase_ValidateAccessToken_Call {
	return &MockIAMUsecase_ValidateAccessToken_Call{Call: _e.mock.On("ValidateAccessToken", ctx, accessToken)}
}

func (_c *MockIAMUsecase_ValidateAccessToken_Call) Run(run func(ctx context.Context, accessToken string)) *MockIAMUsecase_ValidateAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIAMUsecase_ValidateAccessToken_Call) Return(_a0 *usecase.ValidateTokenResult, _a1 error) *MockIAMUsecase_ValidateAccessToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAMUsecase_ValidateAccessToken_Call) RunAndReturn(run func(context.Context, string) (*usecase.ValidateTokenResult, error)) *MockIAMUsecase_ValidateAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIAMUsecase creates a new instance of MockIAMUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIAMUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIAMUsecase {
	mock := &MockIAMUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
