// Code generated by grpcstubgen. DO NOT EDIT.

package grpc

import (
	pb "secure-rag-platform/services/iam/gen/v1"
)

type IAMServiceServerImpl struct {
	pb.UnimplementedIAMServiceServer
}

var _ pb.IAMServiceServer = (*IAMServiceServerImpl)(nil)
