// Code generated by grpcstubgen. DO NOT EDIT.

package grpc

import (
	pb "secure-rag-platform/api/gen/go/iam/v1"
	"secure-rag-platform/services/iam/internal/usecase"
)

type IAMServiceServerImpl struct {
	pb.UnimplementedIAMServiceServer
	svc *usecase.IAMUsecase
}

func NewIAMServiceServer(uc *usecase.IAMUsecase) *IAMServiceServerImpl {
	return &IAMServiceServerImpl{svc: uc}
}

var _ pb.IAMServiceServer = (*IAMServiceServerImpl)(nil)
