// Code generated by grpcstubgen. DO NOT EDIT.

package grpc

import (
	pb "secure-rag-platform/api/gen/go/iam/v1"
	"secure-rag-platform/services/iam/internal/usecase"
)

type InternalIAMServiceServerImpl struct {
	pb.UnimplementedInternalIAMServiceServer
	svc IAMUsecaseContract
}

func NewInternalIAMServiceServer(uc *usecase.IAMUsecase) *InternalIAMServiceServerImpl {
	return &InternalIAMServiceServerImpl{svc: usecaseOrNil(uc)}
}

var _ pb.InternalIAMServiceServer = (*InternalIAMServiceServerImpl)(nil)
