// Code generated by grpcstubgen. DO NOT EDIT.

package grpc

import (
	pb "secure-rag-platform/services/iam/gen/v1"
	"secure-rag-platform/services/iam/internal/usecase"
)

type InternalIAMServiceServerImpl struct {
	pb.UnimplementedInternalIAMServiceServer
	deps *serverDeps
}

func NewInternalIAMServiceServer(uc *usecase.IAMUsecase) *InternalIAMServiceServerImpl {
	return &InternalIAMServiceServerImpl{deps: newServerDeps(uc)}
}

var _ pb.InternalIAMServiceServer = (*InternalIAMServiceServerImpl)(nil)
