// Code generated by grpcstubgen. DO NOT EDIT.

package grpc

import (
	"context"
	pb "secure-rag-platform/services/iam/gen/v1"
	"secure-rag-platform/services/iam/internal/usecase"
)

func (s *UserServiceServerImpl) ListUsers(ctx context.Context, req *pb.ListUsersRequest) (*pb.ListUsersResponse, error) {
	_ = req

	principal, _, err := authenticate(s.svc, ctx)
	if err != nil {
		return nil, toGRPCError(err)
	}
	if !isAdmin(principal) {
		return nil, toGRPCError(usecase.ErrForbidden)
	}

	users, err := s.svc.ListUsers(ctx)
	if err != nil {
		return nil, toGRPCError(err)
	}

	items := make([]*pb.User, 0, len(users))
	for _, item := range users {
		items = append(items, userToProto(item))
	}

	return &pb.ListUsersResponse{Users: items}, nil
}
