// Code generated by grpcstubgen. DO NOT EDIT.

package grpc

import (
	"context"
	pb "secure-rag-platform/services/iam/gen/v1"
)

func (s *RoleServiceServerImpl) ListRoles(ctx context.Context, req *pb.ListRolesRequest) (*pb.ListRolesResponse, error) {
	_ = req

	if _, _, err := authenticate(s.svc, ctx); err != nil {
		return nil, toGRPCError(err)
	}

	roles, err := s.svc.ListRoles(ctx)
	if err != nil {
		return nil, toGRPCError(err)
	}

	return &pb.ListRolesResponse{Roles: rolesToProto(roles)}, nil
}
