// Code generated by grpcstubgen. DO NOT EDIT.

package grpc

import (
	"context"
	pb "secure-rag-platform/api/gen/go/iam/v1"
)

func (s *SessionServiceServerImpl) ListUserSessions(ctx context.Context, req *pb.ListUserSessionsRequest) (*pb.ListUserSessionsResponse, error) {
	principal, _, err := authenticate(s.svc, ctx)
	if err != nil {
		return nil, toGRPCError(err)
	}

	sessions, userID, err := s.svc.ListUserSessions(ctx, principal, req.GetUserId())
	if err != nil {
		return nil, toGRPCError(err)
	}

	items := make([]*pb.UserSession, 0, len(sessions))
	for _, session := range sessions {
		items = append(items, sessionToProto(session))
	}

	return &pb.ListUserSessionsResponse{
		UserId:   userID,
		Sessions: items,
	}, nil
}
