// Code generated by grpcstubgen. DO NOT EDIT.

package grpc

import (
	"context"
	pb "secure-rag-platform/services/iam/gen/v1"
	"secure-rag-platform/services/iam/internal/usecase"
)

func (s *AuthServiceServerImpl) Login(ctx context.Context, req *pb.LoginRequest) (*pb.TokenPairResponse, error) {
	if err := s.deps.requireUC(); err != nil {
		return nil, err
	}

	tokens, err := s.deps.uc.Login(ctx, usecase.LoginInput{
		Login:    req.GetLogin(),
		Password: req.GetPassword(),
	})
	if err != nil {
		return nil, toGRPCError(err)
	}

	return &pb.TokenPairResponse{
		AccessToken:  tokens.AccessToken,
		RefreshToken: tokens.RefreshToken,
		ExpiresIn:    tokens.ExpiresIn,
		TokenType:    tokens.TokenType,
	}, nil
}
