// Code generated by grpcstubgen. DO NOT EDIT.

package grpc

import (
	"context"
	pb "secure-rag-platform/api/gen/go/iam/v1"
)

func (s *AuthServiceServerImpl) Logout(ctx context.Context, req *pb.LogoutRequest) (*pb.LogoutResponse, error) {
	_ = req

	if err := requireUC(s.svc); err != nil {
		return nil, err
	}

	accessToken, err := extractBearerToken(ctx)
	if err != nil {
		return nil, toGRPCError(err)
	}

	principal, _, err := s.svc.AuthenticateAccessToken(ctx, accessToken)
	if err != nil {
		return nil, toGRPCError(err)
	}

	revoked, err := s.svc.Logout(ctx, principal, "")
	if err != nil {
		return nil, toGRPCError(err)
	}

	return &pb.LogoutResponse{Revoked: revoked}, nil
}
