// Code generated by grpcstubgen. DO NOT EDIT.

package grpc

import (
	"context"
	pb "secure-rag-platform/services/iam/gen/v1"
)

func (s *AuthServiceServerImpl) LogoutAll(ctx context.Context, req *pb.LogoutAllRequest) (*pb.LogoutAllResponse, error) {
	if err := s.deps.requireUC(); err != nil {
		return nil, err
	}

	accessToken, err := extractBearerToken(ctx)
	if err != nil {
		return nil, toGRPCError(err)
	}

	principal, _, err := s.deps.uc.AuthenticateAccessToken(ctx, accessToken)
	if err != nil {
		return nil, toGRPCError(err)
	}

	result, err := s.deps.uc.LogoutAll(ctx, principal, req.GetUserId())
	if err != nil {
		return nil, toGRPCError(err)
	}

	return &pb.LogoutAllResponse{
		UserId:       result.UserID,
		RevokedCount: result.RevokedCount,
		CtxVer:       result.CtxVer,
	}, nil
}
