// Code generated by grpcstubgen. DO NOT EDIT.

package grpc

import (
	"context"
	pb "secure-rag-platform/services/iam/gen/v1"
	"secure-rag-platform/services/iam/internal/usecase"
)

func (s *RoleServiceServerImpl) RemoveUserRole(ctx context.Context, req *pb.RemoveUserRoleRequest) (*pb.RemoveUserRoleResponse, error) {
	principal, _, err := authenticate(s.svc, ctx)
	if err != nil {
		return nil, toGRPCError(err)
	}
	if !isAdmin(principal) {
		return nil, toGRPCError(usecase.ErrForbidden)
	}

	roles, ctxVer, err := s.svc.RemoveUserRole(ctx, req.GetUserId(), req.GetRoleCode())
	if err != nil {
		return nil, toGRPCError(err)
	}

	return &pb.RemoveUserRoleResponse{
		UserId: req.GetUserId(),
		Roles:  rolesToProto(roles),
		CtxVer: ctxVer,
	}, nil
}
