// Code generated by grpcstubgen. DO NOT EDIT.

package grpc

import (
	"context"
	pb "secure-rag-platform/services/iam/gen/v1"
	"secure-rag-platform/services/iam/internal/usecase"
)

func (s *AttributeServiceServerImpl) ReplaceUserAttributes(ctx context.Context, req *pb.ReplaceUserAttributesRequest) (*pb.ReplaceUserAttributesResponse, error) {
	principal, _, err := s.deps.authenticate(ctx)
	if err != nil {
		return nil, toGRPCError(err)
	}

	targetUserID := req.GetUserId()
	if targetUserID == "" {
		targetUserID = principal.UserID
	}

	if !canAccessUser(principal, targetUserID) {
		return nil, toGRPCError(usecase.ErrForbidden)
	}

	updatedBy := principal.UserID
	attributes, ctxVer, err := s.deps.uc.ReplaceUserAttributes(ctx, targetUserID, structToMap(req.GetAttributes()), &updatedBy)
	if err != nil {
		return nil, toGRPCError(err)
	}

	return &pb.ReplaceUserAttributesResponse{
		UserId:     targetUserID,
		Attributes: mapToStruct(attributes),
		CtxVer:     ctxVer,
	}, nil
}
