// Code generated by grpcstubgen. DO NOT EDIT.

package grpc

import (
	"context"
	pb "secure-rag-platform/api/gen/go/iam/v1"
)

func (s *SessionServiceServerImpl) RevokeSession(ctx context.Context, req *pb.RevokeSessionRequest) (*pb.RevokeSessionResponse, error) {
	principal, _, err := authenticate(s.svc, ctx)
	if err != nil {
		return nil, toGRPCError(err)
	}

	revoked, err := s.svc.RevokeSession(ctx, principal, req.GetSessionId())
	if err != nil {
		return nil, toGRPCError(err)
	}

	return &pb.RevokeSessionResponse{Revoked: revoked}, nil
}
