// Code generated by grpcstubgen. DO NOT EDIT.

package grpc

import (
	"context"
	pb "secure-rag-platform/services/iam/gen/v1"
)

func (s *SessionServiceServerImpl) RevokeSession(ctx context.Context, req *pb.RevokeSessionRequest) (*pb.RevokeSessionResponse, error) {
	principal, _, err := s.deps.authenticate(ctx)
	if err != nil {
		return nil, toGRPCError(err)
	}

	revoked, err := s.deps.uc.RevokeSession(ctx, principal, req.GetSessionId())
	if err != nil {
		return nil, toGRPCError(err)
	}

	return &pb.RevokeSessionResponse{Revoked: revoked}, nil
}
