// Code generated by grpcstubgen. DO NOT EDIT.

package grpc

import (
	"context"
	pb "secure-rag-platform/services/iam/gen/v1"
)

func (s *SessionServiceServerImpl) RevokeAllUserSessions(ctx context.Context, req *pb.RevokeAllUserSessionsRequest) (*pb.RevokeAllUserSessionsResponse, error) {
	principal, _, err := authenticate(s.svc, ctx)
	if err != nil {
		return nil, toGRPCError(err)
	}

	result, err := s.svc.RevokeAllUserSessions(ctx, principal, req.GetUserId())
	if err != nil {
		return nil, toGRPCError(err)
	}

	return &pb.RevokeAllUserSessionsResponse{
		UserId:       result.UserID,
		RevokedCount: result.RevokedCount,
		CtxVer:       result.CtxVer,
	}, nil
}
