// Code generated by grpcstubgen. DO NOT EDIT.

package grpc

import (
	pb "secure-rag-platform/api/gen/go/iam/v1"
	"secure-rag-platform/services/iam/internal/usecase"
)

type RoleServiceServerImpl struct {
	pb.UnimplementedRoleServiceServer
	svc iamUsecase
}

func NewRoleServiceServer(uc *usecase.IAMUsecase) *RoleServiceServerImpl {
	return &RoleServiceServerImpl{svc: usecaseOrNil(uc)}
}

var _ pb.RoleServiceServer = (*RoleServiceServerImpl)(nil)
