// Code generated by grpcstubgen. DO NOT EDIT.

package grpc

import (
	pb "secure-rag-platform/services/iam/gen/v1"
	"secure-rag-platform/services/iam/internal/usecase"
)

type RoleServiceServerImpl struct {
	pb.UnimplementedRoleServiceServer
	svc *usecase.IAMUsecase
}

func NewRoleServiceServer(uc *usecase.IAMUsecase) *RoleServiceServerImpl {
	return &RoleServiceServerImpl{svc: uc}
}

var _ pb.RoleServiceServer = (*RoleServiceServerImpl)(nil)
