// Code generated by grpcstubgen. DO NOT EDIT.

package grpc

import (
	pb "secure-rag-platform/services/iam/gen/v1"
	"secure-rag-platform/services/iam/internal/usecase"
)

type SessionServiceServerImpl struct {
	pb.UnimplementedSessionServiceServer
	deps *serverDeps
}

func NewSessionServiceServer(uc *usecase.IAMUsecase) *SessionServiceServerImpl {
	return &SessionServiceServerImpl{deps: newServerDeps(uc)}
}

var _ pb.SessionServiceServer = (*SessionServiceServerImpl)(nil)
