// Code generated by grpcstubgen. DO NOT EDIT.

package grpc

import (
	pb "secure-rag-platform/api/gen/go/iam/v1"
	"secure-rag-platform/services/iam/internal/usecase"
)

type SessionServiceServerImpl struct {
	pb.UnimplementedSessionServiceServer
	svc IAMUsecaseContract
}

func NewSessionServiceServer(uc *usecase.IAMUsecase) *SessionServiceServerImpl {
	return &SessionServiceServerImpl{svc: usecaseOrNil(uc)}
}

var _ pb.SessionServiceServer = (*SessionServiceServerImpl)(nil)
