// Code generated by grpcstubgen. DO NOT EDIT.

package grpc

import (
	"context"
	pb "secure-rag-platform/services/iam/gen/v1"
	"secure-rag-platform/services/iam/internal/usecase"
)

func (s *RoleServiceServerImpl) SetUserRoles(ctx context.Context, req *pb.SetUserRolesRequest) (*pb.SetUserRolesResponse, error) {
	principal, _, err := s.deps.authenticate(ctx)
	if err != nil {
		return nil, toGRPCError(err)
	}
	if !isAdmin(principal) {
		return nil, toGRPCError(usecase.ErrForbidden)
	}

	assignedBy := principal.UserID
	roles, ctxVer, err := s.deps.uc.SetUserRoles(ctx, req.GetUserId(), req.GetRoleCodes(), &assignedBy)
	if err != nil {
		return nil, toGRPCError(err)
	}

	return &pb.SetUserRolesResponse{
		UserId: req.GetUserId(),
		Roles:  rolesToProto(roles),
		CtxVer: ctxVer,
	}, nil
}
