// Code generated by grpcstubgen. DO NOT EDIT.

package grpc

import (
	"context"
	pb "secure-rag-platform/api/gen/go/iam/v1"
	"secure-rag-platform/services/iam/internal/usecase"
)

func (s *UserServiceServerImpl) UpdateUser(ctx context.Context, req *pb.UpdateUserRequest) (*pb.UpdateUserResponse, error) {
	principal, _, err := authenticate(s.svc, ctx)
	if err != nil {
		return nil, toGRPCError(err)
	}
	if !isAdmin(principal) {
		return nil, toGRPCError(usecase.ErrForbidden)
	}

	var login *string
	if req.Login != nil {
		v := req.GetLogin()
		login = &v
	}

	var password *string
	if req.Password != nil {
		v := req.GetPassword()
		password = &v
	}

	var isActive *bool
	if req.IsActive != nil {
		v := req.GetIsActive()
		isActive = &v
	}

	updated, err := s.svc.UpdateUser(ctx, usecase.UpdateUserInput{
		UserID:   req.GetUserId(),
		Login:    login,
		Password: password,
		IsActive: isActive,
	})
	if err != nil {
		return nil, toGRPCError(err)
	}

	return &pb.UpdateUserResponse{User: userToProto(updated)}, nil
}
