// Code generated by grpcstubgen. DO NOT EDIT.

package grpc

import (
	pb "secure-rag-platform/api/gen/go/iam/v1"
	"secure-rag-platform/services/iam/internal/usecase"
)

type UserServiceServerImpl struct {
	pb.UnimplementedUserServiceServer
	svc IAMUsecaseContract
}

func NewUserServiceServer(uc *usecase.IAMUsecase) *UserServiceServerImpl {
	return &UserServiceServerImpl{svc: usecaseOrNil(uc)}
}

var _ pb.UserServiceServer = (*UserServiceServerImpl)(nil)
