// Code generated by grpcstubgen. DO NOT EDIT.

package grpc

import (
	pb "secure-rag-platform/services/iam/gen/v1"
	"secure-rag-platform/services/iam/internal/usecase"
)

type UserServiceServerImpl struct {
	pb.UnimplementedUserServiceServer
	deps *serverDeps
}

func NewUserServiceServer(uc *usecase.IAMUsecase) *UserServiceServerImpl {
	return &UserServiceServerImpl{deps: newServerDeps(uc)}
}

var _ pb.UserServiceServer = (*UserServiceServerImpl)(nil)
