// Code generated by grpcstubgen. DO NOT EDIT.

package grpc

import (
	"context"
	"strings"

	pb "secure-rag-platform/services/iam/gen/v1"
)

func (s *InternalIAMServiceServerImpl) ValidateAccessToken(ctx context.Context, req *pb.ValidateAccessTokenRequest) (*pb.ValidateAccessTokenResponse, error) {
	if err := s.deps.requireUC(); err != nil {
		return nil, err
	}

	accessToken := strings.TrimSpace(req.GetAccessToken())
	if accessToken == "" {
		if token, err := extractBearerToken(ctx); err == nil {
			accessToken = token
		}
	}

	result, err := s.deps.uc.ValidateAccessToken(ctx, accessToken)
	if err != nil {
		return nil, toGRPCError(err)
	}

	resp := &pb.ValidateAccessTokenResponse{
		Valid:         result.Valid,
		Reason:        result.Reason,
		Subject:       subjectToProto(result.Subject),
		ExpiresAtUnix: result.ExpiresAtUnix,
	}
	if result.Principal != nil {
		resp.SessionId = result.Principal.SessionID
		resp.TokenId = result.Principal.TokenID
	}

	return resp, nil
}
